README.md, dataactbroker/README.md, dataactcore/README.md, dataactvalidator/README.md, doc/CONTRIBUTING.md
Update of the docs after the great repo merge of April, 2016:
* Move background info from dataactcore README to main README
* Remove vestiges of old install directions in favor of the consolidated version
* Install direction updates/fixes
* Add background blurb and link to main README in each of the individual READMES (core, api, validator)
* Replace "coming soon" with a link to the alpha website, hooray!
=> Post repo-merge doc updates

dataactcore/models/jobTrackerInterface.py
@nmonga91 Can you take a look at this, since you're the most familiar with the job queue? Didn't catch this before, but it turns out that the changes introduced for the job queue break the overriding of the database name (for instance, when unit tests are running). This didn't come to light until I was changing the database names as part of another story.
Will this updated code work with the queue logic?
=> hotfix for overriding job db name

dataactvalidator/interfaces/stagingTable.py
Small hotfix to the staging table change to not include 'u' in front of every field name.
=> Not including 'u' for unicode in the map put in the staging table

dataactcore/migrations/env.py
This PR fixes a bug that was, in some cases, preventing data model metadata from being passed to the Alembic context. This problem was only occurring in cases where the database names in the broker's config.yml don't match the original database names that were hard-coded into the app back in the day.
=> fix bug in alembic metadata setup

dataactvalidator/filestreaming/schemaLoader.py
File ID was being provided as a field ID when cross file rules were loaded, which caused a foreign key bug
=> Fixes cross file rule loading's use of common addRule function

dataactcore/migrations/versions/3a79d7a4d1c1_merge_rule_tables.py
Some of the downgrade text that alembic presumably auto-generated was breaking things when running downgrades.
=> Hotfix for alembic backwards migrations

dataactvalidator/validation_handlers/validator.py, tests/fileTypeTests.py
Initial implementation of BPOA check fails the record if year cannot be cast to an int, but fails to make an exception for blank values
=> Hotfix blank year

dataactcore/scripts/migrateDataBroker.py
I know we discussed not using a script for the data migration, but I still felt more comfortable putting together something repeatable and programmatic. This uses `pg_dump` and `pg_restore` to grab data from our old databases and insert it into its new home.
The script is in python simply so that we can grab the database credentials from `DB_CONFIG`. Otherwise, it's just executing postgres shell commands. It should be safe to run the shell commands and pipe data from the dump to the restore, since we're controlling the input.
Lastly, the script is repeatable. If you run it multiple times, it will throw errors on primary key violations.
=> add data migration script

dataactcore/scripts/migrateDataBroker.py
The data migration script failed on sandbox because migration that runs against the old staging tables to drop `valid_record` was removed from the migration history and never runs.
Thus, the old tables have that column and the new ones do not, causing the migration script to error. Added a patch that just removes that column in the old db if it's there. 
Also added the `--single-transaction` flag to the`pg_restore` command to ensure that we don't end up with any half-migrated tables.
Again, this script will only work if the target tables are empty, so we'll have to coordinate with @klrBAH when in the deploy process it should run.
=> fix for out-of-sync valid_record column

tests/unit/conftest.py, tests/unit/dataactvalidator/test_a16_appropriations.py, tests/unit/dataactvalidator/test_sql_validations.py, tests/unit/dataactvalidator/utils.py
Rough cut; we'll probably want to need to add more setup information, but this
should get us started. See test_a16_appropriations for example usage.
conftest.py adds a fixture related to database setup (monkeying what is in the
baseTestValidator.py). We'll probably also want to use something like
factory-boy to make generating example models easier.
=> Add some sql-rule validations + skeleton for more

dataactvalidator/filestreaming/loadFile.py
Since we're temporarily bulk loading the historical SF-133 data, we'll also need to temporarily bypass the current SF-133 loader, which will delete everything in that table whenever we deploy.
The bulk load is a temporary measure to ensure that we have a set of FY 2016 SF-133 data for use by the GTAS validations. The [completed DB-862 story](https://federal-spending-transparency.atlassian.net/browse/DB-862) will restore the SF-133 load.
=> temporarily bypass the SF-133 load

requirements.txt, tests/unit/dataactcore/factories/domain.py, tests/unit/dataactcore/factories/staging.py, tests/unit/dataactvalidator/test_a10_appropriations.py
Factories should make generating nonsense data a little bit easier, which means our tests can focus on only the essential information. This includes factories for SF133 and Appropriations and uses them in one of the unittests as a demonstration.
=> Introduction of Factory Boy

tests/integration/runTests.py
This prevents actual emails from being sent during the integration tests
=> Mock out sesEmail.send

tests/integration/conftest.py
This is a hack, but will should fix the immediate problem of integration tests
sending out email. Previously, we had fixed if a user ran `runTests.py`
directly, but if using `py.test`, tests outside the scope of `runTests` will
be auto-discovered (and not use the mock)
=> Mock out SES for py.test integration tests

dataactcore/migrations/versions/c9090bf7f0a8_sf_133_add_index_year.py, dataactcore/models/domainModels.py
Realized today that the unique index on the SF-133 is missing `fiscal_year`. We need to get that on there or the load file will fail in a few months.
Apologies for not noticing this until we had a few million rows loaded--the migration takes a few minutes to run.
=> add fiscal year to SF_133 index

dataactbroker/app.py, dataactvalidator/app.py
Setting the debug on app.run wasn't working. Do it when we create
the app. To turn off debug, set server_debug = false in config.yml.
=> Use debug setting in config.yml when creating Flask apps

dataactcore/models/jobTrackerInterface.py, dataactcore/utils/jobQueue.py
This reports when a job is sent to the job manager, when it arrives, and when the response from the validator comes back.
=> Adding log messages to job queueing

dataactvalidator/interfaces/validatorErrorInterface.py, dataactvalidator/validation_handlers/validationManager.py
This adds a File object for cross-file jobs to allow the check_status route to report cross-file errors and warnings correctly
=> Hotfix cross file status

dataactbroker/scripts/loadFSRS.py, dataactcore/migrations/env.py, tests/unit/conftest.py, tests/unit/dataactbroker/test_fsrs.py, tests/unit/dataactcore/test_utils_fileF.py, tests/unit/dataactvalidator/test_a10_appropriations.py, tests/unit/dataactvalidator/test_a11_appropriations.py, tests/unit/dataactvalidator/test_a12_appropriations.py, tests/unit/dataactvalidator/test_a14_appropriations.py, tests/unit/dataactvalidator/test_a15_appropriations.py, tests/unit/dataactvalidator/test_a16_appropriations.py, tests/unit/dataactvalidator/test_a18_cross_file.py, tests/unit/dataactvalidator/test_a19_cross_file.py, tests/unit/dataactvalidator/test_a22_appropriations.py, tests/unit/dataactvalidator/test_a23_appropriations.py, tests/unit/dataactvalidator/test_a29_appropriations.py, tests/unit/dataactvalidator/test_a30_appropriations.py, tests/unit/dataactvalidator/test_a30_object_class_program_activity.py, tests/unit/dataactvalidator/test_a32_appropriations.py, tests/unit/dataactvalidator/test_a33_appropriations_1.py, tests/unit/dataactvalidator/test_a33_appropriations_2.py, tests/unit/dataactvalidator/test_a6_appropriations.py, tests/unit/dataactvalidator/test_a7_appropriations.py, tests/unit/dataactvalidator/test_a8_appropriations.py, tests/unit/dataactvalidator/test_a9_appropriations.py, tests/unit/dataactvalidator/test_b14_object_class_program_activity.py, tests/unit/dataactvalidator/test_b15_object_class_program_activity.py, tests/unit/dataactvalidator/test_b19_object_class_program_activity.py, tests/unit/dataactvalidator/test_b20_object_class_program_activity.py
This PR mainly updates the unit tests to get a database fixture using the functions in `dataactcore/interfaces/db.py` instead of baseInterface + interface holder.
A few miscellaneous items included:
* Update the FSRS loader (another one I forgot in PR #272)
* Migrations now use the common URI function in db.py instead of repeating the code to create a URI string
@mab6bf @jworcestBAH @nmonga91 @cmc333333: heads-up that once this is merged, the syntax for referencing the pytest database fixture will change slightly.
Old: `database.stagingDb`
New: `database`
=> db connection refactor part 2: unit tests

dataactvalidator/scripts/loadFile.py, dataactvalidator/scripts/loaderUtils.py
On our latest SF-133 file from GTAS, a few fields that had
previously been filled with spaces are now coming in as empty
values. We'll speak to the team about  not
altering the file format month-to-month, but it seemed
reasonable to make this small fix to handle either case.
=> Handle empty values in non-padded TAS fields.

dataactvalidator/config/sqlrules/b14_object_class_program_activity.sql, dataactvalidator/config/sqlrules/b15_object_class_program_activity.sql, tests/unit/dataactvalidator/test_b14_object_class_program_activity.py, tests/unit/dataactvalidator/test_b15_object_class_program_activity.py
These rules were updated to check the sum for all records within a TAS against the sf-133 amount for that TAS rather than checking each record against the amount individually.
=> B14 and B15 updated to sum for each tas, unit tests updated to match

.gitignore, dataactcore/config_example.yml, dataactcore/local_config_example.yml, dataactcore/local_secrets_example.yml, doc/CONTRIBUTING.md
Create two new config samples (local_config_example.yml and
local_secrets_example.yml) to match the changes to the broker's
config handling. Also update the install docs to explain how
these files are used.
Took my best guess at a reasonable way of splitting up values between the three sample files. Happy to go back and forth on this. Ultimately, though, I think the sample files matching our particular use is less important than making sure that folks reading the install docs know what to do.
=> Update docs to match environment-specific broker config.

dataactbroker/handlers/fileHandler.py, dataactcore/utils/jobQueue.py, tests/unit/dataactcore/test_job_queue.py
As the parameters to write_csv have changed, we need to modify their usage in file F generation, too. This also adds back a unit test which had been accidentally deleted to catch this sort of error in the future.
=> Update file F's write_csv

dataactcore/migrations/env.py
I had removed some of these model imports  when making  unrelated changes
to env.py b/c the IDE was marking them as unused. They do need to be
there, however, else Alembic won't know which models to check when
autogenerating migrations.
=> Make sure alembic is aware of all models in use.

tests/unit/dataactvalidator/test_b18_object_class_program_activity_1.py, tests/unit/dataactvalidator/test_b18_object_class_program_activity_2.py
This fixes object class handling for B18 to avoid failures that were occurring for object classes under 100
=> Fixed B18 test to fill object classes up to three digits

dataactcore/models/lookups.py, dataactcore/scripts/setupErrorDB.py, dataactcore/scripts/setupJobTrackerDB.py, dataactcore/scripts/setupUserDB.py, dataactcore/scripts/setupValidationDB.py
This is a companion to PR #303. Based on suggestions from @jworcestBAH and @cmc333333, this moves our static helper values out of the database load scripts and into a common file. This way, they can be referenced as needed, which will:
1. make the in-application surrogate lookups more straightforward than the current methods in `baseInterface.py`
2. still allow the database load scripts to populate the helper tables
If this looks good, I'll cleanup up the integration test code in #303 to use these constants instead of dynamically populating dictionaries from the database (see: https://github.com/fedspendingtransparency/data-act-broker-backend/pull/303#discussion_r81338600)
=> Create a file with lookup values used by the broker

dataactcore/interfaces/function_bag.py, dataactcore/models/errorInterface.py, dataactcore/models/jobTrackerInterface.py, tests/integration/baseTestAPI.py, tests/integration/fileTests.py
This PR completes the removal of the old db interfaces from the fileTests.py suite of integration tests.
The changes might make more sense when reviewing commit by commit.
=> Remove db interfaces from the fileTests suite of integration tests

dataactvalidator/validation_handlers/validator.py
Fixes a bug where rule descriptions were displayed as error messages for cross-file validations
=> Cross file validation now uses error message instead of description

dataactbroker/handlers/fileHandler.py, dataactcore/models/errorInterface.py, dataactcore/models/validationInterface.py, dataactcore/utils/report.py, dataactvalidator/validation_handlers/validationManager.py, dataactvalidator/validation_handlers/validator.py, tests/integration/baseTestValidator.py, tests/integration/fileTypeTests.py, tests/integration/mixedFileTests.py, tests/integration/validatorTests.py
This PR removes the remaining database interfaces from the validator unit tests.
=> Remove db interfaces from validator tests - part 3 and final

dataactbroker/scripts/initialize.py
Didn't catch this in tests, because test setup invokes the
setup functions individually.
=> hotfix: add missing import to the dataactbroker initialize script

dataactvalidator/scripts/loadTas.py, tests/integration/data/all_tas_betc.csv, tests/unit/dataactvalidator/test_scripts_loadTas.py
We're getting our TAS files from a different source now, which has a slightly
different set of columns. Modify the import script to accommodate and replace
the CSVs included in the app. The logic is simplified as our data source is
now more accurate (not including duplicate rows, for example).
This is a first step towards replacing the `tas` field in our models with the new `ACCT_NUM`-based approach.
=> Change TAS file format

dataactbroker/handlers/jobHandler.py, tests/integration/baseTestAPI.py, tests/integration/runTests.py
This also makes it possible to just run `py.test` from the root of the project without errors.
=> Remove nonpytest runner

dataactbroker/app.py, dataactcore/config_example.yml, dataactcore/local_config_example.yml, dataactvalidator/app.py
This commit uses the new debug flag for all debug-related settings.
Going forward, code that needs to know the debug status of the app
can either get it from app.debug, if the Flask app is handy, or
from CONFIG_SERVICES['debug'].
The new flag has already been merged into the config repo: https://github.com/fedspendingtransparency/data-act-broker-config/pull/25
Folks will have to add debug to their local configs once this is merged.
=> Use new, consolidated debug flag when creating Flask apps

dataactcore/migrations/versions/bb33cc8f0a3e_setting_submission_error_numbers_to_.py, dataactcore/models/jobModels.py
This pull request upgrades the number_of_errors and number_of_warnings fields in the submission and job models to default to 0 to prevent errors.
=> Updating the submission and job models

dataactcore/interfaces/function_bag.py, setup.cfg
These are auto-generated files, so we don't really need to lint them. Also fixes a linting bug. We should be able to turn on linting on Jenkins after this.
=> Exclude migrations from flake8

dataactvalidator/app.py, dataactvalidator/validation_handlers/validationManager.py, tests/integration/jobTests.py
I went through a lot of iterations on this and finally came back to @cmc333333's advice of keeping
things simple for the first go-round.
This PR tries to reduce the layers of try/except that wrap the validation application and process. Ultimately, I needed to untangle these layers to best proceed with the JobTracker database refactor.
Best to step through the commits--I tried to explain everything in the messages.
Once this is reviewed and merged, the next step is to remove the second try/except block in `validation_job`
=> Global validation error handling

dataactcore/aws/s3UrlHandler.py
This is a hotfix to address an issue we had with initial validations getting stuck on dev. There's more to unpack here (_e.g._, is there a way to prevent the app from getting stuck when there's an unhandled exception like this, why is this suddenly a problem), but this should at least get folks past that first validation screen.
=> Return 0 for filesize if S3 file not found

.codeclimate.yml
First stab at a custom .codeclimate.yml for this project. It explicitly excludes alembic migrations (which were previously included) and anything in`tests/` (no change...these were excluded before).
In an effort to make the reports more actionable, also disabled the similar code check. The duplication engine is still enabled, but the similar code check specifically was turning up what I consider to be distracting false positives.
Obviously, open for discussion!
=> .codeclimate.yml

dataactcore/aws/s3UrlHandler.py, dataactvalidator/validation_handlers/validationManager.py
We had been using the file size of an error report on AWS. This also adds a log message whenever we can't find the file to determine its size on AWS.
=> Use submission file when determining file size

dataactbroker/fileRoutes.py, dataactbroker/handlers/accountHandler.py, dataactbroker/handlers/fileHandler.py, dataactbroker/permissions.py, dataactbroker/userRoutes.py, dataactcore/interfaces/function_bag.py, dataactcore/migrations/versions/963cad0fd72a_add_admin_field_to_user.py, dataactcore/models/lookups.py, dataactcore/models/userModel.py, dataactcore/scripts/initialize.py, tests/integration/baseTestAPI.py, tests/unit/dataactbroker/test_account_handler.py
We'll be allowing users to have multiple agencies with different levels of permission for each, so having the `website_admin` permission on the agency level doesn't make sense. This also removes two fictitious permission names.
=> Separate out superuser logic

dataactbroker/handlers/accountHandler.py, tests/unit/dataactbroker/test_account_handler.py
Allowing anyone with a max account the ability to see the help pages by removing the CGAC check and only setting the CGAC if it's available.
=> MAX account help page access

dataactcore/utils/fileF.py, tests/unit/dataactcore/test_utils_fileF.py
Data for this field needed to be pulled from D1, so this adds a subquery to
grab that. It also converts the mapper interface to use a callable (rather
than an object with a `transform` method).
=> Account for NAICS_Description field in file F

dataactbroker/handlers/accountHandler.py, dataactbroker/handlers/fileHandler.py, dataactbroker/permissions.py, dataactcore/models/lookups.py, tests/integration/baseTestAPI.py, tests/unit/conftest.py, tests/unit/dataactbroker/test_account_handler.py, tests/unit/dataactbroker/test_domainRoutes.py, tests/unit/dataactbroker/test_permissions.py
This includes the first half of an effort to replace our permissions checks (which rely on a user's _single_ permission level) to a per-agency check. Easiest to step through changeset by changeset, but this is largely foundation for part 2, which makes use of these functions.
* Read in multiple user affiliations from MAX
* Remove unused parameters
* Add functions to check user permission for a specific agency
=> Use affiliations to determine permissions, part 1

dataactbroker/README.md, dataactbroker/fileRoutes.py, dataactbroker/handlers/fileHandler.py, dataactbroker/permissions.py, dataactcore/interfaces/function_bag.py, dataactcore/models/jobModels.py, tests/unit/dataactbroker/test_file_handler.py, tests/unit/dataactbroker/test_handlers_fileHandler_sign_url.py, tests/unit/dataactbroker/test_permissions.py
Builds on #467 ([diff](https://github.com/fedspendingtransparency/data-act-broker-backend/compare/db-1386-3-permission-setup...db-1386-4-use-permissions))
This adds goes through each of the `fileHandler` endpoints and switches each over to inspect user affiliations for permissions. A lot of code changes, but it's relatively repetitive after the foundation is laid in the first few commits.
Tested this locally as a `website_admin` and on sandbox as a `writer` (but not admin).
=> Use affiliations to determine permissions, part 2

dataactbroker/README.md, dataactbroker/handlers/fileHandler.py, dataactcore/models/errorModels.py, dataactcore/models/jobModels.py, dataactcore/models/lookups.py, tests/unit/dataactbroker/test_file_handler.py
We can look up this information by calling the agency list API, but why do that when we can include it in the agency response? This also gave a good opportunity to disentangle some of the submission/job-to-dictionary logic into separate functions.
=> Include agency_name in submission info

dataactcore/utils/fileE.py, tests/unit/dataactcore/test_utils_fileE.py
In some situations, these attributes are empty (represented by the empty
string); in other situations they are not present. Account for both
situations and test.
Found this bug while updating authentication credentials.
=> Account for non-existent attributes in file E

dataactvalidator/config/sqlrules/b9_award_financial.sql, tests/unit/dataactvalidator/test_b9_award_financial.py
Updating B9/10 for File C to exclude those rows with both a null program activity code and null program activity name, updated tests
=> Bug fix for B9/10 Validation for File C only

dataactcore/migrations/env.py
Alembic needs to know about all of the app's models, which means we need to
import them. This line was taken out during a recent refactor, but we still
need it until we can load those models dynamically.
This fixes alembic migration generation; it _may_ be required to upgrade the database.
=> Add back all of the model types

dataactvalidator/config/sqlrules/b12_award_financial_1.sql, dataactvalidator/config/sqlrules/b12_object_class_program_activity_1.sql, tests/unit/dataactvalidator/test_b12_award_financial_1.py, tests/unit/dataactvalidator/test_b12_object_class_program_activity_1.py
Modify implementation of B12 to also exclude 4831, 4832, and 4931 from requiring the D/R field to be populated. These USSGLs can also have the D/R field blank, just like the downward USSGLs (4x7x).
=> Modify B12 to be able to submit blank D/R fields to 4831, 4832, and 4931

dataactvalidator/config/sqlrules/b12_award_financial_1.sql, dataactvalidator/config/sqlrules/b12_object_class_program_activity_1.sql, dataactvalidator/config/sqlrules/b9_award_financial.sql, dataactvalidator/config/sqlrules/b9_object_class_program_activity.sql, tests/unit/dataactvalidator/test_b12_award_financial_1.py, tests/unit/dataactvalidator/test_b12_object_class_program_activity_1.py, tests/unit/dataactvalidator/test_b9_award_financial.py, tests/unit/dataactvalidator/test_b9_object_class_program_activity.py
- Broker only validates program activity if we have the domain values for that year
- Broker does not validate FY 2017 program activity data since we don't have the values
=> B9 validate years

dataactvalidator/config/sqlrules/b9_award_financial.sql, dataactvalidator/config/sqlrules/b9_object_class_program_activity.sql
Improving B9 performance through the utilization of temporary tables in order to reduce the execution time of the JOIN with program_activity
=> B9 Perfomance Improvement

dataactcore/aws/sqsHandler.py, dataactvalidator/app.py
Database connections are now opened/closed at the beginning and end of the loop, respectively. Also, the python process is no longer terminated when an exception is raised, but instead the exception is logged and the polling continues.
=> Hotfix for open database connections

dataactvalidator/config/sqlrules/b11_award_financial_1.sql, dataactvalidator/config/sqlrules/b11_award_financial_3.sql, dataactvalidator/config/sqlrules/b11_object_class_program_activity_1.sql, dataactvalidator/config/sqlrules/b11_object_class_program_activity_3.sql, tests/unit/dataactvalidator/test_b11_award_financial_3.py, tests/unit/dataactvalidator/test_b11_object_class_program_activity_3.py
We can't pad the 0 value to 000 for the object class because it currently accept 3 and 4 digits.  The change to this commit is to add an exception for `0` and `00` and add test cases.
=> Add exception for '0'/'00'

dataactvalidator/config/awardFields.csv, dataactvalidator/config/detachedAwardFields.csv
Pad assistancetype column so it always has 2 characters. Stops auto-truncating in excel from causing errors.
Technical Changes:
- file_column table updates, will need to reinitialize the table
=> DB 1674 pad assistanceType

dataactvalidator/filestreaming/csvAbstractReader.py
As an agency user, I want to be able to submit a B file that doesn't have a typo in the field
A/C:
- User can submit a file B file that either does or doesn't have the typo in the DeobligationsRecoveriesRefundsdOfPriorYearByProgramObjectClass_CPE field.
Technical changes:
Need to run `python scripts/initialize.py -i`.
=> db-1599 Map correct/incorrect deobligationsrecoveriesrefunds

dataactvalidator/config/sqlrules/c11_cross_file.sql, dataactvalidator/config/sqlrules/c12_cross_file.sql, dataactvalidator/config/sqlrules/c8_award_financial.sql, dataactvalidator/config/sqlrules/c9_award_financial.sql, tests/unit/dataactvalidator/test_c11_cross_file.py, tests/unit/dataactvalidator/test_c12_cross_file.py, tests/unit/dataactvalidator/test_c8_award_financial.py, tests/unit/dataactvalidator/test_c9_award_financial.py
- C8/C9 validation is only performed on rows in file C that have a transaction obligated amount value in the field
- C11/C12 validation is only performed on rows in file C that have a transaction obligated amount value in the field
Technical Changes:
SQL Rule Updates
=> db-1209 Performed only w a transaction obligated amount value

dataactvalidator/config/sqlrules/b9_award_financial.sql, dataactvalidator/config/sqlrules/b9_object_class_program_activity.sql, tests/unit/dataactvalidator/test_b9_award_financial.py, tests/unit/dataactvalidator/test_b9_object_class_program_activity.py
- B9/B10 validations are not case sensitive when validating program activity name
Technical changes:
SQL validation changes
@kaitlin 
I can't replicate the error for the case sensitive. But added `LOWER` to the program activity name to make sure it ignores case.
=> Change program activity to ignore case

dataactbroker/README.md, dataactbroker/fileRoutes.py, tests/integration/fileTests.py
Submissions should only be deletable if they are unpublished (updated and published submissions are not deletable)
=> Db 1760 Deleting published submissions

dataactvalidator/config/sqlrules/c12_cross_file.sql, tests/unit/dataactvalidator/test_c12_cross_file.py
As an agency user, I need to see my previous C12 warnings
If a PIID and PAID combination exists in D1, it should show a warning if it does not exist in C
If a PIID (with null PAID) is in D1, it should show a warning if it does not exist in C
Technical changes: 
SQL rules (Change the rule back to previous commit)
=> DB-1759 I need to see my previous C12 warnings

dataactvalidator/config/sqlrules/c9_award_financial.sql, tests/unit/dataactvalidator/test_c9_award_financial.py
Stop using transaction_obligated_amou in this check.
Also making sure that any combination of fain/uri (including nulls) from D2 must be replicated exactly in C for this warning to not go off.
Adding a "with" to speed things up.
=> Db 1770 fix c9 warnings

dataactbroker/handlers/fileHandler.py
Properly populates the submission table for the dashboard and adds publish status for the recent activity table
=> Queries should be based on published status, not the unpublished status

dataactvalidator/config/sqlrules/b11_award_financial_1.sql, dataactvalidator/config/sqlrules/b11_award_financial_2.sql, dataactvalidator/config/sqlrules/b11_object_class_program_activity_1.sql, dataactvalidator/config/sqlrules/b11_object_class_program_activity_2.sql, dataactvalidator/config/sqlrules/b18_object_class_program_activity.sql, dataactvalidator/config/sqlrules/b9_object_class_program_activity.sql, tests/unit/dataactvalidator/test_b11_award_financial_2.py, tests/unit/dataactvalidator/test_b11_object_class_program_activity_2.py, tests/unit/dataactvalidator/test_b18_object_class_program_activity.py, tests/unit/dataactvalidator/test_b9_object_class_program_activity.py
For TAS in file B that have zeros for each of the financial data elements (USSGL and related subtotals):
- Accept blanks for program activity name (B9) without warnings
- Accept 0000 for program activity code (B10) without warnings (note, it is ok for the 0 to be padded)
- Accept 000/0000 for object class (B11) without warnings (note, it is ok for the 0 to be padded)
- Accept D, R, or blank for D/R field regardless of whether a 3 or 4 digit object class is given (B12, B18) without warnings
Some of these already happened, but those that didn't have been updated.
- Updates to validation rules, need to reload them to the db
=> Db 1748 b rule fixes zeroes allowed

dataactcore/utils/fileF.py, requirements.txt
Altering PIID and PAID comparisons to use "IS NOT DISTINCT FROM" for better NULL value handling.
- Updated `requirement.txt` to upgrade SQLAlchemy version from `1.0.9` to `1.1.9`
=> Resolving inconsistent F file generation

dataactbroker/handlers/fileHandler.py, dataactcore/aws/s3Handler.py
Hotfix to stream D files non-locally instead of saving to memory. Fixes the Memory Error we kept getting when DoD tried to generate their D1 file.
Also uses threads to continue the streaming so we don't make MetroStar wait too long on their callback response. If we do, it sends it again and we end up downloading multiple 1GB+ files
=> Db 1819 allow large files to generate

dataactvalidator/validation_handlers/validationManager.py
Resetting error metadata for regular csv validations, same as what cross-file validations already do.
=> Error data no longer compounding for file level validations

dataactbroker/handlers/fileHandler.py
Whenever one of the D files is being generated, make sure the cross-file validation job is in a 'waiting' status it's not already. This will ensure the dependency check will kick off the cross-file validation job.
Checklist:
=> D File completion kicks off cross-file validation

celeryconfig.py, dataactbroker/handlers/fileGenerationHandler.py, dataactbroker/handlers/fileHandler.py, dataactcore/config.py, dataactcore/config_example.yml, doc/CONTRIBUTING.md, requirements.txt, tests/unit/dataactbroker/test_file_generation_handler.py
Moving job manager functionality for File E and F generation into the broker, which will now use threading to start the generation of the files.
Checklist:
- No longer using Celery & RabbitMQ for asynchronous job execution
=> Removing job manager

dataactcore/scripts/readZips.py, dataactvalidator/config/detachedAwardFields.csv
Fixing a couple bugs:
- reading "all" files locally on a mac for the zip loader script would try to read hidden files as well (that's bad)
- padding congressional district no with leading 0s because it's either 2 letters or 2 numbers and the numbers get truncated sometimes.
=> Bug fixes for zip reading parsing

dataactbroker/fileRoutes.py, tests/integration/fileTests.py
Fixing the check if a certified submission already exists to include "updated" as a certified submission. Added another test to check for this case
=> Db 2030 fixing certified submission check

dataactvalidator/config/sqlrules/d31_detached_award_financial_assistance_2.sql, tests/unit/dataactvalidator/test_d31_detached_award_financial_assistance_2.py
- For rule D31, AwardeeOrRecipientUniqueIdentifier must be blank for aggregate records (i.e. RecordType = 1) and individual recipients (i.e., when BusinessTypes includes "P").
- Update to a SQL rule
=> DB-2034 update d31 to include record_type and business_types check

dataactvalidator/config/sqlrules/d37_detached_award_financial_assistance_1.sql, dataactvalidator/config/sqlrules/d37_detached_award_financial_assistance_2.sql
Stopping the validations from imploding when cfda_number is letters. The format check was correct before it just never got through validations if it wasn't all numbers.
Comparing using the existing string (it should be more accurate this way anyway)
- Updated sql rule
=> Db 2047 cfda number format

dataactvalidator/validation_handlers/validationManager.py, dataactvalidator/validation_handlers/validator.py
Entering something that is too long for the field is now an error in FABS but still warning in normal submissions
=> Db 2065 fabs max length error

dataactbroker/README.md, dataactcore/models/lookups.py, dataactvalidator/validation_handlers/validationError.py
Changing text in "type_error" so it's more clear that other validations didn't run.
- Updating error text, will have to reinitialize your DB
=> Db 2068 updating wrong type error text

dataactbroker/domainRoutes.py, dataactbroker/handlers/fileHandler.py
Temporarily allowing all users to see all agencies in the FABS upload page.
This will need to be changed back at a later date but is needed for testing.
=> Allow all users to upload fabs

dataactvalidator/config/sqlrules/d43_detached_award_financial_assistance_1.sql, dataactvalidator/config/sqlrules/d43_detached_award_financial_assistance_2.sql, tests/unit/dataactvalidator/test_d43_detached_award_financial_assistance_1.py, tests/unit/dataactvalidator/test_d43_detached_award_financial_assistance_2.py
+ Fixing what columns are printed for one part of the rule
+ Making zip+4 or CD required only when country code is USA
=> Db 2054 d43 only applies domestically

dataactvalidator/scripts/readZips.py
Hardcoding a couple of cases for the zip loader. Also slid in a little speedup, approximately 1/6 faster than before.
```
DELETE FROM zips
WHERE state_abbreviation IN ('AA', 'AE', 'AP');
UPDATE zips
SET state_abbreviation = 'UM', congressional_district_no = '99', county_number = '450'
WHERE zip5 = '96898';
UPDATE zips
SET congressional_district_no = '00'
WHERE state_abbreviation IN ('AK', 'DE', 'MT', 'ND', 'SD', 'VT', 'WY');
UPDATE zips
SET congressional_district_no = '98'
WHERE state_abbreviation IN ('AS', 'DC', 'GU', 'MP', 'PR', 'VI');
UPDATE zips
SET congressional_district_no = '99'
WHERE state_abbreviation IN ('FM', 'MH', 'PW', 'UM');
```
Technical release notes:
- Updated zip loader, might want to rerun initialize (at least with a -z flag)
=> Db 2073 zip code loader edge cases

dataactvalidator/validation_handlers/validationManager.py, dataactvalidator/validation_handlers/validator.py
AC:
- Files correctly show "has errors" in red when they have critical errors.
=> DB-2100 fix FABS dashboard statuses

dataactcore/models/lookups.py, dataactvalidator/app.py, dataactvalidator/validation_handlers/validationError.py, dataactvalidator/validation_handlers/validationManager.py
AC:
- Confirm the number of rows in the file matches the number of rows loaded by the validator
- File will fail file-level validation if the number of rows does not match
- Added new error type (row count), will need to run setupAllDB.py
=> DB-2113 check submission row counts

dataactbroker/handlers/fileHandler.py, dataactcore/scripts/pullFPDSData.py, tests/unit/dataactbroker/test_fabs_derivations.py
- `AwardProcurement` and `AwardFinancialAssistance` data's `awarding_agency_code` and `funding_agency_code` columns provide FREC codes when the sub_tier_agency_code is FREC based
Technical Specifications:
- Updating FABS derivations and FPDS script
=> Mapping Awarding Agency Code to FRECs if is_frec

dataactbroker/fsrs.py, dataactbroker/scripts/loadFSRS.py, dataactcore/utils/fileF.py, tests/unit/dataactbroker/test_fsrs.py
Updating the FSRS loader and F file generation
- FSRS loader now deletes based on internal_id rather than the iterating id so it will find duplicates and delete old ones
- FSRS loader loops until there are no records to be updated
- F file generation is now based on distinct fain for grants and piid, awarding sub tier agency code, and parent award id for procurements so even if the D files have multiples, it'll only put one of each in
This isn't as many changes as it looks like, a lot of the lines are formatting/readability updates
- Updated FSRS loader so if there is local FSRS data it might be prudent to wipe it and start from scratch (if there isn't, nothing for local devs to do)
=> Db 2136 fsrs generation

dataactvalidator/validation_handlers/validationManager.py
AC:
- File with extension `.CSV` does not throw a file type error
=> DB 2214 fix file extension capitalization bug

dataactbroker/handlers/fileHandler.py
AC:
- FABS submissions with `city-wide` in their `place_of_performance_zip4a` do not throw a 500 error during derivations
related ticket: https://federal-spending-transparency.atlassian.net/browse/DB-2234
=> HOTFIX: account for 'city-wide' as place_of_performance_zip4a during FABS derivations

dataactbroker/handlers/fileHandler.py
Not copying created_at and updated_at when publishing FABS
=> Hotfix created updated at dates fabs

dataactbroker/handlers/fileHandler.py, dataactcore/models/lookups.py
- Requires re-initialization of the database
- Updates all submission responses publish state to be either 'published' 'updated' 'unpublished' or 'publishing'
=> Db mk 2246 publish duplicate v2

dataactbroker/README.md, dataactbroker/fileRoutes.py, dataactbroker/handlers/fileHandler.py, tests/integration/fileTests.py
Prevent duplicate transactions from being published if a different submission with the same new entries is published.
- Updated route `restart_validation` to allow for restarting FABS! validations
- Updated route `submit_detached_file` to check for new rows before continuing
=> Db 2125 prevent duplicate fabs time

dataactbroker/handlers/fileHandler.py
I was pushing a copy of the published FABS file to the regular submission bucket using the certified FABS path, let's not do that anymore.
=> DB-2289 published FABS files in certified bucket only

dataactbroker/handlers/fileHandler.py
When someone creates a submission that becomes the owner of a cached file, then regenerates the D files within that same submission, it never changes the upload job to `running`. So when we run `mark_job_status`, we miss out because of this `if` statement:
> `    if old_status != 'finished' and status_name == 'finished' and not skip_check:`
> `        check_job_dependencies(job_id)`
=> Hotfix: mark D file generation upload job as "running"

dataactbroker/handlers/fileHandler.py
Submission Finalize only checked DABS permissions and if user was the submission creator. FABS permission users updating a submission created by someone else would get stuck after upload. 
This is no longer an issue.
=> Hotfix Fabs Finalize by FABS-only user

dataactbroker/handlers/fileGenerationHandler.py
Set the FileRequest object to true before generating the D file to make sure there aren't multiple generations going on at the same time
=> Hotfix: mark Job as cached file before generating file

dataactbroker/fileRoutes.py
This route is specific for dabs submissions and dabs submissions are the only one that needs to check for a submission with an existing period. FABS route does not care if there are published submissions with existing periods
using == with # noqa because checking 'is False' will break sqlAlchemy and this will throw a flake warning
=> Hotfix - Existing Dabs Submission Check Bug

dataactvalidator/config/sqlrules/b9_award_financial.sql, dataactvalidator/config/sqlrules/b9_object_class_program_activity.sql, tests/unit/dataactvalidator/test_b9_award_financial.py, tests/unit/dataactvalidator/test_b9_object_class_program_activity.py
https://federal-spending-transparency.atlassian.net/browse/DEV-49
A/C:
- Update B9 execution to accept PA name/code per AID/ATA/MAC combo in authoritative OMB list for FY 2018
- Until we get official OMB policy, make it year agnostic. In other words, validation checks FY16,17, and 18 list.
- SQL rule updates
=> DEV-49 Update B9 (B10) to check for 2016-2018

dataactvalidator/scripts/loadLocationData.py
https://federal-spending-transparency.atlassian.net/browse/DEV-48
- readZips.py strings are trimmed before being inserted into DB
- loadLocationData.py load_zip_city_data strings are trimmed before being inserted into DB
(_dev note: bullet one is not needed, because all records pulled from ctystate.txt in the readZips.py functions are codes_)
=> DEV-48 Trim whitespace from city_names

dataactvalidator/validation_handlers/validationManager.py
No longer cast `NoneType` as string
=> HOTFIX: allow empty flex fields in submitted files

dataactbroker/scripts/update_detached_procurement.py
Updating the detached procurement update script to fix additional agency list changes.
- Removed setting of updated_at 
- Added argument to run update on a specific subtier agency (for the case of USAID agency 1152)
- Updated logging
Relates to bugs: [231](https://federal-spending-transparency.atlassian.net/browse/DEV-231), [410](https://federal-spending-transparency.atlassian.net/browse/DEV-410), [423](https://federal-spending-transparency.atlassian.net/browse/DEV-423)
There are only FPDS transactions with the following subtiers: 1152, 5300, 9576
Run locally:
Run the following commands on the test environment. You can view the updated `agency_code_list.csv` in the sf133-dev bucket. 
```
python dataactcore/scripts/initialize.py -c . # updates agency tables base on new agency_codes_list …
```
=> Bugfix updating agengy list changes

dataactbroker/handlers/fileHandler.py, tests/unit/dataactbroker/test_fabs_derivations.py
We don't want to split the zip4 when it's `city-wide`
=> Hotfix only split valid zips

dataactvalidator/config/sqlrules/fabs42_detached_award_financial_assistance_1.sql, tests/unit/dataactvalidator/test_fabs42_detached_award_financial_assistance_1.py
[Feature Link](https://federal-spending-transparency.atlassian.net/browse/DEV-449)
Rule 42.1 where `PrimaryPlaceOfPerformanceForeignLocationDescription` is required for foreign places of performance for record type 2.
=> Update fabs 42.1 rule

dataactbroker/fsrs.py, dataactbroker/scripts/loadFSRS.py
[Bug Link](https://federal-spending-transparency.atlassian.net/browse/DEV-338)
Updated `loadFSRS.py`, adding arguments in order to specify which ids to load that are missing in broker.  Also fixed issue where regular load was skipping initial id. 
We need to load 2 FSRS report ids (492178, 515853) should taking no more than 10 mins based on the bug ticket. 
Command:
```
python dataactbroker/scripts/loadFSRS.py -g -i 492178 515853
```
Average time to load per id is 3 mins.
=> DEV-338 Update fsrs loader to load missing submissions

dataactvalidator/filestreaming/csvReader.py
Allows the user to use the field `BudgetAuthorityAvailableAmountTotal_CPE` or `TotalBudgetaryResources_CPE` for file A submissions by renaming `TotalBudgetaryResources_CPE` to `BudgetAuthorityAvailableAmountTotal_CPE`. Keeps rules as is. 
[Story Link](https://federal-spending-transparency.atlassian.net/browse/DEV-424)
=> Update DEV 424

dataactcore/scripts/initialize.py
Add a flag to `initialize.py` to set is_cached_file for all FileRequests in the DB to False
=> Un-cache FileRequests during deploy

README.md, dataactcore/scripts/pullFPDSData.py
This PR adds ReadTimeoutError and ConnectionError to the FPDS retries. Currently we were only checking for ConnectionResetError. The error I've been seeing during the nightly job for this is requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), which would not be caught (or retried) and therefore immediately fail in the current version of the script.
=> adding retries in get_data to log statements, expanding exception scope

dataactbroker/README.md, dataactbroker/fileRoutes.py, dataactbroker/handlers/fileHandler.py, tests/integration/fileTests.py
Remove all references to submission_(error/warning)_reports routes
We removed them from everything on the front end so they can get removed here
=> Dev 785 removing submission error warning report paths

dataactbroker/handlers/fabsDerivationsHandler.py, dataactbroker/handlers/fileHandler.py, tests/unit/dataactbroker/test_fabs_derivations.py
Attempting to speed up FABS derivations as much as we can. Turning some of the DB queries into lookups to reduce strain on the DB and to speed up the process as much as possible.
On average sped up the process by 10-15 seconds per 1k rows, which isn't a ton but it's better than nothing.
=> Dev 604 fabs derivation speedup

dataactvalidator/config/sqlrules/a33_appropriations_1.sql, dataactvalidator/config/sqlrules/a33_appropriations_2.sql, tests/unit/dataactvalidator/test_a33_appropriations_1.py, tests/unit/dataactvalidator/test_a33_appropriations_2.py
[Story Link](https://federal-spending-transparency.atlassian.net/browse/DEV-357)
- Joins to the `tas_lookup table` should happen  on `account_num` field
- Add a check to make sure File A submission with financial indicator 'F' (financial accounts) are ignored
- Updated tests to include these changes
=> Updating A33 based on DEV-357 bug

dataactvalidator/config/sqlrules/c9_award_financial.sql, tests/unit/dataactvalidator/test_c9_award_financial.py
Adjusting rule C9 to account for assistance type and changing which lines from D2 are ignored based on assistance type and amount
- Updated SQL rule
=> Dev 578 adjust c9

dataactbroker/handlers/submission_handler.py, dataactcore/interfaces/function_bag.py, dataactcore/models/lookups.py, dataactcore/scripts/setupJobTrackerDB.py, tests/integration/fileTests.py
Removing `db_transfer` and `external_validation` from broker.
- Removed from job types lookup
- Added functionality to `initialize.py --db` to remove job types and related jobs and job dependencies
- Removed `external_validation` job creation from submission process 
[Story Link](https://federal-spending-transparency.atlassian.net/browse/DEV-249)
=> Update dev 249 job type

dataactcore/migrations/env.py, requirements.txt
[Story Link](https://federal-spending-transparency.atlassian.net/browse/DEV-244)
- Alembic version [9.2.0](http://alembic.zzzcomputing.com/en/latest/changelog.html#change-0.9.2) fixes renaming of long index names in Postgres [Details on bugfix](https://bitbucket.org/zzzeek/alembic/issues/421)
- Add functionality to skip dropping indexes  `ix_detached_award_procurement_updated_at` and `ix_published_award_financial_assistance_created_at` since columns are created by timestamp mixin
=> Updating alembic functionality to clean up automigrations

dataactcore/local_secrets_example.yml, dataactvalidator/scripts/load_cfda.py
[Story Link](https://federal-spending-transparency.atlassian.net/browse/DEV-823)
- `load_cfda` now downloads from GSA's S3 bucket
- Note: GSA's bucket is not publicly accessible so we have to guess the filename. To get by, we first check to see if the weekly file has been uploaded and if that's not found, it looks for the past four weeks.
=> CFDA Loader Update from GSA S3 Bucket

dataactvalidator/config/sqlrules/fabs15_detached_award_financial_assistance_1.sql, dataactvalidator/config/sqlrules/sqlRules.csv, tests/unit/dataactvalidator/test_fabs15_detached_award_financial_assistance_1.py
FABS15.1 is updated to prevent legitimate foreign aggregate records from being validated. Adding a check for record type 2 and 3  and updating rule text given by Schema.
[Story Link](https://federal-spending-transparency.atlassian.net/browse/DEV-886)
- Updated SQL rule
=> Updating FABS15.1 to include record type 2 and 3

dataactbroker/README.md, dataactbroker/app.py, dataactbroker/handlers/accountHandler.py, dataactbroker/handlers/account_handler.py, dataactbroker/loginRoutes.py, dataactbroker/userRoutes.py, dataactcore/models/lookups.py, tests/unit/dataactbroker/test_account_handler.py, tests/unit/dataactbroker/test_domainRoutes.py
Updated `perms_to_affiliations` to accept service level accounts (`A`) and give them DABS `w` permissions and the new FABS `e` permissions (which are currently unused).
[DEV-1067](https://federal-spending-transparency.atlassian.net/browse/DEV-1067)
**Technical Release Notes:**
Row added to the user permissions table (`PermissionType`): `editfabs`
=> DEV-1067: DABS service account permissions

dataactbroker/README.md, dataactbroker/app.py, dataactbroker/file_routes.py, dataactbroker/handlers/account_handler.py, dataactbroker/handlers/fileHandler.py, dataactbroker/permissions.py, dataactcore/models/lookups.py, tests/unit/dataactbroker/test_file_routes.py, tests/unit/dataactbroker/test_permissions.py
Updated all FABS permission checks to also accept `editfabs` permissions, excluding publishing. Updated the permissions checks so when we check for DABS (`reader`<`writer`<`submitter`) permissions we ignore FABS (`reader`<`editfabs`<`fabs`).
[DEV-1068](https://federal-spending-transparency.atlassian.net/browse/DEV-1068)
=> DEV-1068: FABS service account permissions

dataactbroker/file_routes.py, dataactbroker/handlers/fileHandler.py, dataactbroker/permissions.py, tests/unit/dataactbroker/test_permissions.py
Update current_user_can agency codes to default to `None`.
=> Hotfix: current_user_can agency defaults

dataactcore/scripts/loadDUNS.py, dataactcore/scripts/update_fabs_parent_duns.py, dataactcore/utils/parentDuns.py
Includes script to backfill the ultimate parent name/duns for FABS data using the historic parent duns table. 
**Technical Release Notes:**
* Includes function to get the name of a DUNS directly via the SAM service
* Adding the latest monthly file to represent the DUNS data from the latest year
* Includes two SQL statements, one to update the FABS where the action date + DUNS match the historical parent DUNS table, the other to use the earliest action date + DUNS when there isn't a match
[DEV-1158](https://federal-spending-transparency.atlassian.net/browse/DEV-1158)
**The following are ALL required for the PR to be merged:**
- Unit & integration tests updated with relevant test cases (N/A)
- Frontend impact assessment completed (N/A)
=> DEV-1158: Update FABS parent DUNS

dataactvalidator/scripts/load_program_activity.py, tests/unit/dataactvalidator/test_load_program_activity.py
headers have changed to ```
PA_CODE | FYQ | OMB_BUREAU_TITLE_OPTNL | OMB_ACCOUNT_TITLE_OPTNL | AGENCY_CODE | ALLOCATION_ID | ACCOUNT_CODE | PA_TITLE
-- | -- | -- | -- | -- | -- | -- | --
```
And there was a bug in comparing naive and aware times.
=> Program activity fixes to accommodate for new headers and date problem

dataactbroker/file_routes.py, dataactbroker/handlers/fileHandler.py, dataactbroker/permissions.py, tests/integration/detachedUploadTests.py, tests/integration/fileTests.py
Updated the permissions check for the `upload_detached_file` to function similarly to the rest of the checks.
Removed the non-functioning `current_user_can` check and the check within the `upload_fabs_file` function. Added a wrapper to check for permissions based on the request's `SubTierAgency`.
[DEV-1191](https://federal-spending-transparency.atlassian.net/browse/DEV-1191)
**The following are ALL required for the PR to be merged:**
=> DEV-1191: Fix upload_detached_file permissions check

dataactbroker/README.md, dataactbroker/file_routes.py, tests/integration/fileTests.py
Update `check_generation_status` and `check_detached_generation_status` from POST requests to GET.
Change the router for `check_generation_status` and `check_detached_generation_status` from POST to GET. Update README and tests.
[DEV-1208](https://federal-spending-transparency.atlassian.net/browse/DEV-1208)
=> DEV-1208: Switch check_generation_status and check_detached_generation_status to GET

dataactbroker/handlers/fileHandler.py, tests/integration/fileTests.py, tests/unit/dataactbroker/test_file_handler.py
Blocking D file generation until every step before it is complete.
Blocks D1/D2 file generation until all A,B,C jobs are complete with 0 errors
[DEV-1205](https://federal-spending-transparency.atlassian.net/browse/DEV-1205)
=> DEV-1205: Block D file generation

dataactvalidator/config/sqlrules/b9_award_financial.sql, dataactvalidator/config/sqlrules/b9_object_class_program_activity.sql, tests/unit/dataactvalidator/test_b9_award_financial.py, tests/unit/dataactvalidator/test_b9_object_class_program_activity.py
Fixing B9 error. Speeding up B9
B9 was checking for the format `FY####Q#` when the actual program activity column contained `FY##Q#`, fixing this in the rule. Also including a speedup to drop the amount of time B9 takes
[DEV-1301](https://federal-spending-transparency.atlassian.net/browse/DEV-1301)
[DEV-1300](https://federal-spending-transparency.atlassian.net/browse/DEV-1300) (this one was looped in because it made sense to fit it in here)
=> Hotfix: DEV-1301 b9 fyq fix

tests/unit/dataactbroker/test_file_handler.py, tests/unit/dataactbroker/test_file_routes.py, tests/unit/dataactbroker/test_submission_handler.py, tests/unit/dataactcore/factories/job.py, tests/unit/dataactcore/test_function_bag.py, tests/unit/dataactvalidator/validation_handlers/test_file_generation_handler.py, tests/unit/dataactvalidator/validation_handlers/test_file_generation_manager.py, tests/unit/dataactvalidator/validation_handlers/test_validator.py
Cleaned up JobFactory for easier/cleaner test writing
Removed the requirement to query JobStatus, JobType, and FileType every time a JobFactory is created for testing. Simply need to pass the relevant ID from the lookup instead. Bonus: Did the same for CertifiedFilesHistoryFactory and SubmissionNarrativeFactory.
[DEV-1286](https://federal-spending-transparency.atlassian.net/browse/DEV-1286)
=> DEV-1286: clean up JobFactory

dataactbroker/file_routes.py, tests/integration/baseTestAPI.py, tests/integration/detachedUploadTests.py
Cleaning up upload_detached_file route params and fixing a permissions check bug.
Dates, cgac/frec codes, and quarter checks in upload_detached_file are useless because we don't do anything with any of them. Removed them from tests. Fixing a bug where a non-admin user would never be able to upload a detached file (typo)
[DEV-1280](https://federal-spending-transparency.atlassian.net/browse/DEV-1280)
=> DEV-1280: Remove unnecessary params in upload_detached_file

dataactbroker/handlers/fileHandler.py
**High Level Description**
Fixing local upload
**Technical Description**
Timestamping the local file was lost during the modifications for API upload, so we need to add it back in in the build_file_map function, where previously it was carried out by the upload_local_file route. Makes use of the S3Handler.get_timestamped_filename function.
[DEV-1071](https://federal-spending-transparency.atlassian.net/browse/DEV-1071)
- [NA] Unit & integration tests updated with relevant test cases
- [NA] Frontend impact assessment completed
=> fixing local upload timestamping

APISubmissionGuide.md, dataactbroker/README.md, dataactbroker/file_routes.py, dataactbroker/handlers/fileHandler.py, tests/integration/fileTests.py
Renaming `submit_files` to `upload_dabs_files` for better clarity.
Renaming `submit_files` to `upload_dabs_files` so API users can understand what the route does better.
[DEV-1328](https://federal-spending-transparency.atlassian.net/browse/DEV-1328)
=> DEV-1328: rename submit files route

APISubmissionGuide.md, dataactbroker/README.md, dataactbroker/file_routes.py, tests/integration/detachedUploadTests.py
Renaming `upload_detached_file` to `upload_fabs_files` for better clarity.
Renaming `upload_detached_file` to `upload_fabs_files` so API users can understand what the route does better.
[DEV-1329](https://federal-spending-transparency.atlassian.net/browse/DEV-1329)
=> DEV-1329: rename upload detached file route

dataactbroker/README.md, dataactbroker/file_routes.py, dataactbroker/handlers/fileHandler.py, tests/integration/fileTests.py, tests/integration/integration_test_helper.py, tests/integration/list_submission_tests.py, tests/unit/dataactbroker/test_file_routes.py
Allow users to filter by submission ID when using list_submissions
Add a filter object for filtering list_submissions. Currently only contains submission_id but can be expanded to more. Update list_submissions to a POST for cleaner/easier sending of the filters object.
[DEV-1357](https://federal-spending-transparency.atlassian.net/browse/DEV-1357)
=> DEV-1357: submission dashboard submission_id filter

dataactbroker/README.md, dataactbroker/handlers/fileHandler.py, tests/integration/integration_test_helper.py, tests/integration/list_submission_tests.py
Adding a last modified date filter to `list_submissions` endpoint
Adding ability to filter by a last modified date range. **looking for advice** would this be better as a `last_modified_range` array with 2 elements? Opinions much appreciated.
[DEV-1359](https://federal-spending-transparency.atlassian.net/browse/DEV-1359)
=> DEV-1359: submission dashboard last modified date filter

dataactbroker/handlers/fileHandler.py, dataactvalidator/validation_handlers/file_generation_handler.py, dataactvalidator/validation_handlers/file_generation_manager.py
D file generations are stuck for users who had to revalidate their submissions.
`restart_validation()` updated all jobs to the file status of "waiting", which is not a status that D file generation should ever be in. This caused all D file generations affected by the revalidation to never generate. Also allow for uncaching of currently cached files based on job status and other factors.
[DEV-1406](https://federal-spending-transparency.atlassian.net/browse/DEV-1406)
=> Hotfix: D generation job marked as "waiting"

dataactcore/utils/duns.py
Preventing deactivation records to overwrite populated DUNS records with blank values.
* Any blank values will not be updated in the DUNS table.
* Blank Business Categories (incoming as `NaN`) would simply be an empty list.
N/A
=> Fix: DUNS Script Deactivations

dataactvalidator/config/sqlrules/b9_award_financial.sql, dataactvalidator/config/sqlrules/b9_object_class_program_activity.sql, tests/unit/dataactvalidator/test_b9_award_financial.py, tests/unit/dataactvalidator/test_b9_object_class_program_activity.py
Updating rule B9 so it doesn't activate for FY17Q2/3
Removing limitation that only recertifications of FY17Q2/3 ignore B9. All submissions in that FY/Q will now ignore the rule
[DEV-1422](https://federal-spending-transparency.atlassian.net/browse/DEV-1422)
- N/A Frontend impact assessment completed
=> DEV-1422: B9 ignore FY17Q2/3

dataactvalidator/config/sqlrules/fabs23_detached_award_financial_assistance_1.sql, dataactvalidator/config/sqlrules/fabs23_detached_award_financial_assistance_2.sql, dataactvalidator/config/sqlrules/sqlRules.csv, tests/unit/dataactvalidator/test_fabs23_detached_award_financial_assistance_1.py, tests/unit/dataactvalidator/test_fabs23_detached_award_financial_assistance_2.py
Update FABS23.1 to allow blanks without failing. Add FABS23.2 to make sure AwardingSubTierCode and AwardingOfficeCode map to the same top tier agency code.
See above
[DEV-1440](https://federal-spending-transparency.atlassian.net/browse/DEV-1440)
=> DEV-1440: FABS23 awarding office and sub tier validations

dataactcore/scripts/pullFPDSData.py
When our count of records does not match the count we retrieved at the beginning of a pull, we exit gracefully. This feature has a slight bug in the log.
Because `entries_processed` is an integer, we should never attempt to get the length of it. Just use the variable itself.
N/A
=> Fix: FPDS loader count mismatch fix

dataactbroker/handlers/fileHandler.py, tests/integration/detachedUploadTests.py, tests/integration/fileTests.py
Limits files to CSV and TXT for uploads
Headers for files are automatically set by file type so it can be transferred, use those headers to make sure only the file types we want go through.
[DEV-1327](https://federal-spending-transparency.atlassian.net/browse/DEV-1327)
=> DEV-1327: limit uploads to CSV and TXT files

dataactbroker/handlers/aws/session.py, dataactcore/config_example.yml
At some point several years ago, the Broker session timeout was changed to 7 days. We want it to be 30 minutes.
Replaced the session timeout with a configuration variable that we can change for environments without a deploy. Also removed the loop that could allow a user to click more even when they should've been logged off.
[DEV-1609](https://federal-spending-transparency.atlassian.net/browse/DEV-1609)
=> DEV-1609: Update session timeout

dataactcore/utils/jsonResponse.py
Always show the error message returned, even in production
Update the JSONResponse class to always return the error message provided, even in production, so it can be useful.
[DEV-1639](https://federal-spending-transparency.atlassian.net/browse/DEV-1639)
=> DEV-1639: Always return error message in JSONResponse

dataactvalidator/scripts/loadTas.py
A change was pushed to production that breaks the TAS nightly loader. This fixes it.
The `sess` variable was moved outside the `load_tas` function, but this change did not persist for the other parts of the code that call `load_tas`. Move `sess` back inside of `load_tas`.
N/A
=> Hotfix TAS loader

dataactcore/scripts/populate_historical_unique_award_keys.py, dataactvalidator/validation_handlers/validator.py
Fixing the script and an error the updates for it created and splitting it up so it does smaller sections of the data at a time.
Actually committing in the script and updating the validator so it doesn't throw a key error with the new key. Splitting the updates in the script into one year at a time so there is less data being processed at once and the DB doesn't stall
[DEV-1679](https://federal-spending-transparency.atlassian.net/browse/DEV-1679)
=> DEV-1679: split unique key population by year

dataactcore/scripts/populate_historical_unique_award_keys.py
The DetachedAwardFinancialAssistance table has bad `action_date`s, so we cannot use `cast_as_date` function. There's no other useful way to separate the table, and it's smaller than the others, so we will just update the whole table at once.
Added parameters to the script to allow for starting at different points (to skip the FPDS records that have already run in Dev). Don't separate the DetachedAwardFinancialAssistance table by `action_date`.
[DEV-1679](https://federal-spending-transparency.atlassian.net/browse/DEV-1679)
=> DEV-1679: Fix unique_award_key script for DetachedAwardFinancialAssistance records

dataactbroker/handlers/fileHandler.py
Fixing upload issues Windows users are having
Windows assumes a csv file is an excel for some reason, need to go by extension.
[DEV-1327](https://federal-spending-transparency.atlassian.net/browse/DEV-1327)
=> Hotfix: DEV-1327: CSV/TXT file upload

dataactcore/scripts/load_federal_hierarchy.py
We replace these `agency_code`s in the SubTier table but did not manually make the change when pulling from the Federal Hierarchy API. This corrects that.
Script update.
[DEV-1754](https://federal-spending-transparency.atlassian.net/browse/DEV-1754)
=> DEV-1754: Replace Navy, Army, and Air Force agency codes with DOD

dataactbroker/README.md, dataactbroker/handlers/generation_handler.py, dataactbroker/routes/generation_routes.py, tests/integration/generation_tests.py
Allow detached A file generation (actual functionality not working, endpoints updated).
Update endpoints to allow detached A files to be generated, update tests and documentation. Return a temporary "in development" message in case this somehow goes out without the generation and someone tries to use it
[DEV-1809](https://federal-spending-transparency.atlassian.net/browse/DEV-1809)
=> DEV-1809: Allow A files in detached generation endpoints

dataactcore/interfaces/function_bag.py
Retrieving the FABS metadata was taking up all the API memory, because we were pulling in all the records just to get the FABS record count. We just want to get the `count()`.
Replace `len(rows.all())` with `rows.count()` in the `get_fabs_meta` function.
[DEV-1866](https://federal-spending-transparency.atlassian.net/browse/DEV-1866)
=> Hotfix: Use counts instead of counting the length of the array for get_fabs_meta

dataactcore/aws/sqsHandler.py, dataactvalidator/app.py
Handle the MockSQS messages the same as real SQS messages.
MockSQS changed the contents of the initial message, but never changed it back before sending it to the Validator. This caused the local testing to have different results than remote.
[DEV-1492](https://federal-spending-transparency.atlassian.net/browse/DEV-1492)
=> DEV-1492: Fix Mock SQS message handling for file generations

dataactvalidator/app.py, dataactvalidator/validation_handlers/file_generation_manager.py
Handle A file generation agency codes correctly. Fix generation job handling for non-D files.
Pass `agency_code` to A file generations because they are outside of a submission and not currently using the `FileGeneration` object. Also, make sure to mark A, E, and F file generations as running and then completed. 
[DEV-1492](https://federal-spending-transparency.atlassian.net/browse/DEV-1492)
=> DEV-1492: Fix file A, E, and F file generation bugs created by caching overhaul

dataactcore/scripts/load_federal_hierarchy.py
Update the exit codes to include a `2` for API-specific issues.
Update the exit codes from `3` to `2` where we run into issues with missing responses from the API. Update logging.
N/A
=> OPS: Add exit code 2 to the Fed Hierarchy script

dataactcore/scripts/load_historical_certified_dabs.py
Add delimiter check to the historical certified DABS loader.
=> Hotfix: Update historical certified DABS script

dataactbroker/README.md, dataactbroker/handlers/fileHandler.py, dataactbroker/routes/file_routes.py, dataactcore/aws/s3Handler.py, dataactcore/config.py, dataactcore/config_example.yml
Remove the route we no longer use
We removed all usage of get_protected_files on the frontend. Removing it from the backend
[DEV-2016](https://federal-spending-transparency.atlassian.net/browse/DEV-2016)
=> DEV-2016: Remove get_protected_files route

dataactbroker/handlers/fileHandler.py, dataactcore/config_example.yml, dataactvalidator/validation_handlers/file_generation_manager.py
Adding the ability to know if a D file generation is generated based on awarding or funding agency.
Update the config variable for D file generations to allow for a string to be added. Include a step in the generation to add the agency type to the filename.
[DEV-2017](https://federal-spending-transparency.atlassian.net/browse/DEV-2017)
- ~Merged _after_ [Config #307](https://github.com/fedspendingtransparency/data-act-broker-config/pull/307)~
=> DEV-2017: Add agency_type to generated D filenames

dataactvalidator/validation_handlers/validationManager.py, tests/unit/dataactvalidator/validation_handlers/test_validationManager.py
The research in [DEV-2013](https://federal-spending-transparency.atlassian.net/browse/DEV-2013) revealed a bug: putting a `job_id` in the Validator for a deleted Job will essentially "corrupt" the Validator instance because we attempt to write a file-level error. We should not attempt to write a file-level error without a valid Job.
Attempting to write a file-level error with an invalid `job_id` creates an invalid transaction in the database session, because the `job_id` field in the File table is a primary key to a Job object. Without a valid Job, we should not attempt to create the File object.
[DEV-2024](https://federal-spending-transparency.atlassian.net/browse/DEV-2024)
The following are ALL required for the …
=> DEV-2024: Do not attempt to write a file-level error when a Job does not exist

dataactvalidator/app.py, dataactvalidator/validation_handlers/file_generation_manager.py, dataactvalidator/validation_handlers/validationManager.py
Currently, when a process on the Validator runs into an Exception that we have not accounted for explicitly, the Validator instance swallows the error without failing (but still sends the message to the Dead Letter Queue). We want the Validator process itself to fail.
Remove the `try`/`except` code for Exceptions that we do not plan for. This will ensure that when an unhandled Exception is raised, it continues until the Validator process is killed. Supervisord should already be configured to spin up a new Validator instance to replace the old one.
[DEV-2043](https://federal-spending-transparency.atlassian.net/browse/DEV-2043)
- Merged concurrently with …
=> DEV-2043: Fully raise Validator exceptions

dataactbroker/handlers/fileHandler.py
When a cross-file job fails, it shouldn't break the submission.
check_status was throwing an error if cross-file was in the "failed" status. Removed that error and made sure the same issue couldn't happen again with an upload file somehow either.
[DEV-2083](https://federal-spending-transparency.atlassian.net/browse/DEV-2083)
- Note: There is another ticket for a frontend fix to actually display the error on the frontend, this is just to stop the endpoint from throwing errors.
=> DEV-2083: Check status cross-file

dataactbroker/handlers/submission_handler.py, tests/unit/dataactbroker/test_submission_handler.py
Run revalidation threshold check on backend as well as frontend.
If we ever allow users to certify using the API, we need to make sure the revalidation threshold check is being run there too.
[DEV-1382](https://federal-spending-transparency.atlassian.net/browse/DEV-1382)
=> DEV-1382 revalidation threshold on backend

dataactvalidator/config/sqlrules/b9_award_financial.sql, dataactvalidator/config/sqlrules/b9_object_class_program_activity.sql, tests/unit/dataactvalidator/test_b9_award_financial.py
Program Activity Code in Rule B9 should be case-insensitive.
(see high level)
[DEV-2180](https://federal-spending-transparency.atlassian.net/browse/DEV-2180)
=> DEV-2180: B9 program activity code is case-insensitive

dataactbroker/README.md, dataactbroker/handlers/account_handler.py, dataactbroker/routes/user_routes.py, tests/integration/userTests.py
Errors were being thrown when trying to email from a FREC submission.
There was a problem with the way we were gathering the agency name for the email that caused an error when emails were being sent from FREC submissions. Updated the function to allow only users with access to a submission to send from that submission. Also updated the function in general to be cleaner and better.
[DEV-2234](https://federal-spending-transparency.atlassian.net/browse/DEV-2234)
=> DEV-2234: send email frec submission

.travis.yml
Change the travis and code climate configuration to report code coverage stats to code climate for this repo
- Use the recommended Go executable script `cc-test-reporter`
- Configure an env var in the travis build to contain the test reporter ID from code climate
- `cc-test-reporter` requires env var `CC_TEST_REPORTER_ID` with the value from https://codeclimate.com/repos/5723cb9f3efe1c693e002919/settings/test_reporter
- Have it pick up the generated `coverage.xml` file and report its stats to code climate
- Needs to be moved to the root dir before reporting
N/A
- N/A ~Frontend impact assessment completed~
=> Report unit test code coverage to code climate

dataactcore/scripts/raw_sql/backfill_funding_agency_data_q12019.sql
Creating SQL for backfilling funding agency data based on office code
Adding new SQL to update funding sub tier name/code and funding top tier name/code based on office codes starting 10/1/18. The choice was made to make a new script rather than update the original because the original is still needed but some of the offices were filled in already in the first run of the scripts so we would be missing some of the filling that needs to happen if we just used the existing ones.
[DEV-2308](https://federal-spending-transparency.atlassian.net/browse/DEV-2308)
=> DEV-2308: Office backfill updates

dataactcore/scripts/load_federal_hierarchy.py
Federal Hierarchy source renamed the office type `grant` to `financial assistance` unannounced. This is a bandaid fix and a more indepth PR to update the office model should be made soon.
(n/a)
[DEV-2485](https://federal-spending-transparency.atlassian.net/browse/DEV-2485)
=> Hotfix: Federal Hierarchy Office Type Renaming

dataactcore/scripts/load_federal_hierarchy.py
Federal Hierarchy source renamed the office type `grant` to `financial assistance` unannounced. This is a bandaid fix and a more indepth PR to update the office model should be made soon.
(n/a)
[DEV-2485](https://federal-spending-transparency.atlassian.net/browse/DEV-2485)
=> Hotfix: Federal Hierarchy Office Type Renaming - Production

dataactvalidator/config/sqlrules/c11_cross_file.sql
Speeding up C11 SQL
Using a UNION instead of an OR on 2 EXISTS statements
[DEV-2513](https://federal-spending-transparency.atlassian.net/browse/DEV-2513)
=> Speeding up c11 SQL

setup.cfg
Current coverage is factoring in unit test code too. We should only measure coverage of code to be used in or supporting production.
* Leverage the [pytest coverage plugins pickup of `setup.cfg`](https://pytest-cov.readthedocs.io/en/latest/config.html)
* And put the [`omit` config section under `[coverage:run]`](https://coverage.readthedocs.io/en/latest/config.html#configuration-reference) in there to indicate [to exclude](https://coverage.readthedocs.io/en/latest/source.html#source) `tests/*` from coverage
N/A
- `N/A` ~Merged concurrently with Frontend~
- `N/A` ~Unit & integration tests updated with relevant test cases~
- `N/A` ~Frontend impact assessment …
=> Excluding the tests/ directory from test coverage

legacy_requirements.txt, server_requirements.txt
During the deploy process (see https://github.com/fedspendingtransparency/data-act-build-tools/pull/198) we use Python 2 to support an old version of supervisor. This upgrades that by moving it into the reqs file used w/Python 3, `server_requirements.txt`.
The conditional check will happen with the next deployment. Supervisord 4.0.2 is currently running in sandbox.
=> add supervisor to server reqs, remove legacy file

dataactbroker/scripts/load_fsrs.py, dataactcore/scripts/populate_subaward_table.py, dataactcore/scripts/raw_sql/link_broken_subaward_contracts.sql, dataactcore/scripts/raw_sql/link_broken_subaward_grants.sql, dataactcore/scripts/raw_sql/populate_subaward_table_contracts.sql, dataactcore/scripts/raw_sql/populate_subaward_table_grants.sql, tests/unit/dataactcore/test_populate_subaward_table.py
With the Subaward table included in the FSRS, it was discovered that performance lacked for the main environments. This should resolve it.
* Updated fix_broken_links functionality to only update based on new awards from the last subaward load.
* Updated SQL performance of populate_subaward_table functionality.
* Updated FSRS loader subaward logic to populate only with new FSRS data and cleaned up logs. 
[DEV-2837](https://federal-spending-transparency.atlassian.net/browse/DEV-2837)
=> DEV-2837: Hotfix FSRS loader Performance

dataactvalidator/config/sqlrules/fabs21_detached_award_financial_assistance_1.sql, dataactvalidator/config/sqlrules/fabs21_detached_award_financial_assistance_2.sql, dataactvalidator/config/sqlrules/fabs23_detached_award_financial_assistance_1.sql, dataactvalidator/config/sqlrules/fabs23_detached_award_financial_assistance_2.sql, tests/unit/dataactvalidator/test_fabs21_detached_award_financial_assistance_1.py, tests/unit/dataactvalidator/test_fabs21_detached_award_financial_assistance_2.py, tests/unit/dataactvalidator/test_fabs23_detached_award_financial_assistance_1.py, tests/unit/dataactvalidator/test_fabs23_detached_award_financial_assistance_2.py
Subtier codes can have letters now, they should be case insensitive
Updating FABS 21 and FABS 23 rules to ignore case (all others don't use sub tier codes or are already case insensitive)
[DEV-2685](https://federal-spending-transparency.atlassian.net/browse/DEV-2685)
=> DEV-2685: case insensitive subtier fabs

dataactvalidator/config/sqlrules/b20_object_class_program_activity.sql, tests/unit/dataactvalidator/test_b20_object_class_program_activity.py
Fixing an edge case of B20 where we allow any number of zeroes (1-4) in the object class if the pac and tas are the same
Fixing B20 rule to not AND on the same value
[DEV-2890](https://federal-spending-transparency.atlassian.net/browse/DEV-2890)
=> DEV-2890: B20 logic error

dataactbroker/README.md, dataactbroker/handlers/fileHandler.py, tests/integration/integration_test_helper.py, tests/integration/list_submission_tests.py
Include the minimum last modified date in the `list_submissions` endpoint
Filters should not affect the minimum date, only the type (FABS/DABS) and the publish status (true/false/both) along with user permissions
[DEV-1761](https://federal-spending-transparency.atlassian.net/browse/DEV-1761)
=> DEV-1761: list submissions min last mod

dataactcore/scripts/load_federal_hierarchy.py
The following columns are included in the Federal Hierarchy export:
- `cgaclist_1_cgac`
- `cgaclist_2_cgac`
- `cgaclist_3_cgac`
- `cgaclist_4_cgac`
- `fhorgofficetypelist_3_officetype`
- `fhorgofficetypelist_3_officetypeenddate`
- `fhorgofficetypelist_3_officetypestartdate`
- Also replaced double quotes with single 
[DEV-3221](https://federal-spending-transparency.atlassian.net/browse/DEV-3221)
=> DEV-3221: Add Columns to Federal Hierarchy Export

dataactcore/scripts/load_historical_error_metadata.py
Script to move all historical error metadata into the certified table.
This script copies the certified error/warning metadata and uses the certified files for updated certifications to ensure the metadata we have is from the latest certification of the submission.
[DEV-3197](https://federal-spending-transparency.atlassian.net/browse/DEV-3197)
=> DEV-3197: load historical error metadata

dataactvalidator/filestreaming/csvReader.py, dataactvalidator/validation_handlers/validationManager.py, dataactvalidator/validation_handlers/validator.py
Sometimes with flex fields error metadata gets split up, causing some strange data and bad visuals. This fix prevents this problem going forward.
Always sort flex fields as they are pulled so they're always in order of header name and don't mess up the key, causing split data.
[DEV-3362](https://federal-spending-transparency.atlassian.net/browse/DEV-3362)
=> DEV-3362: prevent split error metadata

dataactcore/scripts/fix_split_error_metadata.py
Creating a script to collapse all the split error metadata
Selecting the first instance of the split errors, setting its occurrences to the sum of all the parts of the split, and deleting the other rows in error_metadata and certified_error_metadata
[DEV-3363](https://federal-spending-transparency.atlassian.net/browse/DEV-3363)
=> DEV-3363: Unsplit historical error metadata

dataactbroker/handlers/fileHandler.py, tests/integration/fileTests.py
Preventing API users to upload dabs files with monthly submissions over several months.
n/a
[DEV-2598](https://federal-spending-transparency.atlassian.net/browse/DEV-2598)
=> DEV-2598: Keeping Monthly Submissions to a Month

dataactcore/scripts/load_duns.py, dataactcore/scripts/load_exec_comp.py
During the DUNS reload over the weekend, the pipeline stopped due to a socket error. This guarantees that we catch all forms of connection errors and reconnect if there is an issue.
The specific error in question is:
`2019-09-13 23:17:45,051 ERROR:paramiko.transport:Socket exception: Connection reset by peer (104)`
This is different from the Socket closed error previously caught by `OSError` so this will account for all the various cases.
N/A
=> Hotfix: DUNS/Exec Comp loaders accounting for Socket Connection drops/closes

dataactvalidator/validation_handlers/validationManager.py, dataactvalidator/validation_handlers/validator.py, tests/unit/dataactvalidator/validation_handlers/test_validationManager.py, tests/unit/dataactvalidator/validation_handlers/test_validator.py
Separating flex fields for single file validations
Flex fields are no longer used in single-file validation error metadata storage. Flex fields also no longer appear in the field names column and have their own values column so they aren't part of the `Values Provided` column
[DEV-3568](https://federal-spending-transparency.atlassian.net/browse/DEV-3568)
=> DEV-3568: Separate flex fields

dataactvalidator/validation_handlers/validator.py, tests/integration/error_warning_file_tests.py
Removing the last instances where we put `None` in the error/warning reports instead of blanks
N/A
[DEV-3704](https://federal-spending-transparency.atlassian.net/browse/DEV-3704)
=> DEV-3704: error report nones

dataactcore/scripts/backfill_displaytas_sf133.py, dataactvalidator/scripts/load_sf133.py
Simple script to backfill the display_tas column in SF-133 table.
- Also fixed the SF-133 loader so that display_tas is more accurate.
- Performance in comment
N/A
=> Backfill display_tas sf133 script

dataactbroker/handlers/agency_handler.py, tests/unit/dataactbroker/test_domain_routes.py
Making sure agencies aren't duplicated in the agency list
Preventing duplication of agencies that the user has more than one permission for in the database (DABS and FABS) when calling `list_agencies`
[DEV-3804](https://federal-spending-transparency.atlassian.net/browse/DEV-3804)
=> DEV-3804: Prevent duplicate agencies listing

dataactcore/scripts/backfill_ppop_scope_fabs.py
It's been discovered that the backfill ppop scope script has different capitalizations from the original ticket/derivation. This resolves that. 
N/A
N/A
=> Updating ppop scope backfill capitalization

dataactbroker/config/supervisord.conf, dataactvalidator/config/supervisord.conf
Reduce verbosity of supervisord.log by not duplicating app logs in it.
It turns out that having this set at debug will duplicate any console logging output from the running python processes to the supervisor logs
- see: debug puts process output into the normal log: http://supervisord.org/logging.html#activity-log-levels
- see: about how child process stderr and stdout gets logged when defaulted to AUTO: http://supervisord.org/logging.html#child-process-logs
- see that the defaults when not set puts it in the /tmp dir with 50MB rotated files up to a max of 10 files: http://supervisord.org/configuration.html
[OPS-1036](https://federal-spending-transparency.atlassian.net/browse/DEV-1036)
The following are ALL …
=> OPS-1036 remove debug log level for supervisor

dataactvalidator/config/sqlrules/b14_object_class_program_activity.sql
Fixing miscalculation when generating the difference value for warning B14.
Since the amount is negative, the difference is (total - (-1 * amount)) => total + amount, not total - amount
[DEV-4196](https://federal-spending-transparency.atlassian.net/browse/DEV-4196)
=> DEV-4196 (hotfix): Updating B14 difference column to be the difference and not the double

dataactcore/scripts/load_historical_certified_flex_field.py
Script for backfilling historical certified flex fields
Simply copies over all certified submission's flex fields. If the submission has been updated, reads in the flex fields from the latest certified files since they might have changed during the update.
[DEV-3576](https://federal-spending-transparency.atlassian.net/browse/DEV-3576)
=> DEV-3576: backfill certified flex fields

dataactbroker/handlers/fileHandler.py, tests/integration/fabs_upload_tests.py
It's been discovered that users on the frontend are able to re-upload FABS files post submission. This should resolve that.
N/A
[DEV-4285](https://federal-spending-transparency.atlassian.net/browse/DEV-4285)
=> DEV-4285: Prevent FABS re-upload

dataactvalidator/config/sqlrules/b15_object_class_program_activity.sql
Like B14 (https://github.com/fedspendingtransparency/data-act-broker-backend/pull/1754), B15 has the negative difference applied to it. This PR, like the previous, should resolve it. 
N/A
N/A
=> Warmfix: Fixing B15 Difference Logic

dataactbroker/handlers/dashboard_handler.py
We want the file filter to be based on RuleSql to cover for the one rule label that we use twice
The way we were joining and filtering on file type was allowing for the single instance of 2 rules with the same label to duplicate results in the active dashboard table. Fixing that here.
N/A
=> Fix: Incorrect warning list SQL

dataactvalidator/validation_handlers/validationManager.py, tests/integration/error_warning_file_tests.py
Max length violations are always fatal errors now.
- Removing the differentiation between FABS and DABS when writing length errors
- Removing some now-unnecessary processing of the initial warning dataframe because it will never be populated in the initial validations
[DEV-2618](https://federal-spending-transparency.atlassian.net/browse/DEV-2618)
=> DEV-2618: max length fatal

dataactbroker/helpers/fabs_derivations_helper.py, dataactcore/scripts/backfill_ppop_scope_fabs.py, tests/unit/dataactbroker/test_fabs_derivations.py
* Resolving bug with ppop scope derivation by moving it after most of the derivations.
* Adding case where ppop zip is blank and the code is XX##### or XX####R -> 'City-wide'
* Updating backfill ppop script which should be run again to account for the missed derivations.
[DEV-4456](https://federal-spending-transparency.atlassian.net/browse/DEV-4456)
=> DEV-4456: PPOP Scope Fix

dataactbroker/README.md, dataactbroker/handlers/account_handler.py, tests/unit/dataactbroker/test_user_routes.py
Simply adding the user's email to the `list_submission_users` endpoint. 
N/A
[DEV-4505](https://federal-spending-transparency.atlassian.net/browse/DEV-4505)
=> DEV-4505: Adding email to list_submission_users endpoint

dataactbroker/README.md, dataactbroker/handlers/dashboard_handler.py, dataactbroker/helpers/dashboard_helper.py, dataactbroker/helpers/filters_helper.py, dataactbroker/routes/dashboard_routes.py, tests/integration/dashboard_tests.py, tests/unit/dataactbroker/test_dashboard_handler.py, tests/unit/dataactbroker/test_dashboard_helper.py, tests/unit/dataactbroker/test_filter_helper.py
Slight deviation from `get_impact_counts`, this endpoint returns the counts of errors/warnings ordered by their significance.
* Refactored a bit of the filter logic out to share.
[DEV-4317](https://federal-spending-transparency.atlassian.net/browse/DEV-4317)
=> DEV-4317: get_significance_counts

dataactbroker/handlers/submission_handler.py, tests/unit/dataactbroker/test_submission_handler.py
Adding a flag to the submission_metadata endpoint to indicate whether it's a test submission or not
The test flag checks to see if there are any other DABS submissions with the same start/end periods that have already been certified.
[DEV-4617](https://federal-spending-transparency.atlassian.net/browse/DEV-4617)
=> DEV-4617: submission metadata test flag

dataactbroker/README.md, dataactbroker/handlers/fileHandler.py, tests/unit/dataactbroker/test_file_handler.py
Updating the reporting sort to `reporting_start` and `reporting_end` for list submissions to help sorting the submissions on the historic dabs dashboard.
N/A
N/A
=> Fix: reporting_start, reporting_end to list_submissions sorting

dataactbroker/helpers/fabs_derivations_helper.py, tests/unit/dataactbroker/test_fabs_derivations.py
Updating legal entity congressional derivation to work for record type 1, state-wide ppop codes
Just copy the ppop congressional district to the legal entity congressional district in this situation
[DEV-4445](https://federal-spending-transparency.atlassian.net/browse/DEV-4445)
=> DEV-4445: LE Congressional state-wide derivation

dataactvalidator/config/sqlrules/fabs38_detached_award_financial_assistance_2_2.sql, dataactvalidator/config/sqlrules/fabs38_detached_award_financial_assistance_4_2.sql, tests/unit/dataactvalidator/test_fabs38_detached_award_financial_assistance_2_2.py, tests/unit/dataactvalidator/test_fabs38_detached_award_financial_assistance_4_2.py
Making sure to check for only active published records when getting the office code
Fixing the rule so it only checks active records in our database
N/A
N/A
=> Fix: FABS 38 active records only

dataactcore/scripts/raw_sql/populate_subaward_table_grants.sql, tests/unit/dataactcore/test_populate_subaward_table.py
With the changes to the subgrant loader, it was discovered that it includes all the transactions with the award and not choosing a single transaction to pull the award data from. This remedies that.
N/A
N/A
=> Hotfix: Subgrant Loading Fix

dataactvalidator/validation_handlers/validationManager.py
Actually storing error metadata for formatting errors
Formatting errors were not being stored in the error metadata table, which is bad
N/A
=> Hotfix: formatting error metadata

dataactvalidator/config/sqlrules/c23_award_financial_3.sql, dataactvalidator/config/sqlrules/c23_award_financial_4.sql, tests/unit/dataactvalidator/test_c23_award_financial_3.py, tests/unit/dataactvalidator/test_c23_award_financial_4.py
Updating C23.3 and C23.4 to only sum the relevant rows based on record type
C23.3 (fain) only sums D2 rows with record type 2 or 3
C23.4 (uri) only sums D2 rows with record type 1
[DEV-5095](https://federal-spending-transparency.atlassian.net/browse/DEV-5095)
=> DEV-5095: c23 record type

dataactvalidator/config/sqlrules/c5_award_financial_2.sql, tests/unit/dataactvalidator/test_c5_award_financial_2.py
Updating C5.2 to only trigger when:
* gross_outlay_amount_by_awa_cpe is not null
* any of the optional values is non-zero
N/A
[DEV-5131](https://federal-spending-transparency.atlassian.net/browse/DEV-5131)
=> DEV-5131: Updating C5.2 Triggers

dataactvalidator/config/sqlrules/c12_cross_file.sql, dataactvalidator/config/sqlrules/c9_award_financial.sql, tests/unit/dataactvalidator/test_c12_cross_file.py, tests/unit/dataactvalidator/test_c9_award_financial.py
Updating C9 and C12 to ignore rows with blank TOA when making sure all rows from D1/D2 are in file C
N/A
[DEV-5235](https://federal-spending-transparency.atlassian.net/browse/DEV-5235)
=> DEV-5235: c9 c12 ignore blank toa

dataactbroker/handlers/fileHandler.py, dataactbroker/handlers/submission_handler.py, tests/unit/dataactbroker/test_file_handler.py, tests/unit/dataactbroker/test_submission_handler.py
Setting submissions to `test_submission` using the same logic as setting their `published_submission_ids`
The updates to `test_submission` flag should handle all of these situations, since they're the same situations as filling in `published_submission_ids`
[DEV-5017](https://federal-spending-transparency.atlassian.net/browse/DEV-5017)
=> DEV-5017: certification workflow locks

APISubmissionGuide.md, dataactbroker/README.md, dataactbroker/handlers/fileHandler.py, dataactbroker/handlers/submission_handler.py, dataactbroker/routes/file_routes.py, tests/integration/fileTests.py, tests/unit/dataactbroker/test_submission_handler.py
Updating `check_year_quarter` to `check_year_period` which will handle both monthly and quarterly submissions.
* Added documentation for endpoint and the APIsubmission guide.
* `check_year_period` also requires `is_quarter` for the logic.
* Refactored a bunch of the published submission ids logic.
* Added a check for publishing submission ids logic to only apply on first publish.
[DEV-5020](https://federal-spending-transparency.atlassian.net/browse/DEV-5020)
=> DEV-5020: check_year_quarter updates

dataactbroker/README.md, dataactbroker/handlers/fileHandler.py, tests/integration/fileTests.py
Combining periods 1 and 2 when creating monthly submissions
Periods 1 and 2 cannot be selected separately and must always go together. All other monthly submissions must still span exactly 1 month
- This WILL break frontend creation of periods 1/2 until the frontend is updated
[DEV-5395](https://federal-spending-transparency.atlassian.net/browse/DEV-5395)
=> DEV-5395: period 2 submissions

APISubmissionGuide.md, dataactbroker/README.md, dataactbroker/handlers/submission_handler.py, dataactbroker/routes/file_routes.py, tests/integration/fileTests.py
Updating `check_year_period` to `published_submissions` endpoint for ease of use on the front-end.
* Updated certify_dabs endpoint for these situations. Usually, the submission will be a test submission and stop based on that. I've also accounted for the special case if for some reason `test_submission` is not flagged and there are published submissions in the period.
[DEV-5218](https://federal-spending-transparency.atlassian.net/browse/DEV-5218)
=> DEV-5218: Updating check_year_period -> published_submissions

dataactbroker/README.md, dataactbroker/handlers/submission_handler.py, tests/unit/dataactbroker/test_submission_handler.py
Adding `certification_deadline` to the `submission_metadata` endpoint because the frontend needs it
N/A
[DEV-5317](https://federal-spending-transparency.atlassian.net/browse/DEV-5317)
=> DEV-5317: monthly publish certify buttons

dataactbroker/README.md, dataactbroker/handlers/fileHandler.py, dataactbroker/routes/file_routes.py, tests/integration/fileTests.py, tests/unit/dataactbroker/test_file_handler.py
Returning both publish and certify history when requesting history.
- Added `publications` to the history list
- Renamed the endpoint to better reflect what is being requested (new name: `list_history` instead of `list_certifications`)
- Fixed quote types in the test while I was there
[DEV-5314](https://federal-spending-transparency.atlassian.net/browse/DEV-5314)
=> DEV-5314: split submission history

dataactvalidator/config/sqlrules/a14_appropriations.sql, dataactvalidator/config/sqlrules/a15_appropriations.sql, dataactvalidator/config/sqlrules/a22_appropriations.sql, dataactvalidator/config/sqlrules/a23_appropriations.sql, dataactvalidator/config/sqlrules/a34_appropriations.sql, dataactvalidator/config/sqlrules/a6_appropriations.sql, dataactvalidator/config/sqlrules/a7_appropriations.sql, tests/unit/dataactvalidator/test_a14_appropriations.py, tests/unit/dataactvalidator/test_a15_appropriations.py, tests/unit/dataactvalidator/test_a22_appropriations.py, tests/unit/dataactvalidator/test_a23_appropriations.py, tests/unit/dataactvalidator/test_a34_appropriations.py, tests/unit/dataactvalidator/test_a6_appropriations.py, tests/unit/dataactvalidator/test_a7_appropriations.py
Fixing Rules A6, A7, A14, A15, A22, A23, and A34 to account for multiple entries of the same SF133 line due to DEFC
Summing SF133 lines in cases where we aren't separating by DEFC and are only looking at one line
[DEV-5533](https://federal-spending-transparency.atlassian.net/browse/DEV-5533)
=> DEV-5533: sf133 defc line sum validations

dataactbroker/README.md, dataactbroker/handlers/submission_handler.py, tests/unit/dataactbroker/test_submission_handler.py
Remove preventing only certify after certification deadline
It will only ever allow it to get through the call if it's been published already and we don't need a re-publish in this case.
[DEV-5514](https://federal-spending-transparency.atlassian.net/browse/DEV-5514)
=> DEV-5514: Publish certify past deadline

requirements.txt
This PR will revert the recent ddtrace client upgrade as its not compatible with our version of python (3.5)
the package is not compatible with python 3.5 Travis automated build did not catch this because it does not install the requirements.
=> reverting ddtace client upgrade

dataactcore/config_example.yml, dataactcore/local_config_example.yml, dataactvalidator/validation_handlers/validationManager.py
Makes the batch size for validations configurable instead of hard-coded
validator_batch_size in config.yml will be used as the CHUNK_SIZE in the validationManager.py
https://federal-spending-transparency.atlassian.net/browse/DEV-5582
- [N/A] Merged concurrently with frontend
- [N/A] Unit & integration tests updated with relevant test cases
- [N/A] Frontend impact assessment completed
=> [DEV-5582] make batch size configurable

dataactbroker/handlers/fileHandler.py, tests/unit/dataactbroker/test_file_handler.py
Updating S3 directory structure for certified submissions to accommodate periods and quarters. 
Quarters remain the same "QX" and periods now are "PXX"
[DEV-5553](https://federal-spending-transparency.atlassian.net/browse/DEV-5553)
=> Warmfix DEV-5553: Updating Certified S3 Directory Names

dataactvalidator/validation_handlers/validationManager.py
The current way we upload error/warnings files to S3 doesn't use multipart. `upload_file` does.
N/A
N/A
=> [HOTFIX] Uploading the Error/Warning files to S3 Better

dataactcore/utils/report.py, tests/integration/error_warning_file_tests.py, tests/integration/fileTests.py, tests/unit/dataactbroker/test_file_handler.py, tests/unit/dataactbroker/test_submission_handler.py
Since we changed the name of the error/warning reports, the older reports have been inaccessible. This resolves that by associating certain filename formats to different time periods (before/after DAIMS 2.0 was deployed to production)
N/A
[DEV-5824](https://federal-spending-transparency.atlassian.net/browse/DEV-5824)
=> HOTFIX (DEV-5824): Accessing older Error/Warning Reports

dataactbroker/handlers/submission_handler.py, dataactcore/interfaces/function_bag.py, tests/unit/dataactcore/test_function_bag.py
Updating the metadata box above submissions to use the proper modified date instead of only checking the submission's updated_at
Uses the same table as the frontend submission table to get the last_modified date so if a job has changed that didn't cause the submission to change, the most recent modification of any kind will be the one displayed.
[DEV-5955](https://federal-spending-transparency.atlassian.net/browse/DEV-5955)
=> DEV-5955: metadata box last modified

dataactvalidator/config/sqlrules/c23_award_financial_1.sql, dataactvalidator/config/sqlrules/c23_award_financial_2.sql, dataactvalidator/config/sqlrules/c23_award_financial_3.sql, dataactvalidator/config/sqlrules/c23_award_financial_4.sql, tests/unit/dataactvalidator/test_c23_award_financial_1.py, tests/unit/dataactvalidator/test_c23_award_financial_2.py, tests/unit/dataactvalidator/test_c23_award_financial_3.py, tests/unit/dataactvalidator/test_c23_award_financial_4.py
Updating C23 to only trigger when TOA is not null
N/A
[DEV-5954](https://federal-spending-transparency.atlassian.net/browse/DEV-5954)
=> DEV-5954: C23 ignored with NULL TOA

dataactvalidator/validation_handlers/errorInterface.py, dataactvalidator/validation_handlers/validationManager.py, dataactvalidator/validation_handlers/validator.py, tests/integration/error_warning_file_tests.py
It was discovered that non-SQL validation errors weren't being stored in the database properly when running with parallelized loading. This resolves said bug. 
* Reduced wrapper class ErrorInterface to a dictionary with helper functions
* Core issue was multiprocessing's manager proxy list/dict objects not being updated correctly.
=> Fix: Parallelized Non-SQL Validations 

dataactcore/utils/report.py, dataactvalidator/validation_handlers/validationManager.py
Only create cross file error/warning reports that we actually need as opposed to every possible file combination
Updating the cross pairs we use to only the 4 that actually exist as SQL rules
[DEV-6091](https://federal-spending-transparency.atlassian.net/browse/DEV-6091)
=> DEV-6091: Redundant cross file error warning

dataactbroker/handlers/submission_handler.py, doc/api_docs/file/check_current_page.md
Fixing the `check_current_page` endpoint messages to match what our pages actually look like.
N/A
[DEV-6127](https://federal-spending-transparency.atlassian.net/browse/DEV-6127)
=> DEV-6127: check current submission page messages

dataactvalidator/validation_handlers/validationManager.py, tests/integration/data/appropReadError.csv, tests/integration/error_warning_file_tests.py, tests/unit/dataactbroker/test_validation_helper.py
It was discovered that when uploading a file that started off with rows with too many fields, it failed the job. This resolves that by skipping said long rows in the beginning.
N/A
[DEV-6194](https://federal-spending-transparency.atlassian.net/browse/DEV-6194)
=> DEV-6194: Starting with Long Rows Bug

dataactcore/aws/sqsHandler.py, dataactcore/config_example.yml
Botocore uses the legacy SQS endpoint url which is not acceptable on the DTI environment. This config value sets whether to use the new one or legacy.
N/A
[BRUS2DTI-379](https://federal-spending-transparency.atlassian.net/browse/BRUS2DTI-379)
```
from dataactcore.aws.sqsHandler import sqs_queue
queue = sqs_queue()
message_attr = {"test_type": {"DataType": "String", "StringValue": "test"}}
queue.send_message(MessageBody="TEST BODY", MessageAttributes=message_attr)
```
=> DTI Warmfix: SQS Endpoint URL Configuration

dataactcore/aws/sqsHandler.py
Even though it didn't raise this locally, it turns out the call still needs `region_name` despite the endpoint url including it.
N/A
[BRUS2DTI-379](https://federal-spending-transparency.atlassian.net/browse/BRUS2DTI-379)
=> Warmfix: Including region_name in addition to endpoint_url

dataactcore/scripts/backfill_displaytas.py, dataactcore/scripts/backfill_displaytas_sf133.py
Updating an existing `display_tas` backfill script to backfill not only SF133 but also the staging tables for A, B, and C files and the related certified tables.
Also updating the backfill script to more accurately generate the `display_tas`. Basing the updated code on this USAS code to generate the TAS they display https://github.com/fedspendingtransparency/usaspending-api/blob/dev/usaspending_api/references/management/sql/restock_tas.sql
[DEV-6347](https://federal-spending-transparency.atlassian.net/browse/DEV-6347)
=> DEV-6347: backfill display tas

dataactbroker/fsrs.py, dataactbroker/helpers/generic_helper.py, dataactbroker/scripts/load_fsrs.py
The current implementation and use of suds doesn't account for http proxies. This makes the FSRS and DUNS historical loads break on the DTI environment. This PR simply uses the HTTP proxy environment variables if there are any. 
N/A
N/A
=> Hotfix: WSDL SOAP SUDS HTTP Proxies

Dockerfile, dataactcore/scripts/derive_historical_transaction_exec_comp.py, dataactcore/scripts/load_duns.py, dataactcore/scripts/load_exec_comp.py, dataactcore/utils/duns.py
The following are necessary changes to the DUNS/Exec Comp loaders to run on the DTI environment.
* Running the DUNS load on DTI requires extra work to use the HTTP proxies.
* The loader will use the tempdir instead of `file_d_storage_path` to run within docker containers.
N/A
=> Hotfix: DUNS loader updates (http proxy, tempfiles)

dataactcore/utils/duns.py
Turns out using the HTTP_PROXY updates the IP address for outbound SSH connections which need to be whitelisted by SAM. This simply is a band-aid fix that temporarily makes DAOI ignore the proxy for DUNS and respect the proxy for DTI. When the IPs get whitelisted and/or when we migrate to DTI, this line can be reverted along with updating the DTI configs.
- successful run with the config added and set to `true` on DTI sandbox (http://10.117.0.20:8080/job/Broker-DUNS-Load/948/console)
- failure without the config added on DTI qat (http://10.117.0.20:8080/job/Broker-DUNS-Load/949/console)
- successful run with the config added and set to `true` on DTI qat (http://10.117.0.20:8080/job/Broker-DUNS-Load/950/console)
=> Hotfix: SAM "use_proxy" Config

dataactvalidator/config/sqlrules/b20_object_class_program_activity.sql, tests/unit/dataactvalidator/test_b20_object_class_program_activity.py
Adding ignoring specific pairings of PAC and PAN before the year 2021
PAC of `OPTN` and PAN of `FIELD IS OPTIONAL PRIOR TO FY21` (case insensitive) are ignored for B20 prior to FY2021
[DEV-6547](https://federal-spending-transparency.atlassian.net/browse/DEV-6547)
=> DEV-6547: B20 pre 2021 exception

dataactbroker/handlers/submission_handler.py, tests/integration/fileTests.py
Preventing FY22+ quarterly submission publishing
N/A
[DEV-6753](https://federal-spending-transparency.atlassian.net/browse/DEV-6753)
=> DEV-6753: prevent fy22 quarterly publish

dataactbroker/handlers/fileHandler.py, doc/api_docs/file/upload_dabs_files.md, tests/integration/fileTests.py
Ensures that when making a new DABS submission, API users can't send both cgac and frec codes or leave both of them as null.
N/A
[DEV-4518](https://federal-spending-transparency.atlassian.net/browse/DEV-4518)
=> DEV-4518: require cgac or frec new dabs submission

.travis.yml, dataactbroker/app.py, dataactcore/utils/tracing.py, dataactvalidator/app.py, requirements.txt, tests/unit/dataactcore/utils/test_tracing.py
_:warning: Best reviewed with whitespace ignored, due to many indent changes (ctx mgrs, try-finally)_
**High-level Description:**
Upgraded datadog `ddtrace-py` library, refactor to accommodate upgraded, and add more tracing into big steps of the validator that run in worker sub-processes
- This pushes a good deal of the work to enable trace spans to reach datadog from subprocess traces into a new context manager.
- That context manager is used at the file gen or validation job initiation point
- See linked PR in `data-act-broker-config` for enabling tracing: https://github.com/fedspendingtransparency/data-act-broker-config/pull/619
**Requirements for PR merge:**
[OPS-1660](https://federal-spending-transparency.atlassian.net/browse/OPS-1660) …
=> [OPS-1660] ddtrace update and subprocess and sub-step tracing of Validator

dataactcore/scripts/load_duns.py, dataactcore/scripts/load_exec_comp.py
Adding `--force_reload` arguments to the DUNS and Exec Comp loaders which forces a reload of data from a specified date.
N/A
[DEV-6926](https://federal-spending-transparency.atlassian.net/browse/DEV-6926)
=> DEV-6926: DUNS/Exec Comp Forced Reloads

dataactvalidator/scripts/load_sf133.py
Update the GTAS SF133 loader to only store single character DEFCs (by extracting only the last character if more are provided) 
N/A
[DEV-7070](https://federal-spending-transparency.atlassian.net/browse/DEV-7070)
=> DEV-7070: SF133 Loader, Single Character DEFCs

dataactcore/utils/fileA.py, tests/unit/dataactvalidator/validation_handlers/test_file_generation_manager.py
Fixing the file A generation for the combination of: CGAC agency, NULL ATA, 011 AID, TAS that is connected to agency through FRECs associated with that CGAC.
Fixing the formatting of the array so the filter can read it.
[DEV-7164](https://federal-spending-transparency.atlassian.net/browse/DEV-7164)
=> DEV-7164: file a generation frec list

dataactvalidator/config/sqlrules/c20_award_financial.sql, dataactvalidator/config/sqlrules/c21_award_financial.sql, dataactvalidator/config/sqlrules/c26_award_financial.sql, tests/unit/dataactvalidator/test_c20_award_financial.py, tests/unit/dataactvalidator/test_c21_award_financial.py, tests/unit/dataactvalidator/test_c26_award_financial.py
Only display the difference values in rules C20, C21, and C26 for values that are incorrect
The three rules now return one column labeled "difference" with the entire string instead of a separate column for each difference that then was concatenated for the report.
[DEV-7030](https://federal-spending-transparency.atlassian.net/browse/DEV-7030)
=> DEV-7030: only failing differences c20 c21 c26

dataactcore/scripts/pull_fpds_data.py
Updating the FPDS loader such that:
- it'll only request the pages we expect data for
- it'll retry requests if they don't include data for connection issues.
N/A
[DEV-7336](https://federal-spending-transparency.atlassian.net/browse/DEV-7336)
=> Hotfix: FPDS Loader Retrying Empty Responses

dataactcore/scripts/raw_sql/fileF.sql, dataactcore/scripts/raw_sql/link_broken_subaward_contracts.sql, dataactcore/scripts/raw_sql/link_broken_subaward_grants.sql, dataactcore/scripts/raw_sql/populate_subaward_table_contracts.sql, dataactcore/scripts/raw_sql/populate_subaward_table_grants.sql, tests/unit/dataactcore/test_fileF.py
Resolving bug with File F that was excluding subtiers when linking grants.
Ensured the subaward linking logic was consistent among:
* File F SQL
* Populate Subaward SQL
* Fix Broken Subaward Links SQL
Also noting you can't add comments to the SQL, so we need to ensure this logic is documented somewhere and remains consistent.
[DEV-9553](https://federal-spending-transparency.atlassian.net/browse/DEV-9553)
=> DEV-9553: Fix File F Award Linking Logic

Dockerfile
We need to pin the release version of Python in the Dockerfile. Python 3.7.11 had some breaking changes to some of C libraries.
Don't forget to rebuild the container using the docker-broker-backend job for each environment. 
NONE
=> Pin Python release in Dockerfile

dataactcore/scripts/raw_sql/populate_subaward_table_contracts.sql, dataactcore/scripts/raw_sql/populate_subaward_table_grants.sql, tests/unit/dataactcore/test_populate_subaward_table.py
Updating subaward scripts to derive country names based on the new 2 char characters in addition to the currently supported 3 chars.
[Backfill script tested/verified on QAT](http://jenkins-master-8ca0e1e199b2c8fc.elb.us-gov-west-1.amazonaws.com:8080/job/sql-script-ad-hoc/612/console)
```
WITH update_subawards as (
SELECT
subaward.id,
le_country.country_name AS "legal_entity_country_name",
ppop_country.country_name AS "place_of_perform_country_na",
sub_le_country.country_name AS "sub_legal_entity_country_name",
sub_ppop_country.country_name AS "sub_place_of_perform_country_na"
FROM subaward
LEFT OUTER JOIN country_code AS le_country
ON (UPPER(legal_entity_country_code) = UPPER(le_country.country_code)
OR UPPER(legal_entity_country_code) = …
```
=> DEV-7728: Subaward Country Codes

dataactvalidator/config/sqlrules/c27_award_financial.sql, tests/unit/dataactvalidator/test_c27_award_financial.py
Reverts/readds the DEFC 9 exception to C27
N/A
[DEV-7870](https://federal-spending-transparency.atlassian.net/browse/DEV-7870)
=> DEV-7870: Reverting/readding DEFC 9 exception to C27 (hotfix)

dataactvalidator/scripts/read_zips.py
Generating the link to the census file later immediately before it gets used to prevent expired links.
N/A
N/A
=> Zips Hotfix: Generate link to the census file later

dataactbroker/handlers/fileHandler.py, dataactbroker/handlers/submission_handler.py, dataactbroker/permissions.py, dataactbroker/routes/user_routes.py, doc/INSTALL.md, doc/README.md, doc/api_docs/login/login.md, doc/api_docs/user/active_user.md, tests/integration/userTests.py, tests/unit/dataactbroker/test_permissions.py
Replacing `current_user` endpoint with `active_user`. This resolves an issue with remote environments that detected a "SQL injection" whenever the endpoint was hit, causing users to be timed out of the environment for 10 minutes.
N/A
[DEV-8246](https://federal-spending-transparency.atlassian.net/browse/DEV-8246)
=> DEV-8246: Current User -> Active User

dataactbroker/handlers/fileHandler.py
Preventing the creation of quarterly submissions in FY22 or later
Throws an error when the user tries to create a quarterly submission with FY22 or later as opposed to the previous action of automatically setting it to a test submission.
[DEV-8252](https://federal-spending-transparency.atlassian.net/browse/DEV-8252)
=> DEV-8252: prevent fy22 quarterly submissions

dataactvalidator/config/sqlrules/b19_object_class_program_activity.sql, tests/unit/dataactvalidator/test_b19_object_class_program_activity.py
Padding object class codes to always be 4 characters long for B19 validation
N/A
[DEV-9013](https://federal-spending-transparency.atlassian.net/browse/DEV-9013)
=> DEV-9013: B19 boc dupes

dataactvalidator/scripts/read_zips.py
Stop setting the CD for all MT zips to 00
Since MT has been split into 2 CDs we are now just going to use the value given to us by USPS to determine what the CD is.
[DEV-9571](https://federal-spending-transparency.atlassian.net/browse/DEV-9571)
=> DEV-9571: MT CD

requirements.txt
Running flake8 with a completely new build from scratch breaks due to a bizarre dependency chain issue in one of the packages. The fix included is referenced here - https://github.com/python/importlib_metadata/issues/406
N/A
N/A
=> Fix: Running Flake8 with the current build

dataactbroker/helpers/fabs_derivations_helper.py, tests/unit/dataactbroker/test_fabs_derivations.py
Updating the FABS derivations that can to use the new threshold tables
Any congressional district derivations in FABS that only need zip5 now use the threshold version of the zips grouped table
[DEV-9707](https://federal-spending-transparency.atlassian.net/browse/DEV-9707)
=> DEV-9707: fabs threshold table derivations

dataactvalidator/scripts/load_program_activity.py
Turn off auto-null for pandas on PA file read because they sometimes send `N/A` as a valid entry
N/A
[DEV-9874](https://federal-spending-transparency.atlassian.net/browse/DEV-9874)
=> DEV-9874: Stop auto-nulling PA file

dataactvalidator/config/sqlrules/fabs44_3.sql, tests/unit/dataactvalidator/test_fabs44_3.py
Use the canonical state when comparing congressional districts to the states the zips indicate
N/A
[DEV-9825](https://federal-spending-transparency.atlassian.net/browse/DEV-9825)
=> DEV-9825: fabs 44.3 canonical state

dataactbroker/helpers/fabs_derivations_helper.py, tests/unit/dataactbroker/test_fabs_derivations.py
Updating FABS legal entity location derivations to use the canonical state when deriving legal entity state. Also using that canonical state anywhere that it might matter for derivations
N/A
[DEV-9826](https://federal-spending-transparency.atlassian.net/browse/DEV-9826)
=> DEV-9826: fabs derivations canonical state

dataactvalidator/config/sqlrules/fabs47_3.sql, dataactvalidator/config/sqlrules/fabs47_4.sql, tests/unit/dataactvalidator/test_fabs47_3.py, tests/unit/dataactvalidator/test_fabs47_4.py
Allowing "not applicable" to go through on FABS47.3 and FABS47.4
N/A
[DEV-10290](https://federal-spending-transparency.atlassian.net/browse/DEV-10290)
=> DEV-10290: not applicable exception fabs47

requirements.txt
After upgrading to Python3.9, the Delete Submission feature was not functional with an error message of 
```
An error occurred (InvalidRequest) when calling the DeleteObjects operation: Missing required header for this request: Content-MD5 OR x-amz-checksum-*
```
In Python3.9, the hash library for generating MD5s on FIPS systems was updated to not generate hashs for FIPS systems. This MD5 is crucial for interacting with AWS, specifically requiring an MD5 header when deleting objects from S3 buckets. The hash library does include an additional keyword argument (`usedforsecurity`, defaulted to `True`) to bypass the security check that hasn't been updated in the botocore library. The solution involves making a forked version of botocore that …
=> DEV-10449: Delete Objects MD5 Python3.9 Fix

dataactbroker/helpers/validation_helper.py, tests/unit/dataactbroker/test_validation_helper.py
Minor fix for consistently sorting the Flex Fields in the Error and Warning report. This is more for the error_warning_file tests to consistently pass.
N/A
N/A
=> Fix: Sort Flex Fields in E/W Report

dataactbroker/handlers/account_handler.py, dataactbroker/routes/login_routes.py, dataactcore/local_secrets_example.yml, tests/unit/dataactbroker/test_login_routes.py
Adding an endpoint for the API Proxy users to log into the Broker.
* Added additional tests for the CAIA login endpoint alongside the API Proxy endpoint.
* Included an API Proxy Token configuration (subject to change)
[DEV-10749](https://federal-spending-transparency.atlassian.net/browse/DEV-10749)
=> DEV-10749: /v1/proxy_login Endpoint

dataactbroker/handlers/submission_handler.py
Fixes a bug caused by DEV-9898 due to `null`s being included in the DABS file list.
N/A
[DEV-9898](https://federal-spending-transparency.atlassian.net/browse/DEV-9898)
=> DEV-9898 Fix: Null Cross-file Filenames included in `get_submission_files`

dataactbroker/handlers/fileHandler.py, doc/api_docs/domain/list_agencies.md, tests/integration/dashboard_tests.py, tests/unit/dataactbroker/test_submission_handler.py
If the CGAC provided for a new FABS is 999 then always set it to be a test submission
Cleaned up all tests that weren't FPDS-related to not use CGAC 999
[DEV-10863](https://federal-spending-transparency.atlassian.net/browse/DEV-10863)
=> DEV-10863: fabs test agency

dataactvalidator/validation_handlers/validator.py, tests/integration/error_warning_file_tests.py, tests/unit/dataactvalidator/validation_handlers/test_validator.py
Updating the FABS validator to only run non-sensitive rules for a specific agency.
Also sorts the flex values and values provided lists in the error warning report to fix issues with testing.
[DEV-10862](https://federal-spending-transparency.atlassian.net/browse/DEV-10862)
=> DEV-10862: FABS Validator Custom Non-Senstive Rules

dataactcore/scripts/pipeline/pull_fpds_data.py
Adding an error if total records from a feed is more than 400k. Putting Delivery Order up front because it's the most likely to cause size issues so we might as well get it done first and error faster
N/A
[DEV-10987](https://federal-spending-transparency.atlassian.net/browse/DEV-10987)
=> DEV-10987: FPDS record count limit check

dataactbroker/helpers/fabs_derivations_helper.py, doc/fabs_derivations.md, tests/unit/dataactbroker/test_fabs_derivations.py
**High-level description:**
Updates the FABS derivations for offices such that when assigning the office code (if not provided) from the base transaction, it will now only derive that if the base action date is within the office's effective range.
N/A
[DEV-11125](https://federal-spending-transparency.atlassian.net/browse/DEV-11125)
=> DEV-11125: Update FABS Office Derivations for Active Offices

dataactcore/scripts/pipeline/load_duns_exec_comp.py, dataactcore/utils/sam_recipient.py, tests/unit/dataactcore/scripts/test_sam_recipient.py
* Removes TODOs related to unregistered recipients having update date. We've confirmed SAM does not support that.
* Resolved TODO to use the new `get_utc_now()`
N/A
N/A
=> Fix: Resolve Minor TODOs

dataactcore/utils/sam_recipient.py
Bumping max retries from 10 to 15. With 10, it's already waiting 4 minutes and each retry exponentially increases the wait time, so that should bump it up to last least ten minutes.
N/A
N/A
=> Fix: SAM API - Bump to 15 Retries

dataactvalidator/config/sqlrules/a18_cross_file.sql, dataactvalidator/config/sqlrules/a19_cross_file.sql
This PR removes the following columns that are redundant with `display_tas` from group by expressions and cte selects in the sql rules:
- `allocation_transfer_agency`
- `agency_identifier`
- `beginning_period_of_availa`
- `ending_period_of_availabil`
- `availability_type_code`
- `main_account_code`
- `sub_account_code`
The column `display_tas` is generated by concatenating the values of the above listed columns and these columns are always unique together.  One suggestion for followup is whether it would be beneficial to add a unique together constraint for these columns to enforce this behavior.  
[DEV-11432](https://federal-spending-transparency.atlassian.net/browse/DEV-11432)
The following are ALL required for …
=> [DEV-11432] - Removing redundant columns from group by expressions

dataactcore/utils/fileBOC.py, tests/unit/dataactvalidator/validation_handlers/test_file_generation_manager.py
Removing 000 and 999 from GTAS Comparison Report
BOC 000 in file B and 999 in the BOC GTAS data (and their equivalents with more or less numbers) are all invalid but can be used as fillers and don't need to show up in the comparison report
[DEV-11554](https://federal-spending-transparency.atlassian.net/browse/DEV-11554)
=> DEV-11554: boc filter gtas report

dataactcore/utils/fileBOC.py, tests/unit/dataactvalidator/validation_handlers/test_file_generation_manager.py
Filtering out non-file B USSGLs from the GTAS BOC data when making a GTAS Comparison Report
N/A
[DEV-11620](https://federal-spending-transparency.atlassian.net/browse/DEV-11620)
=> DEV-11620: filter non b ussgl gtas comparison

dataactcore/scripts/setup/load_location_data.py, tests/unit/dataactcore/utils/test_tracing.py
This PR re-adds missing legacy city codes that is not present for certain "states".
I tested this locally using a  minio container to replicate the S3 functionality.  
**Note:**
I also fixed an unrelated test that was randomly failing. See [comment](https://github.com/fedspendingtransparency/data-act-broker-backend/pull/2680#discussion_r1884475378).
[DEV-111811](https://federal-spending-transparency.atlassian.net/browse/DEV-11811)
=> [DEV-11811] - Add legacy city codes (PW, FM, MH) to the city code loader

dataactcore/config.py
* The parameter store name for staging starts with `nonprod`, not `prod` as expected.
=> FIx: Parameter Store Name for Staging

dataactcore/broker_logging.py
If `SimpleSpanProcessor` runs into a URL error, it halts the application. `BatchSpanProcessor` runs in the background and doesn't halt the application if it runs into a URL error.
N/A
[DEV-12325](https://federal-spending-transparency.atlassian.net/browse/DEV-12325)
=> DEV-12325: SimpleSpanProcessor -> BatchSpanProcessor Grafana Fix

dataactcore/scripts/pipeline/generate_sam_fabs_export.py, tests/unit/dataactcore/scripts/test_generate_sam_fabs_export.py
Simply updates the script that exports FABS records to SAM to sort by `published_fabs_id` in addition to `updated_at`.
N/A
[DEV-12580](https://federal-spending-transparency.atlassian.net/browse/DEV-12580)
=> Fix: sam subaward nightly dup fix

dataactcore/scripts/pipeline/load_park.py, tests/unit/dataactcore/scripts/test_load_park.py
Simply exports the `park.csv` the same as the original file (without cleaning up the headers).
N/A
[DEV-12660](https://federal-spending-transparency.atlassian.net/browse/DEV-12660)
[DEV-12600]: https://federal-spending-transparency.atlassian.net/browse/DEV-12600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEV-12660]: https://federal-spending-transparency.atlassian.net/browse/DEV-12660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-12660] Raw park.csv export

dataactcore/scripts/setup/load_defc.py, tests/unit/dataactcore/scripts/test_load_defc.py
The GovInfo endpoint we use to pull DEFC metadata has changed the format of its `dateIssued`. This replaces it with `origDateIssued`.
N/A
[DEV-12828](https://federal-spending-transparency.atlassian.net/browse/DEV-12828)
[DEV-12828]: https://federal-spending-transparency.atlassian.net/browse/DEV-12828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEV-12828] DEFC Loader Fix: `dateIssued`
