fedspendingtransparency/data-act-broker-backend

dataactbroker/config/supervisord.conf
dataactbroker/config/uwsgi.ini
dataactvalidator/config/supervisord.conf
dataactvalidator/config/uwsgi.ini

This fixes the location of the code for the new repo structure in the supervisor and uwsgi config files

Pointing to new file paths for supervisor and uwsgi

---

dataactbroker/app.py

Changing to allow all headers.

Hotfix cors headers

---

dataactbroker/config/supervisord.conf
dataactbroker/config/uwsgi.ini
dataactvalidator/config/supervisord.conf
dataactvalidator/config/uwsgi.ini

Hotfix into staging to correct paths to new repo in supervisord.conf and uwsgi.ini

Correcting paths for new repo locations

---

dataactbroker/handlers/accountHandler.py

updating error messages for incorrect password attempts, and case for generic invalid login method.

---

.gitignore
requirements.txt
tests/runTests.py

@bsweger @jworcestBAH @nmonga91

Adding xml output for testing (run with -o "XML")

---

Dockerfile

Feature pr test results

---

dataactbroker/handlers/accountHandler.py

Updating logic for checking expired vs locked account.

---

dataactbroker/handlers/fileHandler.py
tests/fileTests.py

Check status route now includes last_updated

Added last_updated to check_status route

---

dataactvalidator/validation_handlers/validator.py

Removing the temporary step that was breaking dev

Removing a debug step

---

dataactbroker/README.md
dataactbroker/check_status.yml
dataactbroker/handlers/fileHandler.py
tests/fileTests.py

Check status route now includes info on cross-file errors

Check status cross file

---

dataactvalidator/filestreaming/csvAbstractReader.py
dataactvalidator/validation_handlers/validator.py

This fixes handling of some formatting errors the schema team ran into

Fixing handling of formatting errors

---

dataactvalidator/validation_handlers/validator.py
tests/fileTypeTests.py

Same as dev PR, but with lower file sizes on unit tests since 664 is not included.

Hotfix stable blank year

---

dataactbroker/handlers/accountHandler.py
dataactbroker/handlers/userHandler.py
dataactcore/utils/requestDictionary.py
tests/userTests.py

Db 711 approved user list

---

dataactbroker/handlers/errorHandler.py

Missing file types returned as empty string rather than 500

Handling missing source or target file types

---

dataactvalidator/validation_handlers/validationManager.py

Split run validation into several parts for easier profiling

Db 714 split run validation

---

dataactvalidator/config/sqlrules/b4_object_class_program_activity_2.sql

Reverts fedspendingtransparency/data-act-broker-backend#147

Revert "Fixing typo"

---

dataactvalidator/validation_handlers/validationManager.py

Moved getFileColumns to outer loop

---

dataactvalidator/filestreaming/csvAbstractWriter.py
dataactvalidator/filestreaming/csvLocalWriter.py

Added newline specification to prevent extra lines on Windows, and cut some duplicate code in csv writer

added newline handling for Windows

---

dataactbroker/handlers/accountHandler.py
dataactcore/models/jobTrackerInterface.py
tests/fileTests.py

Submission status now distinguishes between submissions with errors and those without.

Db 803 submission status

---

doc/CONTRIBUTING.md
setup.py

Remove the vestiges of Python 2.7 from our documentation! Also bumped our status to beta in setup.py.

Python 3 doc update

---

dataactcore/scripts/migrateDataBroker.py

Escape the db password with quotes to handle special characters

escape db password

---

dataactbroker/handlers/fileHandler.py
tests/baseTestAPI.py
tests/userTests.py

Also added a unit test for this scenario

Finalize route now allows users in the same agency as the submission

---

dataactbroker/README.md
dataactbroker/fileRoutes.py
dataactbroker/handlers/fileHandler.py
dataactcore/aws/s3UrlHandler.py
dataactcore/config_example.yml
tests/fileTests.py
tests/runTests.py

Db 884 protected files

---

doc/CONTRIBUTING.md
requirements.txt

See commit comments for details

Resolve two small getting-started issues

---

dataactbroker/permissions.py

Applying the error logging hotfix to dev

Added error logging to permissions check

---

dataactbroker/handlers/domainHandler.py

"SYS" agency is now an option for submissions if the current, logged in user is part of the "SYS" agency

Hotfix sys submission tagging

---

dataactbroker/permissions.py

This was hitting a bug for logged in users checking a token permission, as it tried to treat it like a user permission.

Reordered checks for token permissions

---

tests/baseTestValidator.py
tests/fileTypeTests.py

The first changeset is the functional part; the second is just some cleanup

Small tweaks to filesize tests

---

dataactbroker/app.py
dataactcore/models/baseInterface.py
dataactcore/models/jobTrackerInterface.py
dataactvalidator/app.py
tests/baseTestAPI.py
tests/baseTestValidator.py
tests/fileTests.py
tests/runTests.py

This fixes the issue with connections staying open

Hotfix interface closing

---

dataactbroker/handlers/fileHandler.py

Fixes the bug of hanging after updates on cross-file

Updates to submissions do not recreate D files

---

.gitignore
tests/unit/dataactvalidator/test_a30_appropriations.py
tests/unit/dataactvalidator/test_a30_object_class_program_activity.py
tests/unit/dataactvalidator/test_a32_appropriations.py
tests/unit/dataactvalidator/test_b20_object_class_program_activity.py

Although the branch name has A33 in it, A33 tests will be performed in A33's separate branch

Unit tests for rules A30 (Files A and B), A32 (File A), and B20 (File B)

---

dataactvalidator/filestreaming/loadFile.py

Re-instate the current SF 133 loader so we can load test data.

re-instate sf133 loader

---

dataactbroker/handlers/fileHandler.py

This will mark these files as finished so the frontend doesn't get stuck waiting for them

Mark files E and F as finished while skipping generation

---

dataactbroker/handlers/fileHandler.py
tests/integration/fileTests.py

Fixed a bug with error messages being created on jobs with no errors

Only creating file generation error message if status is failed

---

dataactbroker/handlers/fileHandler.py

Fixing filename on validation job

Hotfix file generation message

---

dataactcore/utils/jobQueue.py

Hotfix file gen for stable

---

dataactbroker/handlers/fileHandler.py

Fix for D1/D2 callbacks on staging

Prepending https rather than http if port is 443

---

dataactvalidator/filestreaming/sqlLoader.py

Forget this validation setup script in the changes for PR #272. This is another piece of the work to use the session context for db access that occurs outside of a Flask request.

Run SQL validation rules load outside of global database context.

---

dataactbroker/handlers/fileHandler.py
dataactvalidator/filestreaming/csv_selection.py

This fixes the s3 writing for D files

Fixing write_csv function for using s3

---

dataactbroker/handlers/fileHandler.py
dataactcore/utils/jobQueue.py
tests/unit/dataactcore/test_job_queue.py

Analog of #301 for development

Fix f generation

---

dataactvalidator/config/sqlrules/c23_award_financial_1.sql
dataactvalidator/config/sqlrules/c23_award_financial_2.sql
dataactvalidator/config/sqlrules/c23_award_financial_3.sql
dataactvalidator/config/sqlrules/c23_award_financial_4.sql
tests/unit/dataactvalidator/test_c23_award_financial_1.py
tests/unit/dataactvalidator/test_c23_award_financial_2.py
tests/unit/dataactvalidator/test_c23_award_financial_3.py
tests/unit/dataactvalidator/test_c23_award_financial_4.py

Added clause to exclude award IDs that have an ATA

Added C24 exception to C23

---

dataactvalidator/scripts/loadTas.py
tests/integration/data/all_tas_betc.csv

Test file also changed to match new format without top line

Changed TAS loader to no longer ignore the first line

---

tests/unit/conftest.py

The `database` fixture will now cycle through each of the model types and
delete any present in the database, meaning that every test gets a fresh
start. This adds a bit of overhead (2s on 10s of tests); we might be able to
target it further in the future

Clear database after each unittest

---

dataactbroker/handlers/fileHandler.py
dataactcore/models/stagingModels.py
dataactcore/utils/fileE.py
dataactcore/utils/jobQueue.py
tests/unit/dataactcore/test_job_queue.py
tests/unit/dataactcore/test_utils_fileE.py

Functions to grab file E data from the SAM SOAP endpoints, convert that into the fields we care about, add an asynchronous task for dealing with this processing in the job queue, and connecting all of that to the HTTP `fileHandler` endpoint.
This'll probably be review changeset by changeset.

File E generation

---

dataactbroker/handlers/fileHandler.py

Improved error handling of bad download links for D files

Db 1220 handle missing d files

---

dataactcore/utils/jobQueue.py
tests/unit/conftest.py
tests/unit/dataactcore/factories/job.py
tests/unit/dataactcore/test_job_queue.py

The core here in the last changeset, which adds the retry logic. Along the way, there are several PRs to add better test coverage, some new factories, and a new fixture. This is likely easiest to review changeset by changeset.

Retry file E on exceptions

---

dataactbroker/handlers/fileHandler.py
dataactvalidator/config/sqlrules/b20_object_class_program_activity.sql

Updates language on callback URL error

Changed error message for bad links in D-file callback

---

tests/unit/dataactvalidator/test_a1_appropriations.py
tests/unit/dataactvalidator/test_a1_award_financial.py
tests/unit/dataactvalidator/test_a1_object_class_program_activity.py
tests/unit/dataactvalidator/test_a20_appropriations_1.py
tests/unit/dataactvalidator/test_a20_appropriations_2.py
tests/unit/dataactvalidator/test_a20_award_financial_1.py
tests/unit/dataactvalidator/test_a20_award_financial_2.py
tests/unit/dataactvalidator/test_a20_object_class_program_activity_1.py
tests/unit/dataactvalidator/test_a20_object_class_program_activity_2.py
tests/unit/dataactvalidator/test_a24_appropriation.py
tests/unit/dataactvalidator/test_b3_object_class_program_activity_1.py
tests/unit/dataactvalidator/test_b3_object_class_program_activity_2.py
tests/unit/dataactvalidator/test_b4_object_class_program_activity_1.py
tests/unit/dataactvalidator/test_b4_object_class_program_activity_2.py
tests/unit/dataactvalidator/test_c17_award_financial.py
tests/unit/dataactvalidator/test_c18_award_financial.py
tests/unit/dataactvalidator/test_c5_award_financial_1.py
tests/unit/dataactvalidator/test_c5_award_financial_2.py
tests/unit/dataactvalidator/test_c6_award_financial_1.py
tests/unit/dataactvalidator/test_c6_award_financial_2.py
tests/unit/dataactvalidator/test_c7_award_financial_1.py
tests/unit/dataactvalidator/test_c7_award_financial_2.py
tests/unit/dataactvalidator/test_c9_award_financial.py

This is the change recommended in the earlier DB-1104 PR, @bsweger could you take a look?  Marked as WIP since we're past code freeze.

WIP: Changed from random values to constant values

---

dataactbroker/app.py
dataactcore/migrations/versions/0fcf578896f3_add_uid_index.py
dataactcore/migrations/versions/c9e8302571cd_merging_optional_user_with_flag_removal.py
dataactcore/models/jobModels.py
dataactcore/scripts/initialize.py
dataactvalidator/app.py
tests/unit/dataactbroker/test_delete_user.py

As the linter's not part of the CI just yet, the code base has drifted a bit.
Account for unused imports now to make the later linting a bit easier.

Remove unused imports

---

tests/integration/baseTestValidator.py

This should prevent some closed-connection issues

Close the database connection before dropping it

---

dataactbroker/handlers/accountHandler.py
dataactcore/README.md
dataactcore/logging.py
dataactcore/utils/jsonResponse.py
dataactvalidator/validation_handlers/validationManager.py

Addresses some of the issues @bsweger pointed to and @alburde1 ran into after #397

Logging followup

---

dataactbroker/fsrs.py
tests/unit/dataactbroker/test_fsrs.py

Both are nonsensical, but the latter can be parsed.

Swap out 0000-00-00 for 0001-01-01 in SOAP calls

---

dataactcore/logging.py
doc/CONTRIBUTING.md
requirements.txt

Builds on the docs in #403. Tweaks logging to make prep for a structured logging config. Easiest to review changeset by changeset (though they are quite small).

Logging tweaks

---

doc/CONTRIBUTING.md

Initial docs describing how to modify the log settings. Anything else
interesting/questions that should be answered here?

Add docs around logging config

---

dataactcore/logging.py
dataactcore/migrations/env.py
dataactcore/scripts/setupAllDB.py

Notably:
* Make sure logging is set up when calling setupAllDB.py
* Make sure logging is set up when running `alembic`

A few logging fixups

---

dataactvalidator/validation_handlers/validator.py
tests/integration/mixedFileTests.py

+ Updated variable names within the validate method
+ Updated tests to match the new numbers of errors
+ Ignores completely blank rows in the submission files

DB 1346 ignore empty rows in submissions

---

dataactbroker/handlers/accountHandler.py
dataactcore/config_example.yml
tests/unit/dataactbroker/test_account_handler.py

Linking login errors to MAX's webpage to request group access

Changing login error text to include link to MAX to request group access

---

dataactvalidator/scripts/load_sf133.py
tests/unit/dataactvalidator/test_scripts_load_sf133.py

Includes regression test. We'll need to re-import all of the SF133 data, but that's a separate concern.

Fix SF133 import issue

---

dataactbroker/handlers/fileHandler.py

The values can be falsey, like is_quarter == False. I *think* this logic
matches our intent, but please double check me.
Thanks @bsweger for explaining what this was supposed to do!

Use the presence of a field rather than its value

---

dataactcore/models/lookups.py
dataactvalidator/filestreaming/fieldCleaner.py
dataactvalidator/validation_handlers/validationManager.py
dataactvalidator/validation_handlers/validator.py
tests/integration/validatorTests.py

merge-dev-stable into development

---

dataactcore/models/domainModels.py
dataactvalidator/scripts/load_sf133.py

We're planning to re-import SF133, but the current load process takes ~8hrs. Swapping in this change reduces that to ~3hrs.

Hotfix SF133 speed

---

dataactcore/utils/fileF.py
dataactcore/utils/jobQueue.py
requirements.txt
tests/unit/dataactcore/factories/fsrs.py
tests/unit/dataactcore/test_job_queue.py
tests/unit/dataactcore/test_utils_fileF.py

We had skipped a handful of fields until we had a good sense of the FSRS data. Now that time has come, so let's fill in the rest of the details.

Fill in the rest of the data for file F

---

dataactcore/local_secrets_example.yml
dataactvalidator/scripts/load_sf133.py

Update SF-133 load script to pull from centralized SF-133 bucket

---

dataactbroker/README.md
dataactbroker/handlers/accountHandler.py
tests/integration/userTests.py

Also removes (but does not replace) inaccurate info in the README

Include website_admin in the current_user endpoint

---

dataactcore/migrations/versions/0171eaaafaee_merge_78edf5b0d088_963cad0fd72a.py

Merge latest heads from alembic

---

dataactbroker/domainRoutes.py
dataactbroker/handlers/fileHandler.py
tests/unit/dataactbroker/test_domainRoutes.py

Try two at fixing CGAC agency list

---

dataactcore/utils/fileF.py
tests/unit/dataactcore/test_utils_fileF.py

Account for False in the file F mappings

---

dataactbroker/handlers/fileHandler.py

Add log message with _result_ of initial D call

---

dataactbroker/handlers/accountHandler.py
dataactbroker/userRoutes.py
dataactcore/models/userModel.py
tests/unit/dataactbroker/test_account_handler.py

This is backwards compatible (for now) by just adding a new field. It also
adds a lookup-name shortcut to UserAffiliation.

Include user affiliations in response

---

README.md
dataactbroker/handlers/fileHandler.py

Our dev-stable was out of date, so we replaced it with staging. Unfortunately, that included a bunch of merge commits which only apply to staging.
This PR includes just non-merge commits from dev-stable. When we next release, we'll replace dev-stable with development and be back to normal 😅

Fix branch issues

---

dataactbroker/README.md

Update report_url API docs

---

dataactcore/config.py

Hotfix: Remove validator host override

Dev stable -> staging

---

tests/integration/sqsTests.py

Updating SQS integration test to not purge since we're limited to 1 purge per minute

Updating integration test for SQS

---

dataactbroker/handlers/fileHandler.py

This must be changed before the web app changes. Confirm that the new request for the recent activity table contains an agency field

Adding agency column to the recent activity data query

---

dataactvalidator/validation_handlers/validationManager.py

Delete old flex fields when reuploading file.
Also fixed how we reference job_id in one location.

DB 1619 Flex Field Duplication

---

dataactvalidator/config/sqlrules/c11_cross_file.sql
dataactvalidator/config/sqlrules/c12_cross_file.sql
tests/unit/dataactvalidator/test_c11_cross_file.py
tests/unit/dataactvalidator/test_c12_cross_file.py

Validation compares PIID and/or PAID between C and D1 (either, or both. award IDs may be used)
Technical changes: 
Updated sql rules

db-1680 - Compares PIID and/or PAID

---

dataactbroker/fileRoutes.py
dataactbroker/handlers/fileHandler.py
tests/unit/dataactbroker/test_file_handler.py

Added logic content for the api routes `/list_submission` to be able to sort and order

Db 1632 sortable submissions

---

dataactbroker/handlers/fileHandler.py
dataactcore/interfaces/function_bag.py
tests/unit/dataactbroker/test_fileRoutes.py

Hotfix certified submissions

---

dataactcore/utils/fileF.py
dataactcore/utils/jobQueue.py
tests/unit/dataactcore/test_utils_fileF.py

Updating File F generation queries and adding logging statements for traceability

 Hotfix: File F Generation

---

dataactbroker/README.md
dataactbroker/fileRoutes.py
dataactbroker/handlers/fileHandler.py
tests/integration/fileTests.py

Throw an error if someone tries to certify a monthly submission.
N/A

Db 1766 prevent monthly certification

---

dataactbroker/handlers/fileHandler.py

Updating the keys for storing submissions in S3 (use submission_id instead of user_id)

Db 1699 submission file organization

---

dataactbroker/README.md
dataactbroker/fileRoutes.py
dataactbroker/handlers/fileHandler.py
dataactcore/aws/s3UrlHandler.py
dataactcore/config_example.yml

Copying certified files to the certified folder for that environment.
N/A

Db 1762 certified files in separate location

---

dataactbroker/handlers/fileHandler.py

Format the date IF monthly from numerical to string (eg. `01 => Jan`)

Pass MonthString and Year instead of MonthNumber and Year

---

dataactbroker/handlers/fileHandler.py

Fixing Date format for check_status

Fixing Date format for check_status

---

dataactbroker/handlers/fileHandler.py

Closing extra DB connections in the threaded functions

Hotfix: Closing extra DB connections on D files

---

dataactbroker/domainRoutes.py
tests/unit/dataactbroker/test_domainRoutes.py

Restrict the agency list to agencies that user has submit/create permissions

DB 1810 restrict submission by agency permissions

---

dataactcore/models/lookups.py
dataactvalidator/app.py
dataactvalidator/validation_handlers/validationError.py

**Acceptance Criteria:**
Known bad files are able to uploaded and processed and return an error message warning of invalid characters
**Technical changes:**
Delete the message from the queue where it is looping endlessly.

DB-1795 Error message warning of invalid characters

---

dataactvalidator/config/sqlrules/b9_award_financial.sql
dataactvalidator/config/sqlrules/b9_object_class_program_activity.sql
dataactvalidator/config/sqlrules/c23_award_financial_1.sql
dataactvalidator/config/sqlrules/c23_award_financial_2.sql
dataactvalidator/config/sqlrules/c23_award_financial_3.sql
dataactvalidator/config/sqlrules/c23_award_financial_4.sql
dataactvalidator/config/sqlrules/c8_award_financial.sql
dataactvalidator/config/sqlrules/c9_award_financial.sql

Speeding up some validations by adding WITH clauses and DISTINCTs to them where possible

Hotfix validation speedup dev stable

---

dataactbroker/fileRoutes.py
dataactbroker/handlers/fileHandler.py

Added routes to reset the submission state

Db mk 1806 file upload check

---

dataactvalidator/filestreaming/csvAbstractReader.py
dataactvalidator/filestreaming/csvLocalReader.py
dataactvalidator/filestreaming/csvS3Reader.py
dataactvalidator/validation_handlers/validationManager.py
tests/unit/dataactvalidator/filestreaming/test_csvAbstractReader.py

Reverts fedspendingtransparency/data-act-broker-backend#680

Revert "db1813- Refactor CSV file handling from S3 to remove streaming"

---

dataactbroker/handlers/fileHandler.py
dataactcore/interfaces/function_bag.py
dataactvalidator/validation_handlers/validationManager.py
tests/integration/fileTests.py

Resolves deadlocking issues that result from too many updates to the `Job` model

Db 1852 refactor error count calculations

---

dataactbroker/fileRoutes.py

A sub-task of DB-1858
**Acceptance Criteria:**
User gets directed to the latest step in the process when visiting any part of the submission, or already completed step of the submission
For example, cannot directly navigate to the D file generation page unless they have completed A-C file validation without critical errors
**Technical changes:**
Create a new route to check the current page

DB-1891 Create a route to check current page

---

dataactbroker/README.md
dataactbroker/handlers/fileHandler.py

Db 1850 D Download and messages

---

dataactbroker/README.md
dataactbroker/fileRoutes.py

Reverts fedspendingtransparency/data-act-broker-backend#701

Revert "Hotfix - Dev check current page status"

---

dataactbroker/README.md
dataactbroker/domainRoutes.py
tests/unit/dataactbroker/test_domainRoutes.py

Allows users to get a list of all CGACs

DB MK 1901 Generate Detached Files

---

dataactvalidator/validation_handlers/validationManager.py

db-1877 - Add cross-file validation comments

---

dataactbroker/fileRoutes.py
dataactbroker/handlers/fileHandler.py

Reverts fedspendingtransparency/data-act-broker-backend#679

Revert "Db mk 1806 file upload check"

---

dataactcore/migrations/versions/204e2cf584cd_updating_tas_lookup_table.py
dataactcore/models/domainModels.py
dataactvalidator/scripts/loadTas.py
tests/unit/dataactcore/factories/domain.py
tests/unit/dataactvalidator/test_scripts_loadTas.py

A/C:
FR Entity Type and FR Entity Description is loaded to tas_lookup table.
Options

db-1956 Upload FR Entity Type and FR Entity Description

---

dataactvalidator/filestreaming/csvReader.py
tests/unit/dataactvalidator/filestreaming/test_csvReader.py

*DOI can generate a D1 with a newline in it without error
*None

Db 1957 csv newline parsing

---

dataactvalidator/filestreaming/csvReader.py
tests/unit/dataactvalidator/filestreaming/test_csvReader.py

Reverts fedspendingtransparency/data-act-broker-backend#733

Revert "Db 1957 csv newline parsing" from dev-stable

---

dataactvalidator/filestreaming/csvReader.py
tests/unit/dataactvalidator/filestreaming/test_csvReader.py

Reverts fedspendingtransparency/data-act-broker-backend#737

Revert "Revert "Db 1957 csv newline parsing" from dev-stable"

---

dataactbroker/fileRoutes.py
tests/unit/dataactbroker/test_fileRoutes.py

Fixes to make the check current page work correctly
Please confirm the prerequisites are correct!

DB mk 2013 Check Current Page

---

dataactbroker/fileRoutes.py

Allowed for users to pass into EF without finishing validations because it did not check for the status of validation, it only checkd that there were 0 errors in validation

DB-2013 Check Current Page Fix

---

dataactvalidator/validation_handlers/validationManager.py

Not sure why this was breaking it but it was

Fixing the broken D2 generation

---

dataactbroker/fileRoutes.py

Only checked that the file size was not 0 and had 0 errors, added check to make sure that status was done

DB-2013 Skipping to crossfile before d file jobs are completed

---

dataactvalidator/config/sqlrules/d4_detached_award_financial_assistance_1.sql
tests/unit/dataactvalidator/test_d4_detached_award_financial_assistance_1.py

Adding format check for YYYYMMDD for action date
Technical Release Notes
- Updated sql rule

Db 2050 action date format

---

dataactvalidator/config/sqlrules/d32_detached_award_financial_assistance_1.sql
dataactvalidator/config/sqlrules/d33_detached_award_financial_assistance_1.sql
tests/unit/dataactvalidator/test_d32_detached_award_financial_assistance_1.py
tests/unit/dataactvalidator/test_d33_detached_award_financial_assistance_1.py

PlaceOfPerformanceStartDate and PlaceOfPerformanceCurrentEndDate must be in YYYYMMDD format
- Fixing sql rules

Db 2062 2063 pop start end date

---

dataactbroker/domainRoutes.py

Temporarily allowing all users to see all agencies in the FABS upload page.
This will need to be changed back at a later date but is needed for testing.
Same as the other one, just to dev-stable as requested

Allow all users to upload fabs dev stable

---

dataactbroker/fileRoutes.py

DB 1944 GTAS window

---

dataactvalidator/config/sqlrules/d43_detached_award_financial_assistance_1.sql
dataactvalidator/config/sqlrules/d43_detached_award_financial_assistance_2.sql
tests/unit/dataactvalidator/test_d43_detached_award_financial_assistance_1.py
tests/unit/dataactvalidator/test_d43_detached_award_financial_assistance_2.py

Reverts fedspendingtransparency/data-act-broker-backend#787

Revert "Db 2054 d43 only applies domestically"

---

dataactvalidator/config/sqlrules/d43_detached_award_financial_assistance_1.sql
dataactvalidator/config/sqlrules/d43_detached_award_financial_assistance_2.sql
tests/unit/dataactvalidator/test_d43_detached_award_financial_assistance_1.py
tests/unit/dataactvalidator/test_d43_detached_award_financial_assistance_2.py

Reverts fedspendingtransparency/data-act-broker-backend#794

Revert "Revert "Db 2054 d43 only applies domestically""

---

dataactbroker/handlers/fileHandler.py

Hotfix to resolve FABS upload submissions after FREC update

Hotfix: Removing frec_code from upload_detached_file()

---

dataactvalidator/validation_handlers/validationManager.py

Adding populate job error info for cross-file

Hotfix error count

---

dataactvalidator/config/sqlrules/b20_object_class_program_activity.sql
dataactvalidator/filestreaming/fieldCleaner.py

Padding so that 0 in Object Class for file B and C will pass validation b20

DB 2090 Padding Zero Object Class

---

dataactvalidator/scripts/loadFile.py

Commenting out the FREC function from the nightly DB loader until we can get a file to pull the data from

HOTFIX remove the FREC nightly load

---

dataactvalidator/scripts/loaderUtils.py

AC:
- Program activity name is trimmed for white space (at beginning and end of name) from source file
- Submissions have white space trimmed in program activity name (at beginning and end of name)
Note: second AC was already completed, as we already trim the content in all user-submitted data.

DB-1840 update clean_data to include trimming of all strings

---

dataactbroker/handlers/fileHandler.py
tests/unit/dataactbroker/test_fabs_derivations.py
tests/unit/dataactcore/factories/domain.py

Adding unit tests for all FABS! derivations. Also updated the derivations ever so slightly (we don't need to open/close a session when we have a session already open in the calling function, just pass it around)

Db 2035 fabs derivation unit tests

---

dataactcore/scripts/loadHistoricalFabs.py

Making a correction that was not pushed in PR [#830](https://github.com/fedspendingtransparency/data-act-broker-backend/pull/830)

DB-2116 historical FABS! loader update

---

dataactcore/models/lookups.py
dataactvalidator/app.py
dataactvalidator/validation_handlers/validationError.py
dataactvalidator/validation_handlers/validationManager.py

Reverts fedspendingtransparency/data-act-broker-backend#842

Revert "DB-2113 check submission row counts"

---

dataactcore/models/lookups.py
dataactvalidator/app.py
dataactvalidator/filestreaming/csvReader.py
dataactvalidator/validation_handlers/validationError.py
dataactvalidator/validation_handlers/validationManager.py

AC:
- Confirm the number of rows in the file matches the number of rows loaded by the validator
- File will fail file-level validation if the number of rows does not match
(Tested in Sandbox)

DB-2113 check submission row counts

---

dataactcore/models/lookups.py
dataactvalidator/app.py
dataactvalidator/validation_handlers/validationError.py
dataactvalidator/validation_handlers/validationManager.py

AC:
- Provide more accurate error code logic/text that fits the case of uploading a file with the wrong extension
- Make sure the submitted file is downloadable from this screen
- Remove link to critical error/warning reports for this file level error
- Database needs to be re-initialized to update errors and error codes

DB-2155 file type error

---

dataactbroker/handlers/fileHandler.py
dataactcore/interfaces/function_bag.py

Adding publish information to the check_status route

DB 2127 Fabs Publish information

---

dataactbroker/handlers/fileHandler.py
dataactbroker/permissions.py

Reverts fedspendingtransparency/data-act-broker-backend#841

Revert "DB-2161 hotfix FABS! access to agency submissions"

---

dataactvalidator/filestreaming/fieldCleaner.py

Remove triple quote when parsing file

2091 Triple Quote

---

dataactvalidator/filestreaming/fieldCleaner.py

Db mk 2091 triple quotes

---

dataactcore/utils/fileF.py
tests/unit/dataactcore/test_utils_fileF.py

Adding the awarding_sub_tier_agency_c filter

Db 2136 fixing f file join

---

dataactbroker/handlers/fileHandler.py
tests/unit/dataactbroker/test_fabs_derivations.py

Special cases for ppop_codes `00*****` and `00FORGN` when deriving state data

Db 2198 00 ppop codes

---

.gitignore
dataactvalidator/config/sqlrules/fabs31_detached_award_financial_assistance_4.sql
dataactvalidator/config/sqlrules/fabs31_detached_award_financial_assistance_5.sql
dataactvalidator/config/sqlrules/fabs31_detached_award_financial_assistance_6.sql
dataactvalidator/config/sqlrules/fabs31_detached_award_financial_assistance_7.sql
dataactvalidator/config/sqlrules/fabs37_detached_award_financial_assistance_1.sql
dataactvalidator/config/sqlrules/fabs37_detached_award_financial_assistance_2.sql
dataactvalidator/config/sqlrules/fabs39_detached_award_financial_assistance_1.sql
tests/unit/dataactvalidator/test_fabs37_detached_award_financial_assistance_2.py
tests/unit/dataactvalidator/test_fabs39_detached_award_financial_assistance_1.py

Major speedups for FABS31 rules. Smaller speedup for FABS39 (joining on a much smaller table for the same results)
- Updating SQL rules

Db 2188 fabs speedup

---

dataactvalidator/filestreaming/csvReader.py

Allowing either FaceValueOfDirectLoanOrLoanGuarantee or FaceValueLoanOrLoanGuarantee for FABS!

Db 2170 allow multiple headers 

---

dataactcore/models/stagingModels.py
dataactcore/scripts/loadHistoricalFabsExtraColumns.py

AC:
- script is written to update historical FABS data from ASP csv file

DB-2199 historical FABS new ASP columns loader

---

dataactcore/migrations/versions/6126ac2553e5_merge_cd1025a_and_e4ac552.py

Merging heads
- New alembic migration to fix all the broken ones from before

Fixing alembic conflicts from dev-stable

---

dataactbroker/handlers/fileHandler.py
tests/unit/dataactbroker/test_fabs_derivations.py
tests/unit/dataactcore/factories/domain.py

DB-MK-2199 FABS derivations to dev stable

---

dataactbroker/handlers/fileHandler.py

Hotfix legal entity city code

---

dataactbroker/handlers/fileHandler.py

Hotfix legal entity city code derivation

---

dataactbroker/handlers/fileHandler.py
tests/unit/dataactbroker/test_fabs_derivations.py

Fixing existing and potential future issues with derivations and removing a few extraneous queries (hopefully that makes them run at least a little faster)

Db 2234 fixing fabs derivations

---

dataactcore/utils/fileD1.py
dataactcore/utils/fileD2.py

AC:
- Generate D2 files using the FABS! database data
- Generate D1 files using the FPDS database data

DB-2157 fix D file generation

---

dataactbroker/handlers/fileHandler.py
dataactvalidator/config/example_program_activity.csv
tests/unit/dataactbroker/test_fabs_derivations.py

Backend: Staging -> Prod

---

requirements.txt

Remove update 0.4.4 from requirements.txt
- Changes to requirements.txt

Hotfix remove update from requirements

---

dataactcore/scripts/loadDUNS.py
dataactcore/scripts/loadHistoricalFabs.py
dataactvalidator/config/detachedAwardFields.csv

AC:
- Determine which fields are zero padded
- Ensure that no zip fields are padded (there are 3 zip fields)
- Ensure that DUNs isn't zero-padded.

DB-2130 remove padding from DUNS and zip fields

---

dataactbroker/handlers/fileGenerationHandler.py

Create file locally, then stream to remote

Hotfix: D file gen CPU usage

---

dataactbroker/handlers/fileHandler.py

Fix a bug created in this PR: https://github.com/fedspendingtransparency/data-act-broker-backend/pull/1013

DB-2295 fix a bug created in previous PR

---

dataactbroker/handlers/fileHandler.py

Removing redundant derivations AGAIN

Db 2323 remove redundant fabs derivations

---

dataactbroker/handlers/fileHandler.py

AC:
- updated_at field changes when the publish_status_id field changes

DB-2331 change updated_at when changing the publish_status

---

dataactvalidator/config/sqlrules/a33_appropriations_2.sql
dataactvalidator/config/sqlrules/a35_cross_file.sql
dataactvalidator/config/sqlrules/b20_object_class_program_activity.sql
dataactvalidator/config/sqlrules/b9_award_financial.sql
dataactvalidator/config/sqlrules/b9_object_class_program_activity.sql
dataactvalidator/config/sqlrules/c11_cross_file.sql
dataactvalidator/config/sqlrules/c9_award_financial.sql

Speeding up dabs sql validations
- sql rule changes

Db 2300 dabs sql speedups

---

dataactbroker/handlers/fileGenerationHandler.py
dataactcore/scripts/pullFPDSData.py

AC:
- Cached D1 file generations are cleared after a successful daily FPDS load

DB-2322 Update D1 caching after FPDS data load

---

dataactbroker/handlers/fileHandler.py

If the job contains the current cached D file, do not change the job file-related data

DB-2295 Hotfix: Submission job info should not change

---

dataactbroker/handlers/fileHandler.py

A/C:
- Submissions are sortable by publish/certify date

DB-2297 fix published and certified on submission sort 

---

dataactbroker/fileRoutes.py
dataactbroker/handlers/fileHandler.py
dataactbroker/handlers/submission_handler.py
dataactcore/interfaces/function_bag.py
dataactvalidator/validation_handlers/validationManager.py
tests/integration/fileTests.py
tests/unit/dataactbroker/test_obligations.py

A/C:
- Agencies are able to delete any submission that is not certified.
- Submission-related functions from `function_bag.py` have been separated out to a `submission_handler.py` file

DB-2342: Allow for deletion of a submission with cached file

---

dataactcore/scripts/deriveCFDATitle.py

https://federal-spending-transparency.atlassian.net/browse/DEV-225

Missing CFDA Title

---

dataactcore/scripts/deriveCFDATitle.py

Dev 225 missing cfda title

---

dataactvalidator/scripts/readZips.py

AC:
- Zip codes are loaded in under a day
_Note: the Zip loader should take about 1/2 the time with these changes_

DEV-46 Zips loader performance

---

dataactbroker/config/supervisord.conf

Add empty `environment` variable to `supervisord.conf` file

Ops supervisord update

---

dataactcore/scripts/pullFPDSData.py

Fixing women_owned_small_business mapping in the FPDS nightly loader

Dev 415 women owned small business fpds loader fix

---

dataactbroker/scripts/update_historical_duns.py

[Story Link](https://federal-spending-transparency.atlassian.net/browse/DB-2235)
Adding historical DUNS from DUNS_export.csv located on S3
Performance notes:
Tested this locally on with a file on my computer:
Average time to get row count of file: ~ 23 s average
Time to update 10k rows to DUNS table: 5-20s
The file contains over 4 million rows which equates to 409 batches. At 20 seconds a batch estimated time to complete script will take 2.5 hours.

Adding script to update historical duns

---

dataactbroker/scripts/update_historical_duns.py

Updating script to update DUNS table for historical agencies to make changes found through testing.
[Story Link](https://federal-spending-transparency.atlassian.net/browse/DB-2235)
Performance notes on running script on test environment:
Time to update 10k rows to DUNS table: 1-5s 
The file contains over 4 million rows which equates to 409 chunks. It took 17 mins to finish on the test environment.

Hotfix historical duns

---

dataactbroker/handlers/fabsDerivationsHandler.py
dataactbroker/handlers/fileHandler.py
tests/unit/dataactbroker/test_fabs_derivations.py

Updating fabs derivations to have their own file and be split out into functions for ease of access

Fabs derivations refactor

---

dataactvalidator/filestreaming/csvReader.py

Make CorrectionLateDeleteIndicator backward-compatible with switch to  CorrectionDeleteIndicator

DEV-650 CorrectionLateDeleteIndicator field

---

dataactcore/utils/fileF.py

Adding POP state name and LE state name to File F Generation
[Ticket](https://federal-spending-transparency.atlassian.net/browse/DEV-441)

Adding state name to file F generation

---

dataactbroker/handlers/fileHandler.py
dataactcore/scripts/loadDUNS.py
dataactcore/utils/parentDuns.py

Replacing limit/offset combo because slice is faster

Dev 234 remove limit offset

---

dataactbroker/handlers/fileGenerationHandler.py

[Related JIRA ticket](https://federal-spending-transparency.atlassian.net/browse/DEV-818)

HOTFIX: D file generation stuck in "running"

---

dataactvalidator/config/sqlrules/fabs15_detached_award_financial_assistance_2.sql
dataactvalidator/config/sqlrules/fabs16_detached_award_financial_assistance.sql
dataactvalidator/config/sqlrules/fabs17_detached_award_financial_assistance.sql
dataactvalidator/config/sqlrules/sqlRules.csv
tests/unit/dataactvalidator/test_fabs15_detached_award_financial_assistance_2.py
tests/unit/dataactvalidator/test_fabs16_detached_award_financial_assistance.py
tests/unit/dataactvalidator/test_fabs17_detached_award_financial_assistance.py

Updating FABS15.2, FABS16, and FABS17 to also activate when record type is 1
- Update SQL Rules

Dev 887 fabs 15 16 17 record type changes

---

dataactbroker/handlers/fabsDerivationsHandler.py
tests/unit/dataactbroker/test_fabs_derivations.py

Adding derivations for place of performance data for record type 3

Dev 897 ppop derivations

---

dataactvalidator/config/sqlrules/fabs44_detached_award_financial_assistance_1.sql
dataactvalidator/config/sqlrules/fabs44_detached_award_financial_assistance_2.sql
dataactvalidator/config/sqlrules/fabs44_detached_award_financial_assistance_3.sql
tests/unit/dataactvalidator/test_fabs44_detached_award_financial_assistance_1.py
tests/unit/dataactvalidator/test_fabs44_detached_award_financial_assistance_2.py
tests/unit/dataactvalidator/test_fabs44_detached_award_financial_assistance_3.py

Updating FABS44 to be ignored when CorrectionDeleteIndicator is D
- SQL rule updates

Dev 964 le cd ignore deletes

---

tests/unit/dataactbroker/test_file_generation_handler.py

Fix testing error with postgres 9.4.7 also works with 9.5.x

Pytest postgres94 fix

---

dataactvalidator/scripts/load_usps_files.py

[Story Link](https://federal-spending-transparency.atlassian.net/browse/DEV-820)

Fixing usps loader paths

---

dataactcore/scripts/initialize.py
dataactvalidator/scripts/loadFile.py
dataactvalidator/scripts/load_cfda_data.py
dataactvalidator/scripts/loaderUtils.py

This is the new PR to extract cfda load.

extracted cfda load

---

dataactcore/scripts/pullFPDSData.py
tests/unit/data/fpdsXML.txt
tests/unit/dataactbroker/test_pullFPDSData.py

Adding `https://www.fpds.gov/FPDS` as an acceptable namespace

DEV-1051: Add additional acceptable FPDS namespace

---

APISubmissionGuide.md
dataactbroker/README.md
dataactbroker/fileRoutes.py
dataactbroker/handlers/fileHandler.py
dataactbroker/handlers/submission_handler.py
tests/integration/fileTests.py
tests/unit/dataactbroker/test_submission_handler.py

Create a new endpoint to retrieve submission metadata

Dev 1075 submission metadata endpoint

---

dataactvalidator/scripts/loadFile.py
dataactvalidator/scripts/loaderUtils.py

Moving cfda updates straight to master

Hotfix cfda updates

---

dataactcore/scripts/initialize.py
dataactvalidator/scripts/loadFile.py
dataactvalidator/scripts/load_object.py
dataactvalidator/scripts/load_object_class.py

created flag to extract object class only

extracted object class

---

dataactvalidator/config/sqlrules/sqlRules.csv

Removing rules FABS37.1 and FABS37.2 temporarily

Hotfix turn off cfda rules

---

dataactbroker/app.py
dataactbroker/handlers/accountHandler.py
dataactbroker/handlers/aws/sesEmail.py
dataactbroker/handlers/fileHandler.py
dataactbroker/handlers/submission_handler.py
dataactvalidator/validation_handlers/validationManager.py
tests/unit/dataactbroker/test_submission_handler.py
tests/unit/dataactcore/factories/user.py

Added a test for certifying DABS. Replaced all instances of `isLocal` with `is_local`

Hotfix: fix bug when certifying DABS

---

dataactvalidator/config/sqlrules/sqlRules.csv

https://federal-spending-transparency.atlassian.net/browse/DEV-1177

Adding back FABS rules 37.1 and 37.2

---

dataactbroker/file_routes.py
dataactbroker/handlers/fileHandler.py

Make fabs a required argument so not including it can't break a submission. All other user errors already didn't create a bad submission

DEV-1192 upload fabs bad params

---

dataactbroker/README.md
dataactbroker/file_routes.py
tests/integration/fileTests.py

Replace `report_url` POST request to a GET.
Replace `report_url` with a GET. Update README for this and DEV-1212. Add tests.
[DEV-1213](https://federal-spending-transparency.atlassian.net/browse/DEV-1213)

DEV-1213: Change report_url to GET

---

dataactcore/scripts/pullFPDSData.py

Update the FPDS nightly loader to compare a count of the records expected by the pull to the incoming data to make sure that the data does not change while the pull is happening.
**Link to JIRA Ticket:** N/A

Hotfix: FPDS loader, data count checker

---

dataactbroker/README.md

**High Level Description:**
Fixing documentation formatting.
**Technical Details:**
None
[DEV-1071](https://federal-spending-transparency.atlassian.net/browse/DEV-1071)
- [ NA] Backend review completed
- [NA ] Merged concurrently with [Frontend#123](https://github.com/fedspendingtransparency/data-act-broker-backend/pull/123)
- [ NA] Unit & integration tests updated with relevant test cases
- [NA ] Frontend impact assessment completed

DEV-1071 Fixing some documentation formatting

---

dataactbroker/README.md
dataactbroker/file_routes.py
dataactbroker/handlers/fileHandler.py
tests/integration/fileTests.py
tests/unit/dataactbroker/test_file_handler.py

Make sure only valid cross-files are requested in report_url
Limit cross_type in report_url to only possible cross_types and validate that the file_type and cross_type make a valid pair.
[DEV-1310](https://federal-spending-transparency.atlassian.net/browse/DEV-1310)

DEV-1310: Validate cross_types in report_url

---

dataactbroker/README.md

Fixing docs
Didn't remove the parameters we aren't using from the docs, fixing that now.
[DEV-1280](https://federal-spending-transparency.atlassian.net/browse/DEV-1280)

DEV-1280: Fixing missed docs

---

APISubmissionGuide.md
dataactbroker/README.md

**High Level**
Making MAX Login process a little better documented
**Technical Details**
None
No JIRA Ticket associated

MAX Login docs update

---

dataactbroker/README.md
dataactbroker/app.py
dataactbroker/file_routes.py
dataactbroker/handlers/fileHandler.py
dataactcore/aws/s3Handler.py
dataactcore/config.py
dataactcore/config_example.yml
dataactcore/local_secrets_example.yml
tests/integration/baseTestValidator.py
tests/integration/detachedUploadTests.py
tests/integration/fileTests.py
tests/integration/userTests.py
tests/unit/dataactbroker/test_file_handler.py
tests/unit/dataactbroker/test_file_routes.py

Removing old upload code.
Removing all code that could return credentials or other private information since it is no longer used. Also cleaning out old functions/routes that are no longer used due to these changes.
[DEV-1321](https://federal-spending-transparency.atlassian.net/browse/DEV-1321)

DEV-1321: remove old upload code

---

dataactcore/utils/requestDictionary.py
dataactvalidator/validation_handlers/file_generation_handler.py

Mark job as finished when regenerating a cached file.

Hotfix: fix job issues for cached file regeneration

---

dataactbroker/handlers/fileHandler.py
dataactcore/utils/requestDictionary.py
tests/integration/fileTests.py

Fix bug that stopped users from creating monthly submissions
Multipart form-data casts the boolean to a string. We need to parse the string to understand if it's a truthy value. Added tests.

Hotfix: Fix monthly submission creation

---

doc/CONTRIBUTING.md

contextual git workflow/ci info

---

dataactcore/migrations/versions/66ce64f4c1da_merge_76d8a31caa51_and_ab4eac43f605.py

Merge heads

---

dataactvalidator/config/sqlrules/fabs21_detached_award_financial_assistance_1.sql
dataactvalidator/config/sqlrules/fabs21_detached_award_financial_assistance_2.sql
dataactvalidator/config/sqlrules/sqlRules.csv
tests/unit/dataactvalidator/test_fabs21_detached_award_financial_assistance_1.py
tests/unit/dataactvalidator/test_fabs21_detached_award_financial_assistance_2.py

Update FABS21 error text and change number to FABS21.1. Add FABS21.2 to make sure FundingSubTierCode and FundingOfficeCode map to the same top tier agency code.
See above
[DEV-1441](https://federal-spending-transparency.atlassian.net/browse/DEV-1441)

DEV-1441: FABS21 funding office and sub tier validations

---

pull_request_template.md

Include a PR template that autopopulates the Pull Request contents for Broker Backend.
The contents of the file should autopopulate future Pull Requests.
N/A
- Merged concurrently with Frontend N/A 

Add PR Template to Github

---

dataactbroker/helpers/fabs_derivations_helper.py
tests/unit/dataactbroker/test_fabs_derivations.py

Derive funding sub tier code from funding office code if one hasn't been added. If a funding office code wasn't provided, get the earliest transaction for the award and copy whatever funding office code was entered there.
Funding sub tier code is now derived (when not provided) based on funding office code. All other funding derivations (sub tier name, top tier name/code) remain the same because these should be the same whether we're using office code or sub tier code.
Adding a process to get the earliest action date for an award (awarding sub tier code + fain/uri (uri for record type 1, fain otherwise)) and getting a transaction for that award that has that action date so we can copy the office codes from it if none are provided in the …

DEV-1148: Funding SubTierAgency derivations

---

README.md
doc/CONTRIBUTING.md
doc/INSTALL.md

API users had issues installing and using the Broker locally. Update the install instructions to include any `initialize` scripts that are needed.
Update `doc/INSTALL.md` markdown.
[DEV-1377](https://federal-spending-transparency.atlassian.net/browse/DEV-1377)

DEV-1377: Update install instructions in documentation

---

Dockerfile

- This PR is to hotfix Dockerfile changes in `DEV-1398` so the jenkins configs are not different from dev.  
- This change is needed to run the broker deployments using python 3.5 instead of python 3.4.
Adds the broker code repository into the container in build-jenkins job `Backend-DBBuild` so it can run the code in `Backend-DBUpdate`.

adding repo within container

---

dataactvalidator/scripts/loadTas.py

Updates to the TAS script so that when we backfill, it properly updates the columns.
(N/A)

Hotfix: TAS Clean Data Padding

---

dataactbroker/README.md

Adding documentation to clarify FREC and CGAC
N/A
[DEV-1624](https://federal-spending-transparency.atlassian.net/browse/DEV-1624)
- [ NA ] Unit & integration tests updated with relevant test cases
- [ NA ] Frontend impact assessment completed

DEV-1624: Documentation on FREC and CGAC

---

dataactbroker/README.md

Adding docs covering the use of existing_submission_id to DABS docs
N/A
[DEV-1623](https://federal-spending-transparency.atlassian.net/browse/DEV-1623)
- [ NA ] Unit & integration tests updated with relevant test cases
- [ NA ] Frontend impact assessment completed

DEV-1623: Updates to existing submission documentation

---

dataactvalidator/scripts/loadTas.py

Backend: Staging -> Master

---

dataactcore/config_example.yml
dataactcore/scripts/load_federal_hierarchy.py

Utilizing `federal_hierarchy_api_url` as a configuration variable so we can potentially test other OMB environments without changing the script code.
Added federal_hierarchy_api_url as a config var. Updated the script to use that config var instead of the hardcoded URL.
N/A

Add federal_hierarchy_api_url as a configuration variable

---

dataactbroker/helpers/fabs_derivations_helper.py
tests/unit/dataactbroker/test_fabs_derivations.py

Fixing and speeding up FABS derivations, specifically in the office code derivation.
Adding record type to queries for getting the earliest award
[DEV-1717](https://federal-spending-transparency.atlassian.net/browse/DEV-1717)

DEV-1717: fh office code derivation update

---

dataactcore/scripts/pullFPDSData.py

Add some specific logging for failures
Adding logging for if we get 0 results in a pull where we expected data, whether in the initial count or in the middle of the pull.
N/A

FPDS Loader Error Printing

---

dataactcore/config_example.yml

Adding the A file generation to the config example
See above
N/A

Update config example

---

dataactcore/scripts/pull_fpds_data.py
requirements.txt

Update the requests library
The requests library is very out of date and needed to be updated.
[DEV-1852](https://federal-spending-transparency.atlassian.net/browse/DEV-1852)

DEV-1852: update requests library

---

dataactbroker/README.md

Making it clear that /v1/login/ is not a production endpoint
N/A
[DEV-1696](https://federal-spending-transparency.atlassian.net/browse/DEV-1696)
- [NA] Backend review completed
- [NA] Unit & integration tests updated with relevant test cases
- [NA] Frontend impact assessment completed

DEV-1696: Fixing docs for /v1/login

---

dataactvalidator/app.py

Remove unused parameter when handling file generation and validations.
Parameter was removed from a function, but the code to remove it from the function call was stashed and never re-added. Updated the code and tested again locally.
[DEV-1492](https://federal-spending-transparency.atlassian.net/browse/DEV-1492)

DEV-1492: FileGeneration implementation bugfix

---

dataactbroker/handlers/fileHandler.py

Preventing FABS submissions from apparently getting stuck in publishing
Breaking up the query into smaller chunks so it doesn't cause memory issues with huge submissions.
[DEV-1913](https://federal-spending-transparency.atlassian.net/browse/DEV-1913)

DEV-1913: Incremental FABS publishing

---

dataactcore/migrations/versions/e33da285ac19_merge_32290_38d83.py

Merge alembic heads so the database can get created/deployed

Federal Hierarchy Merge Heads

---

dataactcore/scripts/load_federal_hierarchy.py

The truncate should not occur unless the entire script completes, so we should keep it in transaction until we `commit` at the very end.
Removed the `sess.commit()`.
N/A

Federal Hierarchy: Remove truncate commit from script

---

dataactbroker/helpers/fabs_derivations_helper.py
tests/unit/dataactbroker/test_fabs_derivations.py

Don't update office codes if the record is correcting the base record
Prevent derivations on corrections to the base record
[DEV-1882](https://federal-spending-transparency.atlassian.net/browse/DEV-1882)

DEV-1882: Office derivation update

---

dataactcore/scripts/raw_sql/backfill_awarding_office_names_q12019.sql
dataactcore/scripts/raw_sql/backfill_funding_office_names_q12019.sql
dataactcore/scripts/run_sql.py

Script created to backfill `awarding_office_name` and `funding_office_name` from their office codes in FY2019Q1 FABS data.
Created the `run_sql.py` script for reusability. Added two SQL files, one for each reported office type.
[DEV-1880](https://federal-spending-transparency.atlassian.net/browse/DEV-1880)

DEV-1880: Script to backfill Federal Hierarchy office name derivations

---

dataactbroker/handlers/submission_handler.py
dataactcore/models/stagingModels.py
dataactcore/utils/fileA.py
dataactcore/utils/fileD1.py
dataactcore/utils/fileD2.py
tests/unit/dataactbroker/test_submission_handler.py

Copy A, B, C data to certified tables
Store all data in Appropriation, ObjectClassProgramActivity, and AwardFinancial for a submission in certified tables when certifying the data. Delete any previously certified data.
[DEV-1981](https://federal-spending-transparency.atlassian.net/browse/DEV-1981)

DEV-1981: Copy data on certify

---

dataactbroker/README.md
dataactbroker/handlers/fileHandler.py

Check currently publishing FABS submissions before publishing
We want to check not only published FABS submissions but also currently publishing ones for duplicate rows.
[DEV-1943](https://federal-spending-transparency.atlassian.net/browse/DEV-1943)

DEV-1943: check publishing fabs

---

dataactbroker/helpers/generic_helper.py
dataactcore/scripts/load_historical_certified_dabs.py
dataactcore/scripts/raw_sql/populate_a_certified_files_history_types.sql
dataactcore/scripts/raw_sql/populate_b_certified_files_history_types.sql
dataactcore/scripts/raw_sql/populate_c_certified_files_history_types.sql
dataactvalidator/scripts/load_sf133.py

Certified DABS data will be pulled by USAspending from the new Certified tables. We need to backfill this data with the previous data that has been submitted and certified.
Script created to copy data directly from the staging tables if they have the most up-to-date files loaded into them, otherwise pull directly from files (which is significantly slower).
[DEV-1982](https://federal-spending-transparency.atlassian.net/browse/DEV-1982)

DEV-1982: Script to populate certified DABS tables

---

FileLogic.md
dataactbroker/README.md

Document the file A generation process.
Include details of how TAS are grouped and monetary values derived in the documentation.
[DEV-1850](https://federal-spending-transparency.atlassian.net/browse/DEV-1850)

DEV-1850: File A generation docs

---

dataactbroker/helpers/generic_helper.py

Update format_internal_tas to correctly strip and create TAS.

Hotfix: Update historical certified DABS script

---

dataactvalidator/config/example_program_activity.csv

Updating S3 URL to a proxy for `example_program_activity.csv`
[OPS-504](https://federal-spending-transparency.atlassian.net/browse/OPS-504)

[OPS-504] Add program activity path to files.usaspending.gov

---

dataactvalidator/app.py

Moving marking job status to after we've established that the job exists
There's no reason to mark the job status before we make sure the job exists. Do that first.
[DEV-2088](https://federal-spending-transparency.atlassian.net/browse/DEV-2088)

DEV-2088: Job status marking

---

dataactvalidator/validation_handlers/validationManager.py

Hotfix: Row Count based on CSV reader

---

dataactbroker/helpers/generation_helper.py

Hotfix: File Regeneration Job Status

---

dataactcore/scripts/get_fsrs_updates.py

We run this FSRS job regularly, this adds an option to pull the most recently updated FABS_for_FSRS file from the S3 bucket.

modify FSRS FABS extract to pull date from s3

---

dataactbroker/handlers/fileHandler.py
dataactcore/scripts/load_federal_hierarchy.py
dataactvalidator/filestreaming/csv_selection.py
dataactvalidator/validation_handlers/file_generation_manager.py

Include an extra parameter to the federal hierarchy loader that exports the updated office table to a csv. 
- Updated `generate_temp_query_file` with a header argument for more use cases.
- Refactored `write_query_to_file` for more use cases
[DEV-2094](https://federal-spending-transparency.atlassian.net/browse/DEV-2094)

DEV-2094: Federal Hierarchy Artifacts - Export Office Table

---

dataactvalidator/config/sqlrules/fabs21_detached_award_financial_assistance_2.sql
dataactvalidator/config/sqlrules/fabs23_detached_award_financial_assistance_2.sql

See title
It's a bad idea to pull all the data from 2 tables for every row we're validating, fun fact.
N/A

Fixing memory/speed issues for office table validations

---

dataactbroker/handlers/submission_handler.py
tests/unit/dataactbroker/test_submission_handler.py

Just an update to the error message for a quarterly_revalidation_threshold issue
See Above
[DEV-1384](https://federal-spending-transparency.atlassian.net/browse/DEV-1384)

DEV-1384: Updating error text

---

StyleGuide.md
dataactbroker/README.md

Updating docs to include new errors we introduced and just making sure they're up to date.
Only updating docs of routes that have become relevant or were recently updated.
[DEV-2186](https://federal-spending-transparency.atlassian.net/browse/DEV-2186)

DEV-2186: update certify_submission and restart_validation docs

---

requirements.txt

Upgrading pyYAML to safer version to address security.
(see above)
[OPS-565](https://federal-spending-transparency.atlassian.net/browse/OPS-565)
- * Unit & integration tests updated with relevant test cases
- * Frontend impact assessment completed

OPS-565: Upgrading pyYAML to 4.2b1

---

dataactvalidator/validation_handlers/validationManager.py

Ignoring extra carriage returns in a file
Ignore completely blank lines that aren't part of a quote-enclosed cell when counting the total number of lines to expect in the file.
[DEV-2019](https://federal-spending-transparency.atlassian.net/browse/DEV-2019)

DEV-2019: Ignore blank lines

---

dataactvalidator/scripts/load_cfda_data.py

The source CSV files have an encoding of "Windows CP-1252" (`cp1252`). The loading scripts were incorrectly set to Latin-1 (`latin1`).
See High level description
[DEV-1052](https://federal-spending-transparency.atlassian.net/browse/DEV-1052)

Fix DEV-1052: Changing encoding to match CFDA source CSV

---

dataactcore/scripts/pull_fpds_data.py

Adding a metrics file to the pull_fpds_data script
File to be used by ops
[DEV-2293](https://federal-spending-transparency.atlassian.net/browse/DEV-2293)

DEV-2293: FPDS loader metrics file

---

dataactvalidator/config/agency_list.csv
dataactvalidator/config/example_agency_codes_list.csv

Adding the new sub tier to the lists for local dev
Actual files that need to be updated for non-local dev will be uploaded to AWS separately
[DEV-2451](https://federal-spending-transparency.atlassian.net/browse/DEV-2451)

DEV-2451: Add new sub tier

---

docker-compose.yml

Change postgres port to not conflict with api
Incremented a couple ports above 5432 for future-proofing (and selfishness since I have to move other things to 5433 sometimes)
None
- [ Not sure what this means; may need to work with broker dev] Merged concurrently with [Frontend#1234](https://github.com/fedspendingtransparency/data-act-broker-web-app/pull/1234)
- [ N/A] Unit & integration tests updated with relevant test cases
- [ N/A] Frontend impact assessment completed

Change postgres port to not conflict with api

---

dataactbroker/helpers/pandas_helper.py
dataactvalidator/scripts/load_cfda_data.py
dataactvalidator/scripts/load_location_data.py

Check if there are changes to the tables before loading in new location data
We don't want to reload the exact same data in locations, so compare all location data before inserting each into their respective tables. `--force` flag exists to force reload of all data
[DEV-2589](https://federal-spending-transparency.atlassian.net/browse/DEV-2589)

DEV-2589: diff check location loader

---

dataactbroker/routes/file_routes.py
dataactbroker/routes/generation_routes.py
requirements.txt

webargs: 1.5.1 --> 5.1.3
Jinja2: 2.8 --> 2.10.1
SQLAlchemy: 1.1.9 --> 1.3.0
SQLAlchemy-Utils: 0.32.1 --> 0.33.11

package updates

---

dataactbroker/handlers/fileHandler.py
dataactbroker/helpers/generic_helper.py
dataactcore/models/jobModels.py
dataactcore/models/stagingModels.py
requirements.txt

Continuing to update packages.
SQLAlchemy = 1.3.3
[DEV-2621](https://federal-spending-transparency.atlassian.net/browse/DEV-2621)

DEV-2621: Update Packages

---

Dockerfile
requirements.txt

Updating packages.
Paramiko: 2.4.2
Bcrypt: 1.3.3
[DEV-2729](https://federal-spending-transparency.atlassian.net/browse/DEV-2729)

DEV-2729: Upgrade Paramiko, Bcrypt

---

dataactcore/scripts/derive_historical_transaction_exec_comp.py
dataactcore/scripts/load_exec_comp.py

Backfill executive compensation data in FABS and FPDS transactions
Use monthly files to backfill executive compensation data in FABS and FPDS tables starting at 10/01/2017
[DEV-2760](https://federal-spending-transparency.atlassian.net/browse/DEV-2760)
- OPs ticket: https://federal-spending-transparency.atlassian.net/browse/OPS-712

DEV-2760: backfill transaction exec comp

---

APISubmissionGuide.md

Adding an intro to the API Submission Guide.
Making sure users know that a basic knowledge of REST APIs is needed to use the API and that the guides provided are tailored to people who have that.
[DEV-2786](https://federal-spending-transparency.atlassian.net/browse/DEV-2786)

DEV-2786: Update API Documentation

---

tests/unit/dataactvalidator/test_fabs18_detached_award_financial_assistance.py
tests/unit/dataactvalidator/test_fabs31_detached_award_financial_assistance_1.py
tests/unit/dataactvalidator/test_fabs31_detached_award_financial_assistance_2.py
tests/unit/dataactvalidator/test_fabs31_detached_award_financial_assistance_3.py
tests/unit/dataactvalidator/test_fabs31_detached_award_financial_assistance_4.py
tests/unit/dataactvalidator/test_fabs31_detached_award_financial_assistance_5.py
tests/unit/dataactvalidator/test_fabs31_detached_award_financial_assistance_6.py
tests/unit/dataactvalidator/test_fabs31_detached_award_financial_assistance_7.py

Updating tests to check for case insensitive
The SQL was already case insensitive but we want the tests to check for that as well.
[DEV-2689](https://federal-spending-transparency.atlassian.net/browse/DEV-2689)

DEV-2689: Case insensitive business types checks

---

tests/unit/dataactvalidator/test_fabs13_detached_award_financial_assistance_2.py
tests/unit/dataactvalidator/test_fabs13_detached_award_financial_assistance_3.py
tests/unit/dataactvalidator/test_fabs14_detached_award_financial_assistance_2.py
tests/unit/dataactvalidator/test_fabs14_detached_award_financial_assistance_3.py
tests/unit/dataactvalidator/test_fabs15_detached_award_financial_assistance_1.py
tests/unit/dataactvalidator/test_fabs15_detached_award_financial_assistance_2.py
tests/unit/dataactvalidator/test_fabs16_detached_award_financial_assistance.py
tests/unit/dataactvalidator/test_fabs17_detached_award_financial_assistance.py

Updating tests to include case insensitivity checks
SQL is already checking things while ignoring case but we want to include that in the tests
[DEV-2687](https://federal-spending-transparency.atlassian.net/browse/DEV-2687)

DEV-2687: country code case insensitive tests

---

dataactvalidator/config/sqlrules/c11_cross_file.sql
dataactvalidator/config/sqlrules/c12_cross_file.sql
dataactvalidator/config/sqlrules/c23_award_financial_1.sql
dataactvalidator/config/sqlrules/c23_award_financial_2.sql
dataactvalidator/config/sqlrules/c23_award_financial_3.sql
dataactvalidator/config/sqlrules/c23_award_financial_4.sql
dataactvalidator/config/sqlrules/c8_award_financial.sql
dataactvalidator/config/sqlrules/c9_award_financial.sql
tests/unit/dataactvalidator/test_c11_cross_file.py
tests/unit/dataactvalidator/test_c12_cross_file.py
tests/unit/dataactvalidator/test_c23_award_financial_1.py
tests/unit/dataactvalidator/test_c23_award_financial_2.py
tests/unit/dataactvalidator/test_c23_award_financial_3.py
tests/unit/dataactvalidator/test_c23_award_financial_4.py
tests/unit/dataactvalidator/test_c8_award_financial.py
tests/unit/dataactvalidator/test_c9_award_financial.py

Makes cross-file validations case insensitive
C->D1 and C->D2 comparisons should be case insensitive for the fain/uri/piid/paid linkage.
[DEV-2691](https://federal-spending-transparency.atlassian.net/browse/DEV-2691)

DEV-2691: case insensitive cross file

---

dataactbroker/handlers/fileHandler.py

Simply adds the user's email to FABS submissions and DABS A/B/C files.
(see title)
[DEV-2682](https://federal-spending-transparency.atlassian.net/browse/DEV-2682)

DEV-2682: User Metadata to Uploads

---

dataactvalidator/app.py
dataactvalidator/filestreaming/csvReader.py
dataactvalidator/validation_handlers/validationManager.py

Including DAIMS names in header errors (both in downloadable report and on the frontend) 
- Includes fix allowing frontend to display header errors
- Sorts the missing/duplicated header names in alphabetical order
[DEV-2024](https://federal-spending-transparency.atlassian.net/browse/DEV-2024)

DEV-2024: Header Error include DAIMS names

---

dataactvalidator/scripts/load_country_codes.py

Making sure initialize can run properly
Fixing diff check on country codes
[DEV-3055](https://federal-spending-transparency.atlassian.net/browse/DEV-3055)

DEV-3055: Diff checker bug

---

dataactvalidator/config/sqlrules/fabs31_detached_award_financial_assistance_5.sql
dataactvalidator/config/sqlrules/fabs31_detached_award_financial_assistance_6.sql
dataactvalidator/config/sqlrules/fabs31_detached_award_financial_assistance_7.sql
dataactvalidator/config/sqlrules/fabs37_detached_award_financial_assistance_1.sql
dataactvalidator/config/sqlrules/fabs37_detached_award_financial_assistance_2.sql
tests/unit/dataactvalidator/test_fabs31_detached_award_financial_assistance_5.py
tests/unit/dataactvalidator/test_fabs31_detached_award_financial_assistance_6.py
tests/unit/dataactvalidator/test_fabs31_detached_award_financial_assistance_7.py
tests/unit/dataactvalidator/test_fabs37_detached_award_financial_assistance_1.py
tests/unit/dataactvalidator/test_fabs37_detached_award_financial_assistance_2.py

Make action type case insensitive in FABS validations
See above
[DEV-3046](https://federal-spending-transparency.atlassian.net/browse/DEV-3046)

DEV-3046: case insensitive action type

---

dataactbroker/handlers/fileHandler.py

"is_quarter_format" was being overridden for existing submissions in special cases, changing them from quarterly to monthly submissions. This should only apply for new submissions.
N/A
N/A

Hotfix: "is_quarter_format" should only overwrite for new submissions

---

requirements.txt

The `marshmallow` package included in `webargs` has been updated and breaking travis builds. This specifies an older compatible version to mend that. 
(see high level)
N/A

Hotfix: Compatible Marshmallow Version 

---

dataactcore/scripts/load_federal_hierarchy.py

For the federal hierarchy load, cut it down from ten requests at a time to five to lighten the load.
(see above)
N/A

Master Hotfix: Limit Federal Hierarchy Requests

---

dataactcore/scripts/raw_sql/link_broken_subaward_contracts.sql
dataactcore/scripts/raw_sql/link_broken_subaward_grants.sql
dataactcore/scripts/raw_sql/populate_subaward_table_contracts.sql
dataactcore/scripts/raw_sql/populate_subaward_table_grants.sql
tests/unit/dataactcore/test_populate_subaward_table.py

Reworking subaward populators/linkers to ignore dashes in the award id and parent award id. 
(see above)
[DEV-3322](https://federal-spending-transparency.atlassian.net/browse/DEV-3322)

DEV-3322: Subaward->Award linking dashes

---

dataactcore/scripts/derive_historical_transaction_exec_comp.py

Updating historic exec comp transaction script to support working directly with the Historic DUNS table.
N/A
[DEV-3285](https://federal-spending-transparency.atlassian.net/browse/DEV-3285)

DEV-3285: Update Historic Exec Comp Transactions

---

dataactbroker/handlers/fileHandler.py

Simply adding a couple of logs to submissions (more than 100 rows) in chunks of 10% (or closest to) so that we can check the status of publishing FABS submissions.
- Can adjust the percentage and minimum number of rows easily. 
[DEV-3372](https://federal-spending-transparency.atlassian.net/browse/DEV-3372)

DEV-3372: FABS Publishing Progress Logs

---

dataactvalidator/validation_handlers/validationManager.py
dataactvalidator/validation_handlers/validator.py

Adding expected value to other errors (length, type, required)
N/A
[DEV-3644](https://federal-spending-transparency.atlassian.net/browse/DEV-3644)

DEV-3644: expected value other

---

dataactvalidator/config/sqlrules/a12_appropriations.sql
dataactvalidator/validation_handlers/validationManager.py
dataactvalidator/validation_handlers/validator.py
tests/unit/dataactvalidator/test_a12_appropriations.py
tests/unit/dataactvalidator/validation_handlers/test_validationManager.py

Setting up infrastructure to get variance from SQL rules where it exists
Also added variance to one of the rules for testing/validation purposes
[DEV-3510](https://federal-spending-transparency.atlassian.net/browse/DEV-3510)

DEV-3510: variance infrastructure

---

dataactbroker/permissions.md

Adding further detail on the actions that are permitted or denied at various permission levels
Grouping actions by permission level
TBD
- [NA] Backend review completed
- [NA ] Merged concurrently with [Frontend#1234](https://github.com/fedspendingtransparency/data-act-broker-web-app/pull/1234)
- [NA] Unit & integration tests updated with relevant test cases
- [NA] Frontend impact assessment completed

Broker detailed permissions

---

dataactbroker/README.md
dataactbroker/app.py
dataactbroker/handlers/dashboard_handler.py
dataactbroker/handlers/fileHandler.py
dataactbroker/helpers/filters_helper.py
dataactbroker/routes/dashboard_routes.py
tests/unit/dataactbroker/test_dashboard_handler.py
tests/unit/dataactbroker/test_delete_user.py
tests/unit/dataactbroker/test_file_handler.py
tests/unit/dataactbroker/test_filter_helper.py

Endpoint listing the submission summaries based on the filters provided.
- Contract can be found in the ticket
[DEV-3669](https://federal-spending-transparency.atlassian.net/browse/DEV-3669)

DEV-3669: Dashboard Summary Endpoint

---

dataactbroker/README.md
dataactbroker/handlers/submission_handler.py
dataactbroker/routes/file_routes.py
tests/unit/dataactbroker/test_submission_handler.py

Endpoint to provide frontend with the latest certification period endpoint based on the time of hitting the endpoint.
Contract:
```
GET /v1/latest_certification_period/
Response:
{
"quarter": 4,
"year": 2019
}
(both return null if for some reason there is no latest quarter to work from)
```
[DEV-3699](https://federal-spending-transparency.atlassian.net/browse/DEV-3699)

DEV-3699: Latest Certification Period endpoint

---

dataactvalidator/config/sqlrules/b14_object_class_program_activity.sql
dataactvalidator/config/sqlrules/b15_object_class_program_activity.sql
dataactvalidator/config/sqlrules/b9_object_class_program_activity.sql
dataactvalidator/config/sqlrules/c20_award_financial.sql
dataactvalidator/config/sqlrules/c21_award_financial.sql

Displaying the display TAS in SQL results instead of the Broker TAS
N/A
[DEV-3859](https://federal-spending-transparency.atlassian.net/browse/DEV-3859)

DEV-3859: Always use display tas

---

dataactvalidator/validation_handlers/validationManager.py
tests/integration/error_warning_file_tests.py

Making the column headers singular in error/warning files
N/A
[DEV-3847](https://federal-spending-transparency.atlassian.net/browse/DEV-3847)

DEV-3847: singular column names

---

dataactbroker/README.md
dataactbroker/handlers/dashboard_handler.py
tests/integration/dashboard_tests.py
tests/unit/dataactbroker/test_dashboard_handler.py

Updating the Dashboard Summary endpoint to group by Agency name to list agencies with 0 submissions.
N/A
[DEV-3363](https://federal-spending-transparency.atlassian.net/browse/DEV-3363)

DEV-3363: Dashboard Summary Endpoint Update

---

dataactbroker/handlers/dashboard_handler.py

A minor ordering bug was discovered on the dashboard page in staging. By ordering the rules in this endpoint, it should resolve it. 
N/A
N/A

Warmfix: Order Warnings in Dashboard Graphs Endpoint

---

dataactbroker/handlers/dashboard_handler.py

Ordering the dashboard summary results so they are consistent. 
Ordering by submission's reporting period end date (both the reporting period and year are based on that)
[DEV-4040](https://federal-spending-transparency.atlassian.net/browse/DEV-4040)

DEV-4040: Dashboard Summary sort by Reporting Period

---

dataactbroker/handlers/fileHandler.py
dataactvalidator/validation_handlers/file_generation_manager.py

Adding start and end date to file D names
N/A
[DEV-3913](https://federal-spending-transparency.atlassian.net/browse/DEV-3913)

DEV-3913: D file name date range

---

dataactvalidator/scripts/read_zips.py

Fixing the zip code loader
Updating the zip code loader to not create the string None
[DEV-3583](https://federal-spending-transparency.atlassian.net/browse/DEV-3583)

DEV-3583: fabs congressional district none

---

dataactbroker/README.md
dataactbroker/routes/file_routes.py

Removing narrative endpoints that are no longer in use
N/A
[DEV-3368](https://federal-spending-transparency.atlassian.net/browse/DEV-3368)

DEV-3368: Remove narrative-endpoints

---

dataactcore/scripts/get_fsrs_updates.py

Leave record type 1 out of the data we sent to FSRS
Just filter the record type 1 records out of the entire process in the SQL
[DEV-4081](https://federal-spending-transparency.atlassian.net/browse/DEV-4081)

DEV-4081: No fsrs aggregate records sent

---

dataactbroker/README.md
dataactbroker/app.py
dataactbroker/routes/file_routes.py

Making the trailing slashes in all endpoints optional, so they work with or without them.
- Simply setting all url mappings to have `strict_slashes` to false
- Also updating the endpoints and documentation to be consistent and always show the trailing slashes, but to also note that it will work with or without them.
[DEV-1790](https://federal-spending-transparency.atlassian.net/browse/DEV-1790)

DEV-1790: Optional trailing slashes in endpoints

---

dataactcore/scripts/backfill_ppop_scope_fabs.py

Simple SQL script to backfill PPOP scope in the FABS table.
Script takes about 5 hours with the following counts on sandbox:
City-wide: 78059
County-wide: 4426463
Foreign: 229444
Multi-State: 14662
Single Zip Code: 2545890
State-wide: 275558
(blank): 38614734
[DEV-4084](https://federal-spending-transparency.atlassian.net/browse/DEV-4084)

DEV-4084: Backfill FABS PPOP scope

---

dataactbroker/helpers/fabs_derivations_helper.py
tests/unit/dataactbroker/test_fabs_derivations.py

Updating PPOP Scope derivation to be case-insensitive.
N/A
[DEV-1720](https://federal-spending-transparency.atlassian.net/browse/DEV-1720)

DEV-1720 Update: PPOP Scope derivation is case-insensitive

---

requirements.txt

Updating waitress version in advance of removing it completely
This will eventually be removed completely but in the interim we're updating it to the latest version and keeping an eye on it.
[OPS-1027](https://federal-spending-transparency.atlassian.net/browse/OPS-1027)

OPS-1027: Waitress upgrade

---

dataactbroker/handlers/fileHandler.py

Adding uploading logs for DABS/FABS submission files
N/A
[DEV-4128](https://federal-spending-transparency.atlassian.net/browse/DEV-4128)

DEV-4128: Basic logs for uploading submission files

---

dataactcore/migrations/versions/3fd9a578c9c5_add_unique_award_key_to_.py

Making alembic play nice
Updating the down migration
N/A

Changing the down revision on the new migration

---

dataactbroker/README.md
dataactbroker/handlers/fileHandler.py
dataactcore/interfaces/function_bag.py
tests/unit/dataactbroker/test_file_handler.py
tests/unit/dataactcore/factories/job.py
tests/unit/dataactcore/test_function_bag.py

Adding a couple data points and sorts for `list_submissions` which will be used by the Active DABS Dashboard pages.
Added:
* `quarterly_submission` - whether it's a quarterly submission or not
* `window_end` - provides the end of the submission window
* `time_period` - the string time period for that submission
New Sorts:
* `submission_id`
* `quarterly_submission`
Added helper functions to be used with submissions
* `get_time_period` - string of the submissions time period
* `get_window_end` - whether the submission is passed it's window end or not
[DEV-4411](https://federal-spending-transparency.atlassian.net/browse/DEV-4411)

DEV-4411: list_submisisons updates

---

dataactbroker/handlers/account_handler.py

Updating the url being sent with the email
The link we were using was outdated after the url was restructured.
N/A

Fix: Email link

---

dataactbroker/README.md
dataactbroker/handlers/account_handler.py
tests/unit/dataactbroker/test_user_routes.py

Applying #1786 to staging as a warmfix.
(see #1786)
[DEV-4505](https://federal-spending-transparency.atlassian.net/browse/DEV-4505)

DEV-4505: Email list_submissions (warmfix)

---

dataactbroker/handlers/fileHandler.py
tests/integration/fileTests.py

Allow creation of submissions in quarters with certified submissions
Stop the check preventing creation of submissions in quarters with certified submissions
[DEV-3801](https://federal-spending-transparency.atlassian.net/browse/DEV-3801)

DEV-3801: allow new submissions certified quarter

---

dataactbroker/helpers/validation_helper.py
dataactvalidator/validation_handlers/validationManager.py

Double checking the delimiter before reading in the file.
N/A
[DEV-4622](https://federal-spending-transparency.atlassian.net/browse/DEV-4622)
[DEV-4623](https://federal-spending-transparency.atlassian.net/browse/DEV-4623)

Hotfix: DEV-4622 DEV-4623 Data Ingest Pipe Counts, D1/D2 Generation

---

dataactbroker/handlers/submission_handler.py
tests/unit/dataactbroker/test_submission_handler.py

Sending the ID of the certified submission rather than just indicating whether there is one or not
Note: README updates are already in another ticket so those will remain there to simplify things
[DEV-4617](https://federal-spending-transparency.atlassian.net/browse/DEV-4617)

DEV-4617: submission metadata update

---

dataactbroker/handlers/fileHandler.py

Fixing the file reversion
Mistyped the column name in a query
N/A

Warmfix revert to certified

---

dataactbroker/handlers/submission_handler.py
tests/unit/dataactbroker/test_submission_handler.py

Fixing publishable flag bug discovered during demo prep
Need to set publishable flag to True when reverting
N/A

Warmfix revert certify

---

requirements.txt

Upgrading psutil for security purposes.
N/A
[DEV-4701](https://federal-spending-transparency.atlassian.net/browse/DEV-4701)

DEV-4701: Upgrading psutil

---

APISubmissionGuide.md

Fixing links to check generation status
All other links work.
N/A

API Submission Guide

---

dataactbroker/README.md
dataactbroker/routes/user_routes.py
tests/integration/userTests.py

Removing `email_users` endpoint until it has been fixed.
N/A
[DEV-4812](https://federal-spending-transparency.atlassian.net/browse/DEV-4812)

Warmfix: Removing 'email_users" endpoint until fixed

---

dataactcore/scripts/raw_sql/fileF.sql
tests/unit/dataactcore/test_fileF.py

Adding 3 new columns to file F
N/A
[DEV-4945](https://federal-spending-transparency.atlassian.net/browse/DEV-4945)

DEV-4945: File F updates

---

dataactbroker/helpers/validation_helper.py
dataactvalidator/validation_handlers/validationManager.py
tests/integration/error_warning_file_tests.py
tests/unit/dataactbroker/test_validation_helper.py

Simply renaming the column "Error Message" to "Rule Message" for error and warning reports.
N/A
[DEV-4684](https://federal-spending-transparency.atlassian.net/browse/DEV-4684)

DEV-4684: "Error Message" -> "Rule Message" EW reports

---

dataactbroker/README.md
dataactcore/models/lookups.py
dataactcore/utils/report.py
tests/unit/dataactbroker/test_file_handler.py

Simply including the File letters to the error warning reports
N/A
[DEV-4683](https://federal-spending-transparency.atlassian.net/browse/DEV-4683)

DEV-4683: Updating error/warning filesnames per DAIMS 2.0

---

dataactbroker/README.md
dataactbroker/handlers/fileHandler.py
dataactbroker/handlers/submission_handler.py
dataactbroker/routes/file_routes.py
dataactcore/interfaces/function_bag.py
tests/integration/list_submission_tests.py
tests/unit/dataactbroker/test_file_handler.py

Updating `list_submission` in two ways:
* renaming the param `certified` to `published` to be more accurate
* updating the submission status to include new states for accuracy
* updated
* published
N/A
[DEV-5315](https://federal-spending-transparency.atlassian.net/browse/DEV-5315)

DEV-5315: Update Submission Table

---

dataactvalidator/config/sqlrules/b22_object_class_program_activity.sql
tests/unit/dataactvalidator/test_b22_object_class_program_activity.py

Updating B22 to sum everything with the same TAS/DEFC combo in file B
N/A
[DEV-5533](https://federal-spending-transparency.atlassian.net/browse/DEV-5533)

DEV-5533: B22 fix

---

requirements.txt

Updating DataDog client libraries to fix a known bug in tracing forked processes
we are tracking [this](https://github.com/DataDog/dd-trace-py/issues/1184) issue with DataDog client: forked process traces are not being captured properly in our currently used version. A workaround noted in the ticket above is available in the LTS release of the client.
[OPS-1272](https://federal-spending-transparency.atlassian.net/browse/OPS-1272)
- [N/A] Merged concurrently with frontend
- [N/A] Unit & integration tests updated with relevant test cases
- [N/A] Frontend impact assessment completed
- [N/A] Documentation Updated
**Area for explaining above N/A when needed:** …

updating datadog trace client

---

dataactcore/config_example.yml
dataactcore/local_config_example.yml
dataactvalidator/validation_handlers/validationManager.py

Applying the changes in #1917 to qat

Warmfix: Validator batch size update qat

---

dataactbroker/helpers/validation_helper.py
dataactcore/models/domainModels.py
dataactvalidator/config/sqlrules/c8_award_financial.sql
dataactvalidator/config/sqlrules/c9_award_financial.sql
dataactvalidator/filestreaming/fieldCleaner.py
dataactvalidator/scripts/loader_utils.py
dataactvalidator/validation_handlers/validationManager.py
docker-compose.frontend.yml
requirements.txt
tests/unit/dataactbroker/test_validation_helper.py

Addressing bottlenecks in ingest and processing of (very large) CSV files using Pandas data processing framework. Swapping use of code doing element-wise function calls (on each cell) with vectorized calls across column Series to reduce processing time.
Pandas is meant to be used to best effect when vectorizing functions across Series. Pandas DataFrames can be thought of as a matrix of Series, which are just numpy arrays, as rows/columns. As numpy arrays, you can apply a function in a vectored way to have it take effect on the whole array at once, rather than iterating cells in that Series/array.
We seemed to be following a pattern of applying validation functions element-wise. Handing a function to pandas that we then apply row by row, …

[HOTFIX][DEV-5600] Optimize CSV data processing with vectorized use of Pandas

---

dataactcore/models/domainModels.py
dataactvalidator/validation_handlers/validationManager.py

Alisa and I discovered some SQL improvements when linking TASs after loading files. The performance should be at least 75% faster.
N/A
N/A

[HOTFIX] Fixing Linking TAS Performance (preemptively merged into #1922 already)

---

dataactbroker/handlers/submission_handler.py
dataactvalidator/filestreaming/csv_selection.py

* Updated reporting start/end dates in metadata endpoint to not break FABS
* Updated stream_file_to_s3 to use `upload_file` for optimization
N/A
N/A

Warmfixes: Write Stream Query Upload and FABS Metadata

---

dataactvalidator/validation_handlers/validationManager.py

Fixing cross-file updating
N/A

Updating crossfile uploading

---

dataactbroker/README.md
dataactbroker/handlers/fileHandler.py
dataactbroker/handlers/submission_handler.py
tests/unit/dataactbroker/test_file_handler.py

Include the removal of S3 files when deleting a submission (submission files + e/w files)
N/A
[DEV-5949](https://federal-spending-transparency.atlassian.net/browse/DEV-5949)

DEV-5949: Delete Submission Files

---

dataactbroker/handlers/submission_handler.py
dataactcore/scripts/delete_orphaned_s3_files.py

Creating a script to delete orphaned submission files.
The script compares all folder numbers in the environment's submission bucket and deletes any that aren't in the database anymore
[DEV-5992](https://federal-spending-transparency.atlassian.net/browse/DEV-5992)

DEV-5992: delete orphaned files

---

dataactcore/aws/s3Handler.py

The download urls generated turned out to be reformatted due to a package update. This resolves that.
N/A
N/A
-  Unit & integration tests updated with relevant test cases

Addressing new signed url format with boto/botocore

---

dataactvalidator/scripts/load_program_activity.py
tests/unit/dataactvalidator/test_load_program_activity.py

Fixing a minor bug with the program activity loader
N/A
N/A

Fixing program acitivty loader for Python3.7

---

dataactvalidator/scripts/load_program_activity.py

* Creating a metrics file when skipped (to not prevent the job from failing)
* Adding more logs for visibility
N/A
N/A

Program activity logs and skipped file success

---

dataactcore/utils/fileA.py
dataactvalidator/config/sqlrules/a12_appropriations.sql
dataactvalidator/config/sqlrules/sqlRules.csv
tests/unit/dataactvalidator/test_a12_appropriations.py
tests/unit/dataactvalidator/validation_handlers/test_file_generation_manager.py

Update which GTAS lines are checked for AdjustmentsToUnobligatedBalanceBroughtForward starting FY21
Prior to FY21, lines 1010-1042 should be checked. Starting FY21, lines 1010-1065 should be checked.
[DEV-6478](https://federal-spending-transparency.atlassian.net/browse/DEV-6478)

DEV-6478: update adjustmentstounobligatedbalance calculation

---

dataactcore/scripts/load_federal_hierarchy.py

The Federal Hierarchy Job has been failing intermittently (once every two-three weeks). This resolves the most common issue (retrying the request for the total records) while updating the exception handling to be more specific to the issue. 
N/A
N/A

Federal Hierarchy Fixes

---

dataactbroker/handlers/fileHandler.py

Fixing some check_status logic
Adding some comments for logic explanation and adding a check for if the validation hasn't started but upload has finished (should be considered "running")
[DEV-4418](https://federal-spending-transparency.atlassian.net/browse/DEV-4418)

DEV-4418: check status logic update

---

dataactbroker/handlers/fileHandler.py
tests/unit/dataactbroker/test_file_handler.py

Adding Submission Comments to comment files 
N/A
[DEV-6630](https://federal-spending-transparency.atlassian.net/browse/DEV-6630)

DEV-6630: Submission Comment in comment file

---

dataactcore/scripts/load_federal_hierarchy.py

The Federal Hierarchy fails from time to time due to networking or an invalid response from SAM. This handles those hiccups the same and retries them instead of failing outright.
N/A
N/A

Federal Hierarchy Retries

---

dataactvalidator/config/def_codes.csv

(see title)
(see title)
[DEV-6601](https://federal-spending-transparency.atlassian.net/browse/DEV-6601)

DEV-6601: Updating local DEFC file to add R to COVID-19 list

---

dataactvalidator/config/sqlrules/c25_award_financial.sql
tests/unit/dataactvalidator/test_c25_award_financial.py

Allowing 0 to count as populated for TOA
N/A
[DEV-6583](https://federal-spending-transparency.atlassian.net/browse/DEV-6583)

DEV-6583: c25 null toa only

---

dataactvalidator/config/sqlrules/a12_appropriations.sql
dataactvalidator/config/sqlrules/sqlRules.csv
tests/unit/dataactvalidator/test_a12_appropriations.py

Updating the A12 rule text to account for both time periods.
(see title)
[DEV-6701](https://federal-spending-transparency.atlassian.net/browse/DEV-6701)

DEV-6701: Updating A12 Text

---

dataactbroker/handlers/fileHandler.py

Automatically set FY22+ quarterly submissions to `test`
N/A
[DEV-6733](https://federal-spending-transparency.atlassian.net/browse/DEV-6733)

DEV-6733: auto set quarterly fy22 test

---

dataactvalidator/README.md

Simply updating the documentation to reflect the recent changes to the data loading and validation process.
N/A
N/A

Documentation Update: Validation Workflow Updates

---

dataactvalidator/config/def_codes.csv

(see title)
(see title)
[DEV-6826](https://federal-spending-transparency.atlassian.net/browse/DEV-6826)

DEV-6826:Adding DEFC U and removing R from COVID list locally

---

APISubmissionGuide.md
dataactbroker/routes/file_routes.py
doc/api_docs/file/get_certified_file.md
doc/api_docs/file/get_fabs_meta.md
doc/api_docs/file/report_url.md

Removing endpoints that have been deprecated for a while
N/A
[DEV-6257](https://federal-spending-transparency.atlassian.net/browse/DEV-6257)

DEV-6257: Remove deprecated endpoints

---

dataactbroker/handlers/fileHandler.py

Adding in handling to trim away extra spaces and not insert an empty string
N/A
[DEV-4518](https://federal-spending-transparency.atlassian.net/browse/DEV-4518)

DEV-4518: Trim incoming cgac frec

---

dataactbroker/fsrs.py

Simply strip the incoming strings from FSRS data 
N/A
[DEV-6828](https://federal-spending-transparency.atlassian.net/browse/DEV-6828)

DEV-6828: Trimmed incoming FSRS data

---

dataactvalidator/scripts/load_agencies.py

Updating the abbreviations in FREC agencies to be the FREC abbreviation
N/A
[DEV-7005](https://federal-spending-transparency.atlassian.net/browse/DEV-7005)

DEV-7005: Frec agency abbreviations

---

APISubmissionGuide.md
doc/README.md

Adding a note in the README to tell users what the base URL is. Also linking to the README in the API Submission guide.
N/A
[DEV-1697](https://federal-spending-transparency.atlassian.net/browse/DEV-1697)

DEV-1697: API doc url

---

dataactvalidator/config/def_codes.csv

Simply updating the local def_codes.csv from nonprod and prod buckets which will add 'V' to the DEFC list.
N/A
[DEV-7021](https://federal-spending-transparency.atlassian.net/browse/DEV-7021)

DEV-7021: Adding DEFC V

---

requirements.txt

* Removing a couple redundant packages from a security notice (pasn1, rsa)
* Updating Jinja2 for a security notice
* Updating Werkzeug to resolve an issue with Docker
N/A
N/A

Minor Package Updates (security, docker)

---

dataactbroker/handlers/fileHandler.py

Adding a small check to prevent users from starting a full revalidation while the submission is already uploading/validating a file. 
N/A
[DEV-3639](https://federal-spending-transparency.atlassian.net/browse/DEV-3639)

DEV-3639: FABS Publishing Duplicates

---

dataactcore/interfaces/function_bag.py
doc/api_docs/file/submission_data.md
tests/integration/fileTests.py

Making occurrences in submission_data an integer because that's logical
N/A
[DEV-4421](https://federal-spending-transparency.atlassian.net/browse/DEV-4421)

DEV-4421: Occurrences sort

---

dataactvalidator/config/sqlrules/c27_award_financial.sql
tests/unit/dataactvalidator/test_c27_award_financial.py

Ignore DEFC 9 in prior period/quarter for C27 (still check all the other fields)
N/A
[DEV-7256](https://federal-spending-transparency.atlassian.net/browse/DEV-7256)

DEV-7256: c27 ignore defc 9

---

dataactvalidator/config/sqlrules/c11_cross_file.sql
dataactvalidator/config/sqlrules/c12_cross_file.sql
dataactvalidator/config/sqlrules/c8_award_financial.sql
dataactvalidator/config/sqlrules/c9_award_financial.sql
tests/unit/dataactvalidator/test_c11_cross_file.py
tests/unit/dataactvalidator/test_c12_cross_file.py
tests/unit/dataactvalidator/test_c8_award_financial.py
tests/unit/dataactvalidator/test_c9_award_financial.py

Adding obligation amount to source values and difference columns in C8, C9, C11, and C12
N/A
[DEV-6001](https://federal-spending-transparency.atlassian.net/browse/DEV-6001)

DEV-6001: c8 c9 c11 c12 obligation amount

---

dataactcore/scripts/pull_fpds_data.py

Simply don't expect entries for the initial counts.
N/A
N/A

Warmfix: FPDS Empty Initial Counts

---

dataactcore/scripts/pull_fpds_data.py
tests/unit/data/fpdsXML.txt

Updating FPDS script to use template v1.5.2 and pull in UEI data
N/A
[DEV-7119](https://federal-spending-transparency.atlassian.net/browse/DEV-7119)

DEV-7119: fpds loader v1.5.2

---

dataactvalidator/config/sqlrules/a33_appropriations_1.sql

Hotfix: Only use FREC list if its a CGAC sub (A33)

---

dataactvalidator/config/sqlrules/a33_appropriations_1.sql

Hotfix: A33 ATA check for both AID filters

---

dataactbroker/handlers/dashboard_handler.py
doc/api_docs/dashboard/historic_dabs_graphs.md
tests/unit/dataactbroker/test_dashboard_handler.py

Updating the backend to return necessary information for the period/quarter bars and the updated tooltip information
N/A
[DEV-7299](https://federal-spending-transparency.atlassian.net/browse/DEV-7299)

DEV-7299: historic dashboard graph endpoint

---

dataactvalidator/scripts/load_object_class.py

Simply updating the object class loader to use the public shared file with USAS.
N/A
[DEV-7511](https://federal-spending-transparency.atlassian.net/browse/DEV-7511)

DEV-7511: Object Class Loader Shared File Update

---

dataactbroker/handlers/fileHandler.py
dataactbroker/routes/file_routes.py
doc/api_docs/file/get_submitted_published_file.md
doc/api_docs/file/list_latest_published_files.md
tests/integration/fileTests.py
tests/integration/integration_test_helper.py
tests/integration/list_latest_published_files_tests.py
tests/unit/dataactbroker/test_file_handler.py

Endpoints that will be used for the Raw Submissions Page.
* Doesn't include Assurance Statements
[DEV-7836](https://federal-spending-transparency.atlassian.net/browse/DEV-7836)

DEV-7836: View Published Files Endpoints

---

dataactvalidator/config/sqlrules/fabs31_detached_award_financial_assistance_5.sql
dataactvalidator/config/sqlrules/fabs31_detached_award_financial_assistance_7.sql

Updating the FABS31.5/FABS31.7 rules for performance
Changing the CASE statement in the EXISTS to a UNION of the two cases.
N/A

FIX: FABS31 performance

---

dataactbroker/handlers/fileHandler.py
doc/api_docs/file/check_status.md
tests/unit/dataactbroker/test_file_handler.py

Splitting the `progress` value into 2 values in `check_status`
New values:
- `upload_progress`
- `validation_progress`
[DEV-8119](https://federal-spending-transparency.atlassian.net/browse/DEV-8119)

DEV-8119: split check status progress

---

dataactvalidator/config/sqlrules/c18_award_financial.sql
tests/unit/dataactvalidator/test_c18_award_financial.py

Only trigger C18 when all elements are present
N/A
[DEV-8162](https://federal-spending-transparency.atlassian.net/browse/DEV-8162)

DEV-8162: C18 trigger all values

---

dataactvalidator/scripts/load_tas.py
tests/unit/dataactvalidator/test_scripts_loadTas.py

Updating the TAS loader to update TAS/Display Tas values when updating records.
N/A
[DEV-8222](https://federal-spending-transparency.atlassian.net/browse/DEV-8222)

DEV-8222: TAS Loader Updates Fix

---

dataactvalidator/scripts/load_program_activity.py

Turning load_program_activity into a script and supports exports and force loads.
N/A
[DEV-8161](https://federal-spending-transparency.atlassian.net/browse/DEV-8161)

DEV-8161: Program Activity Export

---

dataactvalidator/validation_handlers/errorInterface.py

Adding original rule label to error row dict for uniquness and preventing error rule metadata being merged.
N/A
N/A

Fix: Merging Rule Labels for specific rules

---

dataactcore/scripts/get_fsrs_updates.py

Adding a comment that summarizes the SQL query that generates the FSRS Extract.
N/A
[DEV-8244](https://federal-spending-transparency.atlassian.net/browse/DEV-8244)

DEV-8244: FSRS Extract Description

---

dataactvalidator/config/sqlrules/a2_appropriations.sql
tests/integration/error_warning_file_tests.py
tests/unit/dataactvalidator/test_a2_appropriations.py

Updating A2 after updating SF133 with DEFCs.
* Added SF133 total to difference
* Added SF133 total to expected values
* Grouped SF133 total by TAS
[DEV-8398](https://federal-spending-transparency.atlassian.net/browse/DEV-8398)

DEV-8398: A2 group by TAS update (Prod)

---

dataactbroker/handlers/fileHandler.py
dataactbroker/handlers/submission_handler.py
dataactbroker/helpers/generation_helper.py
doc/api_docs/file/check_status.md
doc/api_docs/file/submission_data.md
doc/api_docs/generation/check_detached_generation_status.md
doc/api_docs/generation/check_generation_status.md
tests/unit/dataactbroker/test_file_handler.py
tests/unit/dataactbroker/test_submission_handler.py

Sending the last validated date for cross file and submission data
N/A
[DEV-6122](https://federal-spending-transparency.atlassian.net/browse/DEV-6122)

DEV-6122: last validated dabs timestamps

---

pull_request_template.md

Adding this check to PR template to remind the author and save on the review. 
N/A
N/A

Adding "Style Guide Check" to PR Template

---

dataactvalidator/config/fabsFields.csv
dataactvalidator/config/fabsFieldsRaw.csv
dataactvalidator/validation_handlers/validationManager.py

Removing the DUNS requirement from FABS files and ignoring it when it's submitted
N/A
[DEV-7470](https://federal-spending-transparency.atlassian.net/browse/DEV-7470)

DEV-7470: remove duns fabs file

---

dataactvalidator/scripts/load_sf133.py
dataactvalidator/validation_handlers/validationManager.py

Converting all QQQ DEFCs to Q before they hit the database
This applies to files B/C and to SF133
[DEV-8444](https://federal-spending-transparency.atlassian.net/browse/DEV-8444)

DEV-8444: unify q qqq defc

---

dataactbroker/handlers/submission_handler.py
doc/api_docs/file/latest_publication_period.md

Adding the deadline for the latest publication period for frontend's use
N/A
[DEV-8396](https://federal-spending-transparency.atlassian.net/browse/DEV-8396)

DEV-8396: default dabs period

---

dataactbroker/handlers/fileHandler.py
doc/api_docs/file/update_submission_comments.md
tests/unit/dataactbroker/test_file_handler.py

Blocking comment updates when a submission is reverting/publishing
N/A
[DEV-8495](https://federal-spending-transparency.atlassian.net/browse/DEV-8495)

DEV-8495: Prevent comments during publish

---

dataactcore/scripts/pull_fpds_data.py

Change where we're pulling the ultimate parent legal entity name from
N/A
[DEV-8655](https://federal-spending-transparency.atlassian.net/browse/DEV-8655)

DEV-8655: Parent legal entity fpds

---

dataactcore/utils/fileA.py
dataactvalidator/config/sqlrules/a33_appropriations_1.sql

Make sure A33.1 is properly checking all the groupings we added
Add all the new groupings from file A generation to rule A33.1
[DEV-8637](https://federal-spending-transparency.atlassian.net/browse/DEV-8637)

DEV-8637: file a groupings

---

dataactcore/models/lookups.py
dataactcore/scripts/initialize.py
dataactvalidator/scripts/load_defc.py

Adding defc to the external data types
Only loading DEFC when there are changes
[DEV-8715](https://federal-spending-transparency.atlassian.net/browse/DEV-8715)

DEV-8715: Data sources defc load

---

dataactcore/utils/fileA.py
dataactvalidator/config/sqlrules/a12_appropriations.sql
dataactvalidator/config/sqlrules/sqlRules.csv
tests/unit/dataactvalidator/test_a12_appropriations.py
tests/unit/dataactvalidator/validation_handlers/test_file_generation_manager.py

Replacing line 1065 with 1066 in all file A generation/comparison instances
N/A
[DEV-8810](https://federal-spending-transparency.atlassian.net/browse/DEV-8810)

DEV-8810: line 1066 a12

---

dataactvalidator/scripts/load_tas_failing_edits.py
dataactvalidator/scripts/loader_utils.py

Updating how we clean the headers so we don't break other scripts
N/A
N/A

Loader clean data hotfix

---

dataactvalidator/scripts/load_sf133.py

Combining any duplicate rows in the SF133 file, including ones created by converting QQQ into Q
De-duping by grouping by a unique key
[DEV-8917](https://federal-spending-transparency.atlassian.net/browse/DEV-8917)

DEV-8917: SF133 loader q split

---

dataactvalidator/config/sqlrules/fabs31_2_2.sql
tests/unit/dataactvalidator/test_fabs31_2_2.py

Updating the date in FABS31.2.2 to be far in the future
N/A
[DEV-9056](https://federal-spending-transparency.atlassian.net/browse/DEV-9056)

DEV-9056: fabs31.2 deadline update

---

dataactvalidator/config/sqlrules/fabs31_2_1.sql
dataactvalidator/config/sqlrules/fabs31_2_2.sql
tests/unit/dataactvalidator/test_fabs31_2_1.py
tests/unit/dataactvalidator/test_fabs31_2_2.py

Updating FABS31.2.1 to have the same date limitations as FABS31.2.2
N/A
[DEV-9137](https://federal-spending-transparency.atlassian.net/browse/DEV-9137)

DEV-9137: FABS31 date updates

---

dataactvalidator/config/sqlrules/b21_object_class_program_activity.sql

Speeding up B21
N/A
[DEV-9164](https://federal-spending-transparency.atlassian.net/browse/DEV-9164)

DEV-9164: B21 speedup

---

dataactcore/utils/fileA.py
tests/unit/dataactcore/factories/domain.py
tests/unit/dataactvalidator/validation_handlers/test_file_generation_manager.py

Adding the certification status of each TAS into the generated file A
Rules for what the status is are in the related ticket. This is not stored in the file A staging table, only in the generated file A for reference purposes
[DEV-9078](https://federal-spending-transparency.atlassian.net/browse/DEV-9078)

DEV-9078: New file a column cert status

---

dataactbroker/helpers/fabs_derivations_helper.py
doc/fabs_derivations.md
doc/zips_historical.md

Adding documentation about zips_historical

Documenting zips_historical

---

dataactcore/scripts/pull_fpds_data.py

FPDS feed version 1.5.2 has been decommissioned and 1.5.3 needs to be used instead.
N/A
N/A

Fix: Update FPDS feed version

---

server_requirements.txt

Upgrade supervisor version because of our updated python version
The technical details can be placed here for the knowledge of other developers. Any detailed caveats or specific deployment steps should be outlined here.

update supervisor package

---

dataactvalidator/scripts/read_zips.py

Fix: cd_zips_historical fix

---

dataactcore/migrations/versions/48fbbea5de34_updating_several_ids_to_be_bigints.py
dataactcore/models/domainModels.py

Remove program_activity from the bigint migration
N/A
N/A

Remove program_activity from the bigint migration

---

dataactvalidator/scripts/load_location_data.py

Updating location loader to account for new file formats and names
N/A
[DEV-9767](https://federal-spending-transparency.atlassian.net/browse/DEV-9767)

DEV-9767: Update city county location source

---

dataactbroker/handlers/account_handler.py

Accounting for lack of middle names and "role:" prefixes in roles.
N/A
[DEV-10131](https://federal-spending-transparency.atlassian.net/browse/DEV-10131)

DEV-10131: Middle Name and "role:"s for CAIA

---

Dockerfile

High level description of what the PR addresses should be put here. Should be detailed enough to communicate to the client what this PR addresses without diving into the technical nuances.
The technical details can be placed here for the knowledge of other developers. Any detailed caveats or specific deployment steps should be outlined here.

update python version and setuptools

---

APISubmissionGuide.md
doc/api_docs/file/upload_dabs_files.md

Updating documentation for file A generation
N/A
[DEV-10266](https://federal-spending-transparency.atlassian.net/browse/DEV-10266)

DEV-10266: api submission guide update

---

dataactcore/scripts/setup/load_funding_opportunity_number.py

Updating request path
N/A
[DEV-10337](https://federal-spending-transparency.atlassian.net/browse/DEV-10337)

DEV-10337: FON loader fix

---

dataactbroker/helpers/pandas_helper.py
dataactbroker/helpers/script_helper.py
dataactcore/scripts/initialize.py
dataactcore/scripts/pipeline/pull_fpds_data.py
dataactcore/scripts/setup/load_country_codes.py
dataactcore/scripts/setup/read_zips.py

Updating country code loader to gather data from an API rather than a manually created CSV.
Using the API to scrape the data and then create the CSV from that data rather than gathering from a manually created CSV.
[DEV-9954](https://federal-spending-transparency.atlassian.net/browse/DEV-9954)

DEV-9954: country code loader

---

dataactcore/scripts/setup/setup_emails.py

Upon deploying QAT, there was an issue with the deploying initialize command that needs this fix.

Setup Emails Fix

---

dataactvalidator/app.py
dataactvalidator/validation_handlers/validationManager.py

The issue that spawned the ticket was not necessarily related to the file per se but rather how the validator reacts to the errant file. With the various changes to the validator dispatcher logic and the code to clean up child processes, the error stemmed from trying to kill child processes that no longer existed. This fix includes double checking the child process is running before killing it.
N/A
[DEV-10361](https://federal-spending-transparency.atlassian.net/browse/DEV-10361)

DEV-10361: Validator Child Process Fix

---

dataactcore/scripts/setup/read_zips.py

Simply adding headers to the congressional districts export.
N/A
[DEV-10507](https://federal-spending-transparency.atlassian.net/browse/DEV-10507)

DEV-10507: Adding Congressional District Headers

---

dataactcore/scripts/pipeline/get_fsrs_updates.py
tests/unit/dataactcore/scripts/test_get_fsrs_updates.py

Adding tests to the FSRS subaward update file
N/A
[DEV-10602](https://federal-spending-transparency.atlassian.net/browse/DEV-10602)

DEV-10602: subaward extract test

---

dataactcore/scripts/pipeline/get_fsrs_updates.py

Fixing the FSRS Extract that was untouched during the AssistanceListing updates.
N/A
[DEV-10381](https://federal-spending-transparency.atlassian.net/browse/DEV-10381)

[DEV-10381] Updating FSRS Export to support assistance_listing

---

dataactcore/scripts/pipeline/get_fsrs_updates.py
tests/unit/dataactcore/scripts/test_get_fsrs_updates.py

Updating SQL to use updated_at and speed up the whole script
Cuts down the query from over 4 hours to seconds
[DEV-10593](https://federal-spending-transparency.atlassian.net/browse/DEV-10593)

DEV-10593: FSRS extract performance

---

dataactcore/scripts/ad_hoc/generate_full_sam_fabs_export.py
dataactcore/scripts/pipeline/generate_sam_fabs_export.py
tests/unit/dataactcore/scripts/test_generate_full_sam_fabs_export.py

Creating a script to make a bulk dump of all active FABS records for SAM
Also updating the existing nightly script for a small performance increase
[DEV-10600](https://federal-spending-transparency.atlassian.net/browse/DEV-10600)

DEV-10600: fabs bulk dump script

---

dataactcore/models/lookups.py
dataactcore/scripts/setup/load_funding_opportunity_number.py

Add FON data dump to public bucket.
N/A

DEV-10687: data sources content update

---

dataactcore/scripts/pipeline/get_fsrs_updates.py
tests/unit/dataactcore/scripts/test_get_fsrs_updates.py

Removing the duplicates from the FSRS extract
N/A
[DEV-10657](https://federal-spending-transparency.atlassian.net/browse/DEV-10657)

DEV-10657: dedupe fsrs extract

---

dataactcore/scripts/setup/load_defc.py

Adding a DEFC skipped status labeled as exit code 3
N/A
[DEV-10490](https://federal-spending-transparency.atlassian.net/browse/DEV-10490)

DEV-10490: Adding Exit Code 3 Skipped Status to DEFC loader

---

dataactcore/scripts/setup/load_defc.py

After updating the date format, the diff check needed to be updated as well.
N/A
[DEV-10490](https://federal-spending-transparency.atlassian.net/browse/DEV-10490)

DEV-10490: Fixing DEFC Loader Diff Check after Date Reformat

---

dataactcore/scripts/ad_hoc/generate_full_sam_fabs_export.py
dataactvalidator/filestreaming/csv_selection.py
tests/unit/dataactcore/scripts/test_generate_full_sam_fabs_export.py

Fixing the script so it doesn't crash Jenkins instances when run
There is so much data being stored it must be streamed directly to a file rather than being kept in memory.
N/A

Fixing full FABS dump script

---

Dockerfile
requirements.txt
server_requirements.txt

Updating the Broker to Support Python3.12
N/A
[DEV-10715](https://federal-spending-transparency.atlassian.net/browse/DEV-10715)

[DEV-10715] Python 3.12 (on top of Python3.9)

---

.travis.yml

N/A
N/A
[DEV-10715](https://federal-spending-transparency.atlassian.net/browse/DEV-10715)

DEV-10715: Updating Travis to Run on Python3.12

---

dataactcore/scripts/pipeline/load_gtas_boc.py

Minor update to the BOC loader script to exit with a status of 3 if the load is skipped.
N/A
[DEV-10855](https://federal-spending-transparency.atlassian.net/browse/DEV-10855)

DEV-10855: BOC Loader Update

---

doc/SAM Assistance Listing Data Mapping.csv
doc/SAM Office Data Mapping.csv
doc/SAM Recipient Data Mapping.csv

Simply includes several csvs documenting how SAM's data sources map to their source tables in the Broker.
N/A
[DEV-10659](https://federal-spending-transparency.atlassian.net/browse/DEV-10659)

DEV-10659: SAM Data Mappings

---

dataactbroker/app.py

Adding URL and headers to verbose request logs

---

dataactcore/utils/fileBOC.py
tests/unit/dataactvalidator/validation_handlers/test_file_generation_manager.py

Forgot to set the agency filter
N/A
N/A

Fix: BOC comparison report submission filter

---

dataactbroker/handlers/generation_handler.py

Actually filter by agency code when error checking BOC
N/A
N/A

Fix: BOC comparison report error message

---

dataactbroker/handlers/account_handler.py
tests/unit/dataactbroker/test_login_routes.py

Updating `/v1/proxy_login` to use the `name` field instead of the `email` field at first.
N/A
N/A

Proxy Login Update

---

dataactcore/scripts/setup/load_location_data.py

Replacing city and county loader code to use new files
N/A
[DEV-11041](https://federal-spending-transparency.atlassian.net/browse/DEV-11041)

DEV-11041: switch county loader

---

dataactvalidator/validation_handlers/validator.py
tests/integration/error_warning_file_tests.py

For consistency in tests and upon request.
N/A
N/A

Fix: Sorting all lists in Errors/Warnings from SQL Rules

---

dataactcore/config.py
dataactcore/config_example.yml
dataactcore/models/lookups.py
dataactcore/scripts/ad_hoc/generate_full_sam_fabs_export.py
dataactcore/scripts/pipeline/generate_sam_fabs_export.py
dataactvalidator/filestreaming/csv_selection.py
tests/unit/dataactcore/scripts/test_generate_sam_fabs_export.py

Updating the FABS extract for SAM to include data in `dba_name` and to stream directly to the SAM bucket
Also making `auto` not poll the bucket but rather use a date instead.
[DEV-11084](https://federal-spending-transparency.atlassian.net/browse/DEV-11084)

DEV-11084: fabs extract updates

---

dataactcore/scripts/pipeline/load_federal_hierarchy.py
tests/unit/data/test_fh_full.json
tests/unit/data/test_fh_update.json

Updating the FH loader to combine all the office orgtypes over time for the same office.
N/A
[DEV-11160](https://federal-spending-transparency.atlassian.net/browse/DEV-11160)

DEV-11160: Combining all the Office OrgTypes

---

dataactbroker/handlers/account_handler.py
tests/unit/dataactbroker/test_account_handler.py
tests/unit/dataactbroker/test_login_routes.py

MAX secretly updated its casAttributes, causing our API users to be unable to login. This resolves that.
N/A
[DEV-11256](https://federal-spending-transparency.atlassian.net/browse/DEV-11256)

DEV-11256: MaxAttribute API Login Fix

---

dataactbroker/handlers/account_handler.py
tests/unit/dataactbroker/test_login_routes.py

Simply updating the proxy login endpoint for API Proxy Team.
N/A
[DEV-11313](https://federal-spending-transparency.atlassian.net/browse/DEV-11313)

DEV-11313: Proxy Login Endpoint Updates (dropping name, adding roles)

---

dataactbroker/routes/login_routes.py

Updating the date in the deprecation notice
N/A
[DEV-11314](https://federal-spending-transparency.atlassian.net/browse/DEV-11314)

DEV-11314: MAX deprecation date update

---

dataactcore/models/lookups.py
dataactvalidator/validation_handlers/file_generation_manager.py
tests/unit/dataactvalidator/validation_handlers/test_file_generation_manager.py

Updating the name of the GTAS Comparison Report file
N/A
[DEV-11310](https://federal-spending-transparency.atlassian.net/browse/DEV-11310)

DEV-11310: gtas comparison filename update

---

dataactcore/scripts/setup/load_location_data.py

Re-adds some legacy county data that's not present in the new county data needed for certain states.
N/A
[DEV-11621](https://federal-spending-transparency.atlassian.net/browse/DEV-11621)

DEV-11621: Legacy County Codes

---

dataactvalidator/config/agency_codes.csv
dataactvalidator/config/sqlrules/fabs3_5.sql
tests/unit/dataactvalidator/test_fabs3_2.py
tests/unit/dataactvalidator/test_fabs3_5.py

A couple small tweaks removing characters that unix-based systems ignore normally but that Windows systems can't handle
N/A
N/A

Setup fixes

---

dataactbroker/helpers/filters_helper.py
dataactcore/utils/fileA.py
dataactcore/utils/fileBOC.py
tests/unit/dataactvalidator/validation_handlers/test_file_generation_manager.py

Adding a function that can be used to move specific TASs between certain agencies
The function is called once for adding a TAS to an agency within the agencies filter and must be called manually to remove them from agencies at the same time as the agency filter for an AND statement.
[DEV-11251](https://federal-spending-transparency.atlassian.net/browse/DEV-11251)

DEV-11251: file a gtas report tas exception

---

APISubmissionGuide.md

Updates to the final URL and note for trailing slashes.
N/A
N/A

Fix: API Proxy Guide Updates (continued)

---

dataactcore/scripts/pipeline/generate_sam_fabs_export.py
tests/unit/dataactcore/scripts/test_generate_sam_fabs_export.py

Adding the ability to provide specific dates to create a file for in the FABS for SAM script
The more days that are included, the slower the script will run based purely on the fact that there will be more data. This is true now as well.
[DEV-11697](https://federal-spending-transparency.atlassian.net/browse/DEV-11697)

DEV-11697: sam fabs dates

---

dataactcore/scripts/pipeline/generate_sam_fabs_export.py

With the secrets mechanism requiring USAS aws access, we need to extract the uploading portion of this script to outside in the pipeline with the different bucket/region/credentials.
N/A
[DEV-11998](https://federal-spending-transparency.atlassian.net/browse/DEV-11998)

Fix: FABS for SAM Extract - Migrating Upload Functionality

---

dataactcore/broker_logging.py

Re-enables Granfana after confirming the URL is working in production for the Broker.

Fix: Re-enable Grafana

---

dataactcore/scripts/pipeline/populate_subaward_table.py
dataactcore/scripts/raw_sql/populate_subaward_table_assistance.sql
dataactcore/scripts/raw_sql/populate_subaward_table_contract.sql

Adding subaward report year/month to the populate SQL.  Also fixing populate subaward table metrics file name
N/A
N/A

Fix: SAM Report Date

---

dataactcore/scripts/raw_sql/populate_subaward_table_assistance.sql
dataactcore/scripts/raw_sql/populate_subaward_table_contract.sql
populate_subaward_table_metrics.json

Removing a couple of derivations in favor of using what we are sent
No longer deriving any sub tier country codes or the sub parent UEI name
[DEV-12285](https://federal-spending-transparency.atlassian.net/browse/DEV-12285)

DEV-12285: subaward non derivation

---

dataactcore/utils/fileBOC.py
tests/unit/dataactvalidator/validation_handlers/test_file_generation_manager.py

Remove financing accounts from both the file B data and the GTAS BOC data when creating the GTAS Comparison Report
N/A
[DEV-11468](https://federal-spending-transparency.atlassian.net/browse/DEV-11468)

DEV-11468: gtas comparison financing account filter

---

dataactcore/scripts/pipeline/load_park.py
tests/unit/dataactcore/scripts/test_load_park.py

Updating the PARK export file to contain the Compound Key for agencies.
N/A
[DEV-12633](https://federal-spending-transparency.atlassian.net/browse/DEV-12633)

Hotfix-12633: Updating export file for PARK

---

README.md

Adding basic github badges to the README.
N/A
[DEV-12390](https://federal-spending-transparency.atlassian.net/browse/DEV-12390)
[DEV-12390]: https://federal-spending-transparency.atlassian.net/browse/DEV-12390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-12390:  Readme Badges

---

.github/actions/run-pytest/action.yaml
dataactcore/scripts/pipeline/load_park.py
dataactcore/scripts/pipeline/load_program_activity.py
tests/unit/dataactcore/scripts/test_load_park.py
tests/unit/dataactcore/scripts/test_load_program_activity.py

Simply updating the Program Activity/PARK loaders to:
* report when no file was pulled and the load was skipped
* report its exit codes within the script calls and not through `initialize.py`
* Includes fixes for Github actions and previous USPS loader test issues
[DEV-12935](https://federal-spending-transparency.atlassian.net/browse/DEV-12935)
[DEV-12935]: https://federal-spending-transparency.atlassian.net/browse/DEV-12935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-12935: Program Activity Loader Slack

---

dataactbroker/handlers/generation_handler.py

Update `generated_detached_file` function to include updated submissions
[DEV-12925](https://federal-spending-transparency.atlassian.net/browse/DEV-12925)
[DEV-12925]: https://federal-spending-transparency.atlassian.net/browse/DEV-12925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV-12925] - add updated submissions to generated_detached_file

---

doc/CONTRIBUTING.md

Updating the contributing document
N/A
[DEV-12985](https://federal-spending-transparency.atlassian.net/browse/DEV-12985)
[DEV-12985]: https://federal-spending-transparency.atlassian.net/browse/DEV-12985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEV-12985: Update contributing
